### ISSUE TITLE
schematic: reproduce name2int error when reading manifest during validation

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#1009]
When reading or processing some manifests schematic crashes causing an error in the DCA:

Error in name2int: You specified the columns: 0, but the column names of the data are , Component, HTAN Participant ID, Treatment or Therapy, Treatment Type, Treatment Effect, Treatment Outcome, Days to Treatment End, Treatment Anatomic Site, Days to Treatment Start, Initial Disease Status, Regimen or Line of Therapy, Therapeutic Agents, Treatment Intent Type, Chemo Concurrent to Radiation, Number of Cycles, Reason Treatment Ended, Treatment Arm, Treatment Dose, Treatment Dose Units, Treatment Effect Indicator, Treatment Frequency, entityId 142022-10-24T12:34:42.175574+00:00 shinyapps[5806160]: 15: <Anonymous>

Reported in HTAN.  Error reported in schematic v22.10.3.

Also, reported in NF:

2022-10-25T20:46:17.612261+00:00 shinyapps[5727796]: Warning: Error in name2int: You specified the columns: 0, but the column names of the data are  , Component, Filename, resourceType, progressReportNumber, dataType, assay, platform, individualID, parentSpecimenID, runType, libraryPrep, comments, age, ageUnit, aliquotID, cellType, dataSubtype, diagnosis, dissociationMethod, eTag, fileFormat, isCellLine, isPrimaryCell, isStranded, libraryPreparationMethod, modelSystemName, nf1Genotype, nf2Genotype, nucleicAcidSource, organ, readDepth, readLength, readPair, readPairOrientation, readStrandOrigin, sex, species, specimenID, specimenPreparationMethod, tissue, tumorType, entityId 

NF's manifest is here:

[NF Processed Expression Data - Sheet1.csv](https://github.com/Sage-Bionetworks/schematic/files/10014436/NF.Processed.Expression.Data.-.Sheet1.csv)

AC: reproduce in latest version of schematic, diagnose and fix if the bug persists.

**Comment by milen-sage** [comment]
@milen-sage add the NF model.

**Comment by linglp** [comment]
> @milen-sage add the NF model.

I think this one is the NF model: https://github.com/nf-osi/nf-research-tools-schema/blob/main/nf-research-tools.jsonld 

^ I used it for schema viz.

**Comment by milen-sage** [comment]
@linglp thanks! Yes, that's the model.

**Comment by GiaJordan** [comment]
Per @/allaway on slack: the [data model](https://github.com/nf-osi/nf-metadata-dictionary/blob/main/NF.jsonld) for this dataType

**Comment by milen-sage** [comment]
Thanks @GiaJordan and sorry I got the model wrong! Adding a schema catalog as another product would help with that :) It sounds like you have everything needed to reproduce the NF example?

**Comment by milen-sage** [comment]
And here's the manifest for HTAN:

[HTAN Clinical Tier 1_ Therapy - Sheet1.csv](https://github.com/Sage-Bionetworks/schematic/files/10024592/HTAN.Clinical.Tier.1_.Therapy.-.Sheet1.csv)


It should reproduce with the latest HTAN schema.

**Comment by GiaJordan** [comment]
@milen-sage yes, thanks!

**Comment by GiaJordan** [comment]
@milen-sage `name2int` appears to be an R error, not Python. Currently manifest validation works fine with the command line and I was only able to reproduce using the invalid test manifests on the Testing DCA. 
I met with @afwillia and he'll also try to reproduce for more insight

**Comment by milen-sage** [comment]
Ah, yes this makes a lot of sense!

**Comment by milen-sage** [comment]
@afwillia could you add a quick note on how the issue was resolved. We reviewed the R code related to it, but just for completion on the issue. Feel free to close the issue after that.

**Comment by afwillia** [comment]
@milen-sage Schematic's validation result via reticulate returns a list type in R, with one of the elements is the column name. One validation rule did not return a column name, but `0` instead. The [DTable module in DCA ](https://github.com/Sage-Bionetworks/data_curator/blob/develop/modules/DTable.R)highlights errors by using the column name returned by schematic, however, in this instance, `0` is not part of the manifest. 

The edit in [this for loop in the DTable module](https://github.com/Sage-Bionetworks/data_curator/blob/de6eca75ad1b9efab457ad54d9c02ea4da5c8771/modules/DTable.R#L42) will no longer attempt to display errors that aren't named after a column in the manifest.

**Comment by GiaJordan** [comment]
@milen-sage additionally, the one validation rule that did not return a column name was `generateSchemaError`, which has now been updated to follow the convention of the other rules and return a column name instead of the column number.

**Comment by milen-sage** [comment]
Thanks! And it looks like both of these fixes have been released and confirmed as working in staging DCA instances (e.g. HTAN).
