### ISSUE TITLE
Use pdoc to generate documentation for schematic CLI

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#1027]
**Is your feature request related to a problem? Please describe.**
Use pdoc to generate documentation for schematic CLI so that we don't have to rely on readthedocs

**Describe the solution you'd like**

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by linglp** [comment]
@milen-sage Unfortunately, I don't think pdoc could generate documentation for our CLI commands. Their main feature is understanding numpydoc and google-style docstrings, and I can't find a flag for generating documentation for CLI.

**Comment by milen-sage** [comment]
We can address with a read-the-docs github service account this or next sprint - not urgent. To avoid being the bottleneck in this, feel free to create a new read the docs account to use in the github workflow setup.
