### ISSUE TITLE
schematic: define and encapsulate Synapse table business logic

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#1049]
Building up on #835, reorganize the business logic of Synapse table operations (e.g. into a class or other set of modules and interfaces), so that operations like 
- table replacement
- table upsert
are easier to maintain and positioned well when we are ready for a more general refactor of schematic's asset store interface. 

Finalize incorporating schematic_db as a dependency to schematic, if needed.

**Comment by GiaJordan** [comment]
Tests have been added for table creation and replacement. They currently cannot be run on the remote as part of our CI due to issues we're having when interacting with Synapse, but they run fine locally

**Comment by milen-sage** [comment]
Business logic completed - we can close the issue; refer to #1088 for ongoing work
