### ISSUE TITLE
Test 1

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#1066]

**Comment by MiekoHash** [comment]
Hi @milen-sage , I was trying to add different labels to this ticket from Sprint view and got a warning msg: "You don't have permission to edit this field.". Could you check my permission settings?

**Comment by MiekoHash** [comment]
Testing to see what happens if I link this to a D&T Op ticket: https://sagebionetworks.jira.com/browse/DTO-430

**Comment by milen-sage** [comment]
@MiekoHash hmm you should have admin access. This issue is linked to the schematic repo and the FAIR Data team has admin access there. Just to confirm, if you go here https://github.com/Sage-Bionetworks/schematic/labels are you able to add labels?

We used to work with ZenHub (a third-party GitHub extension for product/project management) for a period of time, and I am a bit worried that ZenHub is interfering with setting labels at the level of an epic. If yes, we can turn ZenHub off. We can then use a different way to organize epics using GitHub w/o the ZenHub extension; e.g. as outlined here: https://www.topcoder.com/thrive/articles/project-management-on-github

**Comment by MiekoHash** [comment]
Thanks, @milen-sage . I don't see any option to add labels and here's the png.

<img width="1478" alt="Screen Shot 2023-01-11 at 5 04 58 PM" src="https://user-images.githubusercontent.com/121985409/211951461-fe3e11e8-54f7-4456-aa3a-2247c1f91c02.png">

**Comment by milen-sage** [comment]
Ah @MiekoHash did you accept the invite for the GitHub FAIR Data team?

**Comment by milen-sage** [comment]
Let me resend it just in case.

**Comment by milen-sage** [comment]
Ok, interesting;  it looks like you were added to the team now. Could you try the labels again?

**Comment by MiekoHash** [comment]
Thanks, @milen-sage. I now see a gear icon on the issue and drop down menu appears. I also checked the sprint board view and labels show up there as well (pngs attached). 

<img width="715" alt="Screen Shot 2023-01-12 at 3 53 10 PM" src="https://user-images.githubusercontent.com/121985409/212205769-e9125922-27f5-4b7a-8412-5bbe3aaa6e7e.png">

<img width="376" alt="Screen Shot 2023-01-12 at 3 52 03 PM" src="https://user-images.githubusercontent.com/121985409/212205775-c1112547-06d7-4f85-8775-189330a261ce.png">
