### ISSUE TITLE
In JIRA: Allow schemas to pick from a list of validation rules

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic#1085]
As a data manager, I want to specify a set of validation rules, for each attribute in a table of records. And I want these validation rules ran during ingress for every table that contains that attribute. That enables validating data plausibility, completeness and conformance.

AC: 
- support more than two rules 
- ~execute rules in real time with delay of less than 2 minutes per rule~
- ~support only individual rules that fit w/in this latency: document the ones that don't~
Note (@GiaJordan edited to reflect addition of #1173 and separation issues that aren't closely related)

Requirements:

**Is your feature request related to a problem? Please describe.**
Some of my schema attributes will need attribute rule pairs that don't exist, in several combinations, and sometimes will need 3 or more.

**Describe the solution you'd like**
Instead of picking from a single rule or predefined pair of rules allow users to specify a list of rules, and make all the current rules available to pick from.

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by milen-sage** [comment]
Sync up with @linglp on latency benchmark

**Comment by MiekoHash** [comment]
Move to JIRA https://sagebionetworks.jira.com/browse/FDS-77
