### ISSUE TITLE
schematic: test, validate and release table update/upsert functionality

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#1088]
Following up on #835, #1049 and #921,  the business logic of table upsert has been developed but needs more testing (e.g. https://github.com/Sage-Bionetworks/schematic_db/issues/129) and validating with users that the functionality works as expected before releasing. 

AC: 
- ensure the feature works as expected 
- reach out to one or two stakeholders to consult them on how to validate the feature works

**Comment by GiaJordan** [comment]
Will also require #1077 and potentially #925 @milen-sage

**Comment by GiaJordan** [comment]
@brynnz22 @Bankso can put testing updates here for now

**Comment by AmyHeiser** [comment]
@andrewelamb since you mentioned in Jira https://sagebionetworks.jira.com/browse/FDS-55 that Upsert functionality already exists in Schematic, does that mean that this issue is no longer needed?  Or should we move to Jira to confrim? cc: @GiaJordan

**Comment by AmyHeiser** [comment]
Yeah lets chat, I see you have a work block this morning but if you can talk let me know

**Comment by AmyHeiser** [comment]
Closing this ticket since the functionality for Upsert is captured and in progress in Jira as is all of the related tickets linked here. cc @GiaJordan if you disagree we can reopen or move to Jira.
