### ISSUE TITLE
Attributes should be usable by more than one component

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic#1096]
**Is your feature request related to a problem? Please describe.**
In a schema.csv if an attribute is used by more than on component, when it gets converted to a jsonld, it is structured in such a way that the /explorer/**find_class_specific_properties** only returns that attribute for one component not both.

See this [slack.](https://sagebionetworks.slack.com/archives/C01ANC02U59/p1674837222896699)
I've preserved that jsonld [here.](https://github.com/CRI-iAtlas/iAtlasSchema/blob/develop/iatlas_schema.jsonld)

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by andrewelamb** [comment]
@milen-sage is this a good description of the issue?

**Comment by milen-sage** [comment]
Yes, good enough! We can refine on Mon.

**Comment by mialy-defelice** [comment]
**User Story:**
As a data modeler I want to be able to assign a specific property to more than one attribute/component and use a the endpoint get_class_specific_properties to return all of the attributes/components whose domain includes this property.

**Specific example:**
In Andrews example data model he assigned `genes_id` as a property of the following attributes/components: `genes_to_gene_sets`, `mutations`, and `publications_to_genes_to_gene_sets`

This is what we would expect to get after calling the `get_class_specific_properties` endpoint.
| attribute/component                    | expectation                                                          | reality                                        |
| -------------------------------------- | -------------------------------------------------------------------- | ---------------------------------------------- |
| genes_to_gene_sets                 | [genes_id, gene_sets_id]                                     | []                                             |
| mutations                          | [genes_id, name, mutation_type, mutation_code]| [mutationCode, mutationType, name                          |
| publications_to_genes_to_gene_sets | [genes_id, gene_sets_id, publications_id]                      | [genesId, geneSetsId, publicationsId]    |

**Desired Output:**
For each property recorded in the JSONLD want to save a list of all the corresponding Attributes/Components in its domain.

Looking at `genesId` for example:
```
{
            "@id": "bts:genesId",
            "@type": "rdf:Property",
            "rdfs:comment": "TBD",
            "rdfs:label": "genesId",
            "schema:domainIncludes": {
                "@id": "bts:PublicationsToGenesToGeneSets"
            },
            "schema:isPartOf": {
                "@id": "http://schema.biothings.io"
            },
            "sms:displayName": "genes_id",
            "sms:required": "sms:true",
            "sms:validationRules": [
                "matchAtLeastOne genes.id set error"
            ]
        },
```

`“schema:domainIncludes”` should instead be:
```
"schema:domainIncludes": [
            {
                "@id": "bts:GenesToGeneSets"
            },
            {
                "@id": "bts:Mutations"
            },
            {
                "@id": "bts:PublicationsToGenesToGeneSets"
            },
```

**Solution**:

Solution will likely come from changing how `property_attributes` are recorded in `get_property` in the `df_parser` and changing `find_class_specific_properties` to handle lists.
