### ISSUE TITLE
In JIRA: Change "uuid" column generated to "id"

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic#1098]
**Describe the solution you'd like**
Change the name of the uuid column generated by schematic from "uuid" to "id"

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by MiekoHash** [comment]
Move to JIRA https://sagebionetworks.jira.com/browse/FDS-70 cc: @andrewelamb
