### ISSUE TITLE
In JIRA: Allow schemas to refer to id column in validations rules

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic#1099]
**Describe the solution you'd like**
When a a validation rule is created like: "matchAtLeastOne patient.id" the attribute with the rule will be matched with the uuid's in the "id" column of the patient component even if patient doesn't have an attribute named "id"

See [this](https://github.com/Sage-Bionetworks/schematic/issues/1098)
Also [this](https://github.com/Sage-Bionetworks/schematic_db/issues/123)

**How important is this feature?** Select from the options below:
• 🌋 Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by milen-sage** [comment]
This feature would enable referring to IDs (and other reserved data model attributes) that are included in manifests and DB tables but are not explicitly defined in the semantics of the model.

**Comment by MiekoHash** [comment]
Move to JIRA https://sagebionetworks.jira.com/browse/FDS-77
