### ISSUE TITLE
Allow schema labels to be the same as display names

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic#1112]
**Is your feature request related to a problem? Please describe.**
When converting a schema.csv to jsonld, I would like the option to have the labels be the same as the names in the schema csv for both component names and attributes.

**Describe the solution you'd like**
` schematic schema convert` CLI should have an option for preserving the names in the schema.csv

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by mialy-defelice** [comment]
**Acceptance Criteria:**
- User can set a flag to use display names as schema labels in their model.
- Schema labeling should not interfere with submission and validation of the model.
- Check that manifests look as anticipated.


**Confirm the following:**
Use several models -- Example, HTAN, iAtlas
- [x] Manifests use schema label
- [x] Conditional formatting
- [x] Required formatting
- [x] Dropdowns
- [x] XSLX output
- [x] Download manifest from synapse
- [x] Submit manifest
- [x] Validate manifest

**Comment by mialy-defelice** [comment]
Related to #1166

**Comment by milen-sage** [comment]
There is a fix in schematic_db to avoid schema labels.
