### ISSUE TITLE
TT1 Research asynchronous API function calls in Schematic for Synapse manifest submission

### ISSUE THREAD

**Issue by MiekoHash** [Sage-Bionetworks/schematic#1120]
https://sagebionetworks.jira.com/browse/DCA-71

**Comment by MiekoHash** [comment]
Hi @milen-sage , This ticket is in the Backlog in TT1. I cannot figure out how to unassign sprint value in GitH.

**Comment by milen-sage** [comment]
I unassigned the sprint (a click on the currently assigned sprint, unassigns it).
