### ISSUE TITLE
schematic: allow using labels as column headers in templates instead of display names

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#1123]

**Comment by mialy-defelice** [comment]
This issue is based on a request by @lopierra that began as a slack conversation, which can be viewed [here](https://sagebionetworks.slack.com/archives/C01ANC02U59/p1675116264543529).

> in this [example manifest](https://github.com/include-dcc/include-linkml/blob/pl-updates/src/data/schematic/include_schematic_linkml.Condition.manifest.csv), the column headers are the displayNames  (e.g. Condition Source Text) that are more readable, but I would prefer to have the column headers be the labels (e.g. conditionSourceText) because they don't have spaces and are easier to work with programmatically.

User Story:
As a data curator I would like the choice to generate the manifest tables column headers with schema labels instead display names for programatic ease of use.

AC:
API and CLI have option to `--use_schema_label` as the column header when generating a manifest. Calling this label will set it to `True`, default is `False` and will default to using the display name.

**Comment by lopierra** [comment]
To clarify the above, I am only able to use `--use_schema_label` with `submit`. I am not able to use `get` to generate a manifest with schema labels as columns headers, and if I manually create a CSV with schema labels as column headers, `validate` will throw an error. So I am forced to use display names in R, which is not ideal.

**Comment by mialy-defelice** [comment]
Hey @lopierra,

Can you provide me with your model and a manifest with entries? I would like to validate and submit to test that everything is working as you are intending.

Thanks!

**Comment by lopierra** [comment]
Hi @mialy-defelice - here is our model in [YAML](https://github.com/include-dcc/include-linkml/tree/main/src/linkml) and [JSON-LD](https://github.com/include-dcc/include-linkml/blob/main/src/data/schematic/include_schematic_linkml.jsonld). 

I'm attaching a [test manifest](https://github.com/Sage-Bionetworks/schematic/files/10819158/htp_study.csv) for the Study component. 

An additional complication is that if I submit my own manifest with schemaLabels as headers, Synapse automatically capitalizes the first letter of each (so `studyCode` becomes `StudyCode`). Is there some way to suppress that, or do I need to open a ticket for Platform about this?

**Comment by mialy-defelice** [comment]
> An additional complication is that if I submit my own manifest with schemaLabels as headers, Synapse automatically capitalizes the first letter of each (so `studyCode` becomes `StudyCode`). Is there some way to suppress that, or do I need to open a ticket for Platform about this?

Are you submitting through the python or R client (using a table upload) or are you using Schematic?

**Comment by lopierra** [comment]
I am using schematic.

**Comment by mialy-defelice** [comment]
> I am using schematic.

@lopierra Okay, this is intentional in schematic to conform to synapse standards. We convert all headers to PascalCase during the final submission step. Are you always using camelCase? You can open a ticket with us.

@milen-sage do they need to be Class Labels or can they be Property Labels?

**Comment by lopierra** [comment]
Thanks - I will open a ticket. We chose camelCase as the standard for slot names in our LinkML model and PascalCase for the classes, so it would be good to have the option for submitting camelCase headers to Synapse.

**Comment by milen-sage** [comment]
Based on conversation with @lopierra this is not an urgent blocker and we'll resolve after refactoring schema parsers #857
