### ISSUE TITLE
TT1 Doc: Consolidate Data Development Workflow and Versioning

### ISSUE THREAD

**Issue by MiekoHash** [Sage-Bionetworks/schematic#1127]
We currently have two documents for "FAIR Data Development Workflow and Versioning".

Google Doc: https://docs.google.com/document/d/1z0DIN9rSoSoIaUttN1NMt7qImYMWhHC0QwO1WVPTvEQ/edit#heading=h.wxf4h0pu8mxl 

Confluence: https://sagebionetworks.jira.com/wiki/spaces/SCHEM/pages/2651553822/FAIR+Data+Development+Workflow+and+Versioning

Task: 
- Move "Data Flow App" section into Confluence, review the Confluence doc., and then deprecate the Google Doc. 
- "ProjecLive" is out of scope of this doc consolidation

Timeline: Having a consolidated confluence doc before the HomeWeek would be ideal but not supercritical.

AC: Contents approval from following reviewers:

- [ ] Schematic - @mialy-defelice , @GiaJordan , @linglp, @milen-sage 
- [ ] DFA: @lakikowolfe, @milen-sage  
- [ ] DCA: @afwillia, @milen-sage

**Comment by MiekoHash** [comment]
Moving  to sprint 5 for review task planning purpose.  cc @milen-sage

**Comment by MiekoHash** [comment]
Confluence page shared with reviewers.

**Comment by GiaJordan** [comment]
I've added my comments
