### ISSUE TITLE
In JIRA: Investigate `Test Schematic` workflow runtime

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#1141]
**Describe the bug**
Usually it appears that our automated tests of schematic complete in about 5 minutes or less. Lately, some of the tests have been running significantly longer, taking [15 minutes](https://github.com/Sage-Bionetworks/schematic/actions/runs/4116371463), [35  minutes](https://github.com/Sage-Bionetworks/schematic/actions/runs/4178654197), [1 hour](https://github.com/Sage-Bionetworks/schematic/actions/runs/4167643460), and [2 hours and 49 minutes](https://github.com/Sage-Bionetworks/schematic/actions/runs/4168434979) to complete.
Unsure if this is related to something in our code or changes to github, but wanted to make a not of the behavior

**To Reproduce**
1. make a commit to a dev branch on github to trigger automated tests

**Expected behavior**
Tests complete without significant delays in runtime

AC:
determine reason for extended runtime, and a potential remedy

**Priority** (select one)
- [ ] Minor ⬇️
- [x] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**

**Additional context**

**Comment by GiaJordan** [comment]
@milen-sage test runtime is starting to become a hinderance to development
cc @MiekoHash

**Comment by milen-sage** [comment]
Yes, this needs to get investigated. It may be related to other latencies we are experiencing too, so troubleshooting testing may provide insight into other latency reductions.

**Comment by MiekoHash** [comment]
Set to Sprint 6 so that I can move to JIRA.

**Comment by MiekoHash** [comment]
Moved to JIRA https://sagebionetworks.jira.com/browse/FDS-84
