### ISSUE TITLE
In Jira: Table Upsert - Add support for other login credential locations

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#1157]
**Is your feature request related to a problem? Please describe.**
Add support for pulling in usernames and auth tokens from `schematic-db` from locations other than `.synapseconfig`

**Describe the solution you'd like**
AC:
Check env for auth token
explore getting username from somewhere other than `.synapseConfig`

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by AmyHeiser** [comment]
Moved to Jira as FDS-304
