### ISSUE TITLE
In JIRA: Table Upsert - custom primary keys

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#1158]
**Is your feature request related to a problem? Please describe.**
Add support for user specified primary keys

**Describe the solution you'd like**
AC:

- [ ] functionality to let users specify their own primary keys
- [ ] functionality to update primary keys after upload of some manifests **if possible**
     - [ ] Also define behavior for changing primary key annotation on synapse

**How important is this feature?** Select from the options below:
• 🌋 Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by GiaJordan** [comment]
Tagging @brynnz22 and @aclayton555 to follow, will keep updated on progress

**Comment by aclayton555** [comment]
Thanks @GiaJordan ! Just to keep track, one question to confirm from our meeting was whether we can also have a combination of columns serve as primary key?

**Comment by GiaJordan** [comment]
@aclayton555 I believe just one per data type, but @andrewelamb can add more info as well.

**Comment by andrewelamb** [comment]
Yes, only one column.

**Comment by milen-sage** [comment]
@milen-sage and @AmyHeiser to confirm with @brynnz22, @aclayton555 on testing w/ modifications to the existing MC2 data model and check on time frame for custom IDs feature.

**Comment by MiekoHash** [comment]
Moved to JIRA: https://sagebionetworks.jira.com/browse/FDS-106
