### ISSUE TITLE
In JIRA: Table upsert - updating existing rows

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#1160]
**Is your feature request related to a problem? Please describe.**
Define behavior for adding existing primary keys to a new manifest with different metadata and uploading as a table with upsert.

**Describe the solution you'd like**
Users request ability to update existing rows while using upsert functionality
AC:
Define behavior and consider adding support for requested behavior

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Additional context**

**Comment by GiaJordan** [comment]
per @andrewelamb functionality already exists in upsert feature

**Comment by MiekoHash** [comment]
@GiaJordan  https://sagebionetworks.jira.com/browse/FDS-55
