### ISSUE TITLE
Numbers in the annotation key field in Synapse.org prevents google sheet manifest from being created in DCA

### ISSUE THREAD

**Issue by cconrad8** [Sage-Bionetworks/schematic#1194]
**Describe the bug**
When a user adds an annotation using synapse.org, then they can not create a google sheet manifest in the DCA if the annotation key added was a number.  

**To Reproduce**
1. Go to synapse.org
2. Click on a data file you want to annotate
3. Add a number to the "key" field (like 1 2 3). Save the annotation
4. Open the data curator app (NF for example) and try to annotate the same file.
5. An error will occur in that a google sheet manifest will not be created.  

**Expected behavior**
If someone annotates a file using synapse.org, the fields should show up on the data curator app manifest regardless of what the field is (number, string) 

**Priority** (select one)
- [X ] Minor ⬇️
- [ ] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**

**Additional context**
One of the NF data portal users encountered this issue because the person didn't realize that the annotations couldn't take numbers and only strings

**Comment by allaway** [comment]
So interestingly enough, I just encountered this same error again with a project that had "milestoneReportNumber" = 0. The valid values for this are '1, '2, '3, '4, (to 10), or Not Applicable. 

When I removed the 0s the error went away. In both the OP as well as in this comment, the error message in the log was:

`Warning: Error in eval: TypeError: '<' not supported between instances of 'int' and 'str'`

more context on the OP issue in slack:  https://sagebionetworks.slack.com/archives/C01ANC02U59/p1679333543710609?thread_ts=1679332132.834539&cid=C01ANC02U59
