### ISSUE TITLE
Add a suggested replacement in validation

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#1258]
**Is your feature request related to a problem? Please describe.**
Sometimes, our investigators submit a slightly wrong version of a correct term. Eg. the correct term for a particular mouse model could be Nf1flox/flox, but they will submit Nf1-Flox/Flox. 

**Describe the solution you'd like**
It would be helpful for the app/validation to suggest the closest match from the schema - e.g. "Did you mean Nf1flox/flox?" It would be *EVEN BETTER!* :) if the user could then just click yes to incorporate that change, rather than having to change the csv by hand. 

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**
Here's a guide to comparing text with different techniques and metrics: https://mariogarcia.github.io/blog/2021/04/nlp_text_similarity.html

**Comment by allaway** [comment]
Related to this, the current error message is not super helpful with large sets of valid terms:

e.g.:

'Nf1-Flox/Flox' is not one of ['hTERT NF1 ipNF95.11b C/T', 'JHU 2-103-PDX', 'cNF97.2a', 'GM23338', 'cNF04.9a', 'B6.129S2-Nf1tm1Tyj/J', 'sNF96.2', 'WT ES', 'M3 MPNST', 'sNF02.2', 'C57BL/6J', 'hTERT NF1 sipnNF95.12B', 'HEK293 NF1 -/- with R681X mNf1 cDNA', '3PNF_SiPSsv_MM_11', 'GM11602', 'GFAP-Cre; Nf1-G848R/Flox', 'HEK293 NF1 -/- clone 2', 'hTERT SC ipn97.4', 'Schwann cell NF1 -/- with R816X mNf1 cDNA', 'HEK293 NF1 -/- with WT tagged mNf1 cDNA', 'Nf1-/- HEK 293', 'iPSC NF1 +/- BJFF.6 bkgd', 'iPSC

**Comment by AmyHeiser** [comment]
Thanks for the feature request @allaway  We are now pointing users to our Jira Service desk for requests.  So I will move this one, but wanted to let you know since we don't monitor this any longer.

**Comment by allaway** [comment]
Thanks Amy! Maybe to prevent others from having issues get lost (or prevent me from making new ones here when I inevitably forget.... 😄 ), we could delete the issue templates from this repository and replace with a template that directs users to the service desk? What do you think? I am happy to make a pull request for this.

**Comment by AmyHeiser** [comment]
Thanks Robert!
