### ISSUE TITLE
Convert all in-code documentation to match style guide

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#128]
For example on well documented class with the correct style to be used by the documentation generator: 

https://github.com/Sage-Bionetworks/HTAN-data-pipeline/blob/dev/MetadataModel.py

We need to convert all of our incode documentation to this level and using that style.

**Comment by milen-sage** [comment]
We need to generate usage docs.

**Comment by ychae** [comment]
@milen-sage does the above PR close this issue?

**Comment by milen-sage** [comment]
not yet - I think it needs more work...

**Comment by ychae** [comment]
can re-open if a more urgent need for it arises

**Comment by ychae** [comment]
@milen-sage sounds good! I'll add it to one of the refactor milestones so we don't lose track of it.
