### ISSUE TITLE
Programmatic end-to-end example of data upload and curation

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#141]
We have documented the Data Curator App usage and provided data upload examples for Synapse (both via WUI and client): https://github.com/Sage-Bionetworks/HTAN-data-pipeline/blob/dev/DOCUMENTATION.md

Once we package the backend (#82) we should provide fully-programmatic data upload & data curation example as well, and link it in the documentation above (at least one site has requested support for this use case: OHSU (#91).

**Comment by milen-sage** [comment]
Marking as feature since this is both documentation and a user interface.

**Comment by ychae** [comment]
@milen-sage this is covered in the current HTAN docs. The schematic backend documentation task is being tracked in #362 -- would it be okay to close this?

**Comment by milen-sage** [comment]
yes, let's close - though I do want eventually to see a notebook containing a working end-to-end example... wish list.

**Comment by ychae** [comment]
Notebook ticket created :) #427
