### ISSUE TITLE
Handle translation between data models

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#164]
Some data models contain overlapping set of terms (i.e. synonymous terms). These overlapping terms can be translated automatically via json-ld. Implement/expose mapping and translation methods.

**Comment by milen-sage** [comment]
E.g. HTAN uses the GDC clinical data model; other consortia at Sage use CDISC specification; and yet other consortia use a mixture of data models. Often diseases designations have synonyms across all these data models.

JSON-LD mechanisms could be used to resolve synonyms via vocabulary terms "expansion" (e.g. to different, synonymous terms can be expanded to the same URI): 
- https://json-ld.org/spec/latest/json-ld/#iri-expansion-within-a-context
- https://json-ld.org/spec/latest/json-ld/#using-the-document-base-as-the-default-vocabulary

But there could be other approaches. We can spec out this feature further and triage it using @ychae's templates. I don't see it as being urgent, but it is probably very important.

**Comment by BrunoGrandePhD** [comment]
This issue will have to wait until I have a firmer grasp on JSON-LD and relevant RDF concepts. I'm slowly getting there.

**Comment by ychae** [comment]
@BrunoGrandePhD would this be part of the next phase?

**Comment by BrunoGrandePhD** [comment]
I'm under the impression that this feature isn't urgent, so it could wait until we have additional bandwidth on the project. 

@milen-sage: Your thoughts?

**Comment by milen-sage** [comment]
Yes, this is definitely next phase feature - when we have hired a person.

**Comment by allaway** [comment]
Updating/mapping to new values within a data model (e.g. changing `cell line` to `Cell line` and updating data to match) might also be a use-case for this feature: https://sagebionetworks.slack.com/archives/C01RKMZQBKL/p1638235706100300?thread_ts=1637365863.095300&cid=C01RKMZQBKL
