### ISSUE TITLE
Define Notification API on Synapsefor Images To Process

### ISSUE THREAD

**Issue by dgutman** [Sage-Bionetworks/schematic#180]
Synapse ingests everything.  DSA needs to have mechanism to know when an imaging data set is ready to be viewed in the DSA.  This means the system is at least pre-validated (i.e. file is on Synapse...)

Ideally API is such as:

1) Data is tagged as "Validation", "PreValidation"

2) API can be queries to get list of SynapseID,  S3Bucket Location, Synapse Filename, any other provenance 
   JSON!!!
3)  DSA queries API, gets list of Ingestable Images
4) Once images are synced/imaged/indexes on the DSA, system can send back a POST request listing status of image, detected image type, metadata, etc...
System returns the DSA Identifier, DSA Path, etc, etc...

System can also return image metadata to aid the data validation pipeline... may be useful for QC

**Comment by xdoan** [comment]
DSA API: https://imaging.htan.dev/girder/api/v1

**Comment by milen-sage** [comment]
For points 1, 2, 3, and 4 above, we can try hashing out the details in chunks. For the first chunk we can consider operating in one of these scenarios - and we can decide which scenario is most easily implementable/most relevant for HTAN (please feel free to add other scenarios if these don't make sense):

- scenario 1: I have images of type X (e.g. H&E) on Synapse (living on bucket x on AWS); I have the synapse links of the images; can I send the DSA a synapse link for each image and receive a piece of metadata for it containing "is the image healthy; link to the image thumb in DSA if healthy; metadata from the imaging RFC for type X that was in the image header"; the latter request for metadata corresponds to @dgutman's point 4 above.

"I" here refers to a service the DCC runs as part of the data curator any time a data contributor indicates a dataset contains an imaging data type. In this scenario, point 1 is covered: the image links we send to the DSA are tagged as 'PreValidated'; 2 is covered, we have provided Synapse links to the DSA; 3 is covered (e.g. the DSA requests the file from Synapse using the Synapse link). How long does the POST reply for point 4 take for each image (e.g H&E; how about a more complex image type)? 

The con for the scenario above is that it looks like the DSA must retrieve the image from Synapse?

scenario 2: I have images of type X (e.g. H&E) on Synapse (living on bucket x on AWS); I manage the bucket with images; can I send the DSA the bucket and receive a piece of metadata for each image containing "is the image healthy; link to the image thumb in DSA if healthy; metadata from the imaging RFC for type X that was in the image header"

"I" here refers either to a service the DCC runs as part of the data curator any time a data contributor indicates a dataset contains an imaging data type; or to a service triggered by a lambda function whenever a new image is added to the bucket. Points 1-3 are covered similarly to scenario 1 above; same question for point 4. How long does the POST reply for point 4 take for each image (e.g H&E; how about a more complex image type)? 

This is similar to scenario 1, but perhaps in this case there is a way to avoid DSA 'retrieving' images via http ? (E.g. the DSA "mounts" a set of buckets predesignated for imaging)? 

In either scenario, once we have the pieces of metadata corresponding to point 4, on "Synapse's" end we can validate the metadata and expose it, say, to the HTAN portal or other downstream services.

For this first chunk of work we can assume that both scenario 1 and 2 operate on public data. We can worry about using auth later once we pick a scenario?

@dgutman does it make sense to discuss this in the context of the API @xdoan linked above in a meeting? In general, we can set a small series of meetings where we cover first the questions above. Then, we can do implementation and testing on our end and have follow up questions and chunks of work (e.g. auth) covered in the next meetings?

**Comment by xdoan** [comment]
Notes frm meeting with Dave:

- He'll share a HTAN oriented set of APIs, can even customize eventually.

- Things are stored as folder > item > file/files on DSA and all can have metadata

- only takes a few seconds to return thumbnail/metadata

- DSA can have buckets in the assetstore and technically to check header metadata/file health/get thumbnail the files only need to be touched 

- How to get DSA aws s3 links to imaging files uploaded through Synapse to the general bucket. Or should we just make all imaging data a custom storage location even if they use the Synapsecilent so we can easily get the image details?

- possibility to mirror images in two places for storage vs performance, or to compress (will see response on RFC to compression)

**Comment by xdoan** [comment]
APIs walkthrough here: https://github.com/ncihtan/dsa-htan/tree/master/dsaSynapseIntegration

**Comment by milen-sage** [comment]
I think this is covered by the plan here: https://github.com/sage-bionetworks/htan-coordination/issues/69
