### ISSUE TITLE
Folder Level Permission Integration

### ISSUE THREAD

**Issue by dgutman** [Sage-Bionetworks/schematic#182]
OAuth provides used identity;  also need to develop service/API/method to sync DSA folder permissions with Synapse Folder PErmissions..

This can likely be done as a service on the SYNAPSE side

**Comment by milen-sage** [comment]
The synapse OAuth service also provides authentication that a given user has download access to a particular set of entities on Synapse. So we should be able to resolve folder permissions this way. Closing for now.
