### ISSUE TITLE
Validate all types of IDs

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#198]
E.g. in addition to schema validation and the existing per-attribute validation rules in schematic, we have use cases for the following cross-manifest validation rules:

- [ ] matchAtLeastOne(<source_component_name>.<source_attribute_name>, <target_component_name>.<target_attribute_name>): if defined for an attribute in the schema, find if among all accessible datasets there exists at least one manifest with Component column name that equals <target_component_name> and at least one manifest with Component column name that equals <source_component_name>. If yes, check whether each value in a column <source_attribute_name>  is present at least once among the values in columns <target_attribute_name>.

- [ ] matchExactlyOne(<source_component_name>.<source_attribute_name>, <target_component_name>.<target_attribute_name>): if defined for an attribute in the schema, find if among all accessible datasets there exists at least one manifest with Component column name that equals <target_component_name> and at least one manifest with Component column name that equals <source_component_name>. If yes, check whether each value in a column <source_attribute_name>  is present **exactly once** among the values in columns <target_attribute_name>, across all target component manifests.

The first validation rule is more important than the second one, and we can start there. May want to create separate GH issue(s) and label this one as an epic. The first validation rule by itself would likely involve quite a bit of work to make sure it works efficiently for many manifests; we may need to make use of the new table and fileview Synapse joins features.

**Comment by ychae** [comment]
@milen-sage is this part of the April release or afterwards?

**Comment by milen-sage** [comment]
that's simialr to what Ethan is doing w/ HTAN dashboard, so this is not critical for HTAN, but it would be useful to have for portal tables; so let's leave in this phase; we can move later

**Comment by ychae** [comment]
Acceptance criteria:
1. having the validation rules in the validation module

**Comment by GiaJordan** [comment]
Documentation addressed in #613
