### ISSUE TITLE
S3 Bucket Sync to Synapse

### ISSUE THREAD

**Issue by clarisse-lau** [Sage-Bionetworks/schematic#209]
Sync files stored in external S3 buckets to Synapse projects

-  set up AWS Lambda function to be triggered by object changes in S3 bucket
-  Lambda function will index files to Synapse via Filehandles based on example in docs: https://docs.synapse.org/articles/custom_storage_location.html#adding-files-in-your-google-cloud-bucket-to-synapse

**Comment by clarisse-lau** [comment]
Base usage implemented here: https://github.com/ncihtan/s3-synapse-sync 
Would love to get feedback on the setup/deployment process and lambda function!

**Comment by clarisse-lau** [comment]
To Do: Add AWS CLI deployment steps

**Comment by clarisse-lau** [comment]
@wlongabaugh @Gibbsdavidl @smrgit 
Any feedback here would also be much appreciated

**Comment by xdoan** [comment]
Now moved to https://github.com/Sage-Bionetworks/s3-synapse-sync for the Sage production server using CloudFormation to manage it. Currently testing file upload with this process.

**Comment by milen-sage** [comment]
Similarly to #210 new feature/bug requests can be handled in a separate issue.
