### ISSUE TITLE
GCP Sync to Synapse

### ISSUE THREAD

**Issue by clarisse-lau** [Sage-Bionetworks/schematic#210]
- Set up cloud function subscribed to Pub/Sub notifications from cloud storage bucket
- Object finalize/delete events trigger GC function to index files to Synapse

**Comment by clarisse-lau** [comment]
Code for base usage is here: https://github.com/ncihtan/gcs-synapse-sync 
Would appreciate any feedback!

**Comment by clarisse-lau** [comment]
@wlongabaugh @Gibbsdavidl @smrgit would love your feedback as well!

**Comment by milen-sage** [comment]
I think we are at a point where centers are testing the functionality, so any new feature/bug requests can be handled separately. I think we are good to close this one!
