### ISSUE TITLE
Develop QC module part of the HTAN data pipeline

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#215]
This should support:
- logical relationships between attributes (e.g. birth date shouldn't be after date of death)
- regular expression and data types (e.g. a date should be formatted properly; a numeric field shouldn't have text values)
- ID checks (e.g. a biosample ID referred to in assay data, should be present in list of biosamples)
- validation routines for various file types (e.g. imaging, gene expression matrices, ...,)
etc.

**Comment by thomasyu888** [comment]
These are definitely things that are done in GENIE.  Currently there is a `genie_registry` package: https://github.com/Sage-Bionetworks/Genie/tree/master/genie_registry, which contains all of this logic per filetype.

The improvement I want to make in the future is to use `jsonschema` validator.  We can convert the `csv` into `json` and send it through the validator.  There will be things that won't be able to validated such as birth date can't be after date of death, etc...

**Comment by milen-sage** [comment]
> There will be things that won't be able to validated such as birth date can't be after date of death, etc...

That's where the plug-in framework kicks-in. It'd be nice to be able to trigger workflows eventually, and make it more Synapse-independent,  but starting w/ custom modules could work.

**Comment by ychae** [comment]
closing as work is covered and continuing through the validation rules effort
