### ISSUE TITLE
Make valid values dropdowns in manifest be alphabetical

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#216]
Currently valid values for an attribute are derived from a dictionary based on the schema hence the order is not guaranteed. Order valid values alphabetically instead or preserve order of values based on the schema - this can be exposed via parameter to the manifest generation method.

**Comment by ychae** [comment]
@sujaypatil96 will this be part of the PyPI release?

**Comment by milen-sage** [comment]
Acceptance criteria - add alphabetizing as an option when generating manifests with dropdown lists.

**Comment by danlu1** [comment]
+1 to this feature and also, can we have an option to sort valid value with ascending/descending order?  See this example of householdIncome. 
<img width="218" alt="Screen Shot 2022-03-15 at 4 25 44 PM" src="https://user-images.githubusercontent.com/90745557/158488482-126ff9c1-c41f-4a40-ad4d-3c3d78af9238.png">

**Comment by GiaJordan** [comment]
Alphabetization of valid values has been implemented and will be available when PR #643 is merged
@ychae

**Comment by allaway** [comment]
It looks like this sorting is case-sensitive. Is this expected?

**Comment by ychae** [comment]
@GiaJordan can we make the alphabetization case-insensitive for Sprint 13?

**Comment by GiaJordan** [comment]
> @GiaJordan can we make the alphabetization case-insensitive for Sprint 13?

Sure, we can add it!

**Comment by GiaJordan** [comment]
Addressed in #830, generated manifests now look like:
![image](https://user-images.githubusercontent.com/61707471/179820773-ba01fa0b-8e02-4c71-a35c-fa9ce5fe95c4.png)
