### ISSUE TITLE
S3/Synapse Sync Testing

### ISSUE THREAD

**Issue by clarisse-lau** [Sage-Bionetworks/schematic#223]
Testing of Lambda function to sync S3 buckets and Synapse  (#209 )
Repository: https://github.com/Sage-Bionetworks/s3-synapse-sync

Things to test: 
- Setup/deployment procedure 
- Lambda functionality
- Bugs
- or any other suggestions for improvement

**Comment by vthorsson** [comment]
- Tested Lambda function set up via AWS Console
- Loaded files into test folder in test bucket and they appeared on synapse project web interface
- Sent some edit suggestions for README to @clarisse-lau

**Comment by milen-sage** [comment]
Since Ethan already tested as well I think we are all good and can close this issue.
