### ISSUE TITLE
GS/Synapse Sync Testing

### ISSUE THREAD

**Issue by clarisse-lau** [Sage-Bionetworks/schematic#224]
Testing of Google Cloud function to sync GS buckets and Synapse (#210 )
Repository: https://github.com/ncihtan/gcs-synapse-sync

Things to test: 
- Setup/deployment procedure 
- Code functionality
- Bugs
- or any other suggestions for improvement

**Comment by vthorsson** [comment]
Tested gcloud CLI tool instructions. 
gcloud functions proceeded , but asked 
```
“Allow unauthenticated invocations of new function [syn_create]? (y/N)?” 
```
(answered N)
and also threw a warning 
```
"Function created with limited-access IAM policy. To enable unauthorized access consider "gcloud alpha functions add-iam-policy-binding syn_create --member=allUsers --role=roles/cloudfunctions.invoker" 
```
but deployment looks successful

**Comment by vthorsson** [comment]
Test file creation on GCS , which was successfully mirrored on synapse web interface. Tested GCS file deletion as well, also successfully reflected on synapse project.  Auxiliary files often created with each such operation 
![image](https://user-images.githubusercontent.com/2837859/83472071-35bfa800-a43b-11ea-9542-19c9af756bcc.png)


![image](https://user-images.githubusercontent.com/2837859/83472037-1b85ca00-a43b-11ea-86f5-fddb57f5ae89.png)

**Comment by vthorsson** [comment]
Test repeated , with change made that instead of the 7 digit ‘Synapse user folder’ distinct folders at same level were specified for foldersToSync.  Files loaded to GCS again successfully reflected in synapse, and the auxiliary files were relegated out of the way to the synapse user folder

**Comment by clarisse-lau** [comment]
Google cloud sync function was also tested by Ethan, closing this issue.
