### ISSUE TITLE
Validation errors missing columns

### ISSUE THREAD

**Issue by xdoan** [Sage-Bionetworks/schematic#225]
No column name is stated in the message portion of the output in error messages. 

e.g for optional field and the dates were also deemed invalid because I put null in.

![Screen Shot 2020-06-03 at 7.59.26 PM.png](https://images.zenhubusercontent.com/5d8a98e53902630001ea7bc4/47e88cfe-6541-40ab-a5b8-768fa8092686)

When I just run the python code :

```
[  [2, 'Cryopreserved Cells in Sample', "'' is not one of ['No', 'Yes']", ''],
   [  2,
      'Wrong schema',
      "'Library Layout' is a required property",
      'Wrong schema']]

```

For upcoming beta testers I fixed it in R but the underlying message is still buggy.

**Comment by milen-sage** [comment]
Hmm, that's weird - we no longer have Library Layout in the scRNA-seq schema.
In the current scRNA-seq schema dates are all required, i.e.
- Library Preparation Date
- Single Cell Dissociation Date
- Sequencing Library Construction Date
- Nucleic Acid Capture Date

I can't reproduce optional fields being tagged as wrong when left empty/null. Could you attach here the manifest, component, and the jsonld schema you are testing with for the python code?

**Comment by milen-sage** [comment]
@xdoan is this still an issue (if so, I still can't repro and inputs above would be helpful).

**Comment by xdoan** [comment]
May have been output from the code in metadata_model_test_driver.py that used a provided jsonSchema. 

Now the error looks like this: are there supposed to be that may of the same messages?

```
[  [  2,
      'Single Cell Isolation Method',
      "'' is not one of ['Microfluidics Chip', 'FACS', 'Droplets']",
      ''],
   [2, 'cDNA Offset', "'' is too short", ''],
   [2, 'cDNA Offset', "'' is too short", ''],
   [2, 'cDNA Offset', "'' is too short", ''],
   [2, 'cDNA Offset', "'' is too short", ''],
   [2, 'cDNA Length', "'' is too short", ''],
   [2, 'cDNA Length', "'' is too short", ''],
   [2, 'cDNA Length', "'' is too short", ''],
   [2, 'cDNA Length', "'' is too short", '']]
```

**Comment by milen-sage** [comment]
I see; yes, if it was using a provided jsonSchema, we can ignore it.

I am not so sure about the multiple rows though... could you attach/link the manifest, schema, and component that resulted in this validation output?

**Comment by xdoan** [comment]
code:
```
import json
import os
import pprint

from MetadataModel import MetadataModel
from ManifestGenerator import ManifestGenerator

pp = pprint.PrettyPrinter(indent = 3)

inputMModelLocation = "./schemas/HTAN.jsonld"
inputMModelLocationType = "local"

# component = "FamilyHistory"
component = "ScRNA-seqAssay" 

mm = MetadataModel(inputMModelLocation, inputMModelLocationType)

print("*****************************************************")
print("Testing metamodel-based validation")
print("*****************************************************")
manifestPath = "../test.csv"

print("Testing validation with jsonSchema generation from Schema.org schema")
annotationErrors = mm.validateModelManifest(manifestPath, component)
pp.pprint(annotationErrors)```

schema: https://github.com/Sage-Bionetworks/HTAN_data_curator/blob/shiny-server/HTAN-data-pipeline/schemas/HTAN.jsonld 

manifest: 
[HTAN ScRNA-seqAssay - Sheet1.csv.zip](https://github.com/Sage-Bionetworks/HTAN-data-pipeline/files/4795522/HTAN.ScRNA-seqAssay.-.Sheet1.csv.zip)

**Comment by xdoan** [comment]
I also did a fresh git clone of the dev branch and it gave me the same error as above. It works on my local machine so I think there might be some server specific things going on.
