### ISSUE TITLE
getStorageDatasetsInProjects returns empty list

### ISSUE THREAD

**Issue by xindiguo** [Sage-Bionetworks/schematic#229]
I tested with both synapse IDs of a file view and a project. The function did not return the expected list of folders in the file view.

Note: my file view scope is a folder that has sub folders.

**Comment by sujaypatil96** [comment]
Could you show us the code/snippet, which you used to call the method? 

Did you check that there were no problems when trying to establish connection to Synapse (using the `synapseclient`)?

**Comment by xindiguo** [comment]
I was testing using [storage_test_drive.py](https://github.com/Sage-Bionetworks/HTAN-data-pipeline/blob/dev/storage_test_driver.py). Before executing, I commented out everything after line 39 and used my own file view synapse ID.

And I saw the welcome message for logging into Synapse, so I would assume my connection was established.

My file view's scope is a folder instead of the entire project. Not sure if this would make a difference.

**Comment by sujaypatil96** [comment]
Hi @xindiguo!

Could you the following steps:

- Change the value of "masterFileview" key in [config.py](https://github.com/Sage-Bionetworks/HTAN-data-pipeline/blob/dev/config.py) on [line #9](https://github.com/Sage-Bionetworks/HTAN-data-pipeline/blob/dev/config.py#L9) to "syn21823263".

- Pass the synID of the project i.e., "syn21542798" to the getStorageDatasetsInProject() function.

- Log the output of the local variable `foldersTable` that is implemented in the [SynapseStorage.py](https://github.com/Sage-Bionetworks/HTAN-data-pipeline/blob/dev/SynapseStorage.py) by adding the following lines in [Line #170](https://github.com/Sage-Bionetworks/HTAN-data-pipeline/blob/dev/SynapseStorage.py#L170)

```
print("====================================================")
print(foldersTable)
print("====================================================")
```

Please do check the `id` and `name` columns in the `foldersTable` dataframe. If so, then we can explain why it wasn't working for you.
