### ISSUE TITLE
Uploaded same Clinical Manifest but a new folder was created

### ISSUE THREAD

**Issue by xdoan** [Sage-Bionetworks/schematic#285]
in this folder https://www.synapse.org/#!Synapse:syn22694607 you can see the manifest CSV had a version history. The first manifest is just patient 12, the second is 12 and 15, and the third is also 12 and 15. I uploaded the same manifest to test syncing and a new folder was created for patient 15, so there are now two patient 15 folders.

**Comment by milen-sage** [comment]
Yes, I'll need to fix that as part of the #198.

**Comment by ychae** [comment]
@milen-sage is this part of this phase of work or the next?

**Comment by milen-sage** [comment]
this is actually related to portal tables, so this phase.

**Comment by milen-sage** [comment]
This will be resolved by PRs #622 #614
