### ISSUE TITLE
Modularize package configuration

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks/schematic#295]
I'm creating an issue to discuss what and how to modularize `schematic`'s configuration. Most of the work was done in #282 (merged and then reverted in #288), but a few things are left to do. If we start with where #282 left off, this is what needs to be done (influenced by discussion in #288):

- [x] **Move any changes to CLI scripts to a separate branch.** This way, we can confirm that the new configuration code can work on its own. 
- [ ] ~**Update all hard-coded file paths in the package.** Files that never change should be bundled with the package using [`pkg_resources`](https://kiwidamien.github.io/making-a-python-package-vi-including-data-files.html). Files that should or might be changed should be parameterized in the configuration file. The list below is compiled based on discussions [on Slack](https://sagebionetworks.slack.com/archives/C01ANC02U59/p1601076059077900).~
  - ~**Bundled files**~
    - [ ] ~class_json_schema.json~
    - [ ] ~property_json_schema.json~
    - [ ] ~schema.json~
    - [ ] ~biothings.jsonld~
    - [ ] ~all_layer.jsonld~
  - ~**User-configurable files**~
    - [ ] ~biothings.jsonld~
    - [ ] ~all_layer.jsonld~
- [x] **Add command-line interface to any scripts.** The list below is based on this [comment](https://github.com/Sage-Bionetworks/schematic/pull/282#issuecomment-700334683) by Milen.
  - [x] csv_to_schemaorg.py
  - [x] ???

Edit: Moving file bundling to separate issue.

**Comment by BrunoGrandePhD** [comment]
I think part of this work might want to include reorganizing the config key names to be a bit more intuitive.

**Comment by BrunoGrandePhD** [comment]
To continue our conversation from #288, I noticed a [new branch](https://github.com/Sage-Bionetworks/schematic/branches) called `develop-config`. However, I don't have access to the repo, so I wouldn't be able to commit to this branch (only to my fork). How do you want to proceed?

**Comment by sujaypatil96** [comment]
Let's leave the **cli-related** discussion for another thread/issue @BrunoGrandePhD.

> To continue our conversation from #288, I noticed a new branch called develop-config. However, I don't have access to the repo, so I wouldn't be able to commit to this branch (only to my fork). How do you want to proceed?

I think that's okay, right? In that you would issue commits to a branch on a local fork (fork on your account/profile), and then you can issue a PR to the `develop-config` branch?

**Comment by BrunoGrandePhD** [comment]
Sounds good. I'll submit PRs from my fork. 

During our HTAN stand-up this morning, you mentioned working with the new config code (and possibly the CLI scripts). Could you clarify what I could help with? Or am I off the hook for now (and if so, you can ping me whenever to help out with something)?

**Comment by sujaypatil96** [comment]
Oh, I'll work on the CLI scripts (inspired by the `csv_to_schemaorg.py` script that you modularized), and issue a PR sometime next week (for one or two of the modules). You can review them and let me know how we can improve them, and then we can propagate the same changes for the rest of the `examples` scripts. Does that sound like a plan @BrunoGrandePhD?

**Comment by BrunoGrandePhD** [comment]
👍

**Comment by BrunoGrandePhD** [comment]
Being addressed in #334

**Comment by BrunoGrandePhD** [comment]
To help keep these issues atomic, I'm going to move the sub-task related to bundling files in the repository to its own issue.
