### ISSUE TITLE
CSV to (JSON-LD) schema generation optimization strategy

### ISSUE THREAD

**Issue by sujaypatil96** [Sage-Bionetworks/schematic#296]
One possible solution to improve the overall performance of the schema generation process, besides actually trying to improve the existing parser would be to follow this strategy:

- The JSON-LD schema will need to be generated once (for the first time) using the current parser (using either `create_schema_classes()` or `create_nx_schema_objects()`) for a CSV file.
- For future updates to the CSV file/JSON-LD schema, create a small CSV file that includes only the parts of the schema that need to be added (newly) or edited.
- A new parser will parse the contents of this file and based on the presence (or absence) of the attribute, will decide whether to perform an edit/add operation(s) (using `edit_schema_object_nx()`/`add_schema_object_nx()` respectively), and update just that part/portion of the JSON-LD schema/file.

**Comment by ychae** [comment]
@sujaypatil96 can this ticket be closed with the above PRs?

**Comment by sujaypatil96** [comment]
@ychae: The new graph-based parser does improve the performance, but we haven't tried experimenting with this strategy yet. This issue definitely has much lower priority than others, but it's still useful to experiment and see if we can further improve our CSV to JSON-LD parsers' performance.

**Comment by ychae** [comment]
Thanks @sujaypatil96! I'll place it in the backlog for now and maybe can consider changing this to an epic if there are multiple components still needed for it. We can also move this up if it becomes something that's needed in the next month or so.

**Comment by ychae** [comment]
Has this been addressed by the optimization work that's been done or is it still on the roadmap?
