### ISSUE TITLE
CSV to JSON-LD generation automation using GH Actions

### ISSUE THREAD

**Issue by sujaypatil96** [Sage-Bionetworks/schematic#297]
We can setup a Github Action that automatically runs the `csv_to_schemaorg.py` script (via command-line utility) and generates the JSON-LD schema every time there is a new schema specification (CSV) that is pushed to the repo.

**Comment by allaway** [comment]
Example of such an action is here: https://github.com/nf-osi/nf-metadata-dictionary/blob/main/.github/workflows/schematic-schema-convert.yml
