### ISSUE TITLE
Add scoping of dataset to subfolders

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#303]
Currently schematic supports dataset scope defined in two ways:

1. top-level (root) project folder - all files in a root folder (and its subfolders) are considered part of the same dataset and are annotated together (i.e. all files are listed in the same metadata template)

2. a folder with annotation 'contentType' set to 'dataset' - all files in the 'dataset' folder (and its subfolders) are considered part of the same dataset and are annotated together (i.e. all files are listed in the same metadata template). The 'dataset' folder can be a subfolder in a project (i.e. it doesn't need to be root)

@xindiguo has code that can scope a dataset to a folder (not necessarily a root folder) in a project w/o requiring annotation 'contentType' = 'dataset' for that folder. 

@xindiguo could you

- [x] pull the latest code from develop or main
- [x] apply your dataset subfolder scope changes
- [x] PR the updated code to the branch develop-fha in schematic's upstream Sage repo

I will go over your code, incorporate and test.

Meanwhile, @xindiguo could you evaluate if option 2 above is working for you (e.g. perhaps data contributors can add this annotation to their dataset subfolders; that can be done in bulk from the main project fileview)? If/when you test that, could you include the code from these PRs https://github.com/Sage-Bionetworks/schematic/pull/301 and https://github.com/Sage-Bionetworks/schematic/pull/299, if they haven't been merged yet by that time.

Once we do the above, @xindiguo can check if https://github.com/Sage-Bionetworks/schematic/issues/274 is resolved. If it isn't, I'll coordinate with @xdoan on updating the data curator frontend to avoid any filename-entityid joins that can be/are done in the backend instead.

@sujaypatil96 once we've merged and tested the code changes above as necessary, I'll PR to the 'develop' branch any changes coming from @xindiguo's schematic fork's develop-fha branch.

**Comment by xdoan** [comment]
just a note, might be helpful to edit bullet points to checkboxes so they can be marked off when complete

**Comment by xindiguo** [comment]
- The dataset has always been scoped on a subfolder. 

- I have added the annotation `contentType = dataset` to the data folder and tested with the main branch code, and it gave me a empty list of folders.
<img width="554" alt="Screen Shot 2020-10-12 at 5 07 35 PM" src="https://user-images.githubusercontent.com/16565812/95800938-91cdef00-0cad-11eb-8e17-9f1969d446bc.png">


Data folder - https://www.synapse.org/#!Synapse:syn22028920
File/Folder view - https://www.synapse.org/#!Synapse:syn21823263/tables/

**Comment by BrunoGrandePhD** [comment]
@xindiguo: Did you ever got around this issue? If so, what was your solution in the end?
