### ISSUE TITLE
Disconnect from server on metadata template generation 

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#305]
@xdoan I was looking at CHOP data, e.g. folder MLL_877476_scRNA (but really anything else I've tried too, including non-CHOP data folders), 'Click to Generate Google Sheet Template' results in 'Disconnected from server' message. Any logs on the server?

**Comment by xdoan** [comment]
somehow its actually only the scRNAseq assay that isn't working, I am able to get other templates on the app. I pulled the latest updates from main. 

```
Warning: Error in py_call_impl: IndexError: pop from empty list

Detailed traceback: 
  File "/home/xdoan/ShinyApps/HTAN_Shiny/schematic/schematic/models/metadata.py", line 133, in getModelManifest
    return mg.get_manifest()
  File "/home/xdoan/ShinyApps/HTAN_Shiny/schematic/schematic/manifest/generator.py", line 215, in get_manifest
    json_schema = self.sg.get_json_schema_requirements(self.root, self.title)
  File "/home/xdoan/ShinyApps/HTAN_Shiny/schematic/schematic/schemas/generator.py", line 489, in get_json_schema_requirements
    process_node = nodes_to_process.pop(0)

  76: <Anonymous>


Execution halted

```

**Comment by milen-sage** [comment]
hmm let me check on my end as well.

**Comment by xdoan** [comment]
now the backend is viewing an old version `cd0d26a` (merging hotfix tables) before the #304 stuff and it worked, that's the version on the prod app now. I did not check other template generation when testing 304.

**Comment by milen-sage** [comment]
I can confirm the backend works for ScRNA-seqLevel1 with the [latest schema PR](https://github.com/Sage-Bionetworks/schematic/pull/304/files).

**Comment by xdoan** [comment]
I'm going to leave it at `cd0d26a` for now since it works, will continue to look into issues with the #304 being merged.

**Comment by milen-sage** [comment]
Sounds good - I see it works now. Can you confirm you experience (or not) the same issues with #304 on the curator dev app?

**Comment by xdoan** [comment]
bug fixed! not part of the other issue.
