### ISSUE TITLE
Create a relational database from json-ld schemas defined in schematic

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#315]
We can instantiate various databases based on json-ld schemas; one type is relational.

To have a functional database instantiation, we need functionality to 
- [x] create a set of tables based on components in a schema
- [x] relate those tables via foreign keys, based on component dependencies in the schema
- [ ] update all necessary tables based on a provided normalized or denormalized table following the schema (i.e. table columns correspond to attributes in the schema _in progress_
- [ ] configure db connection parameters (host, db name, credentials)

Similarly, we can instantiate and update Synapse tables whose relational schema is based on json-ld.

**Comment by ychae** [comment]
@milen-sage is this work for this phase (April 15) or next?

**Comment by milen-sage** [comment]
This is actually related to the 'portal tables' objective in our workstream, so I'd say let's have it on the radar for now though it's not on the critical path for HTAN's first release.
