### ISSUE TITLE
Logging to stderr

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#317]
Currently schematic outputs all errors, warning and informational messages to stdout.

This is not suitable for debugging w/in the context of shiny apps (there, only logs of stderr are stored) as we found out over the last couple of days with @xdoan; but is relevant to other contexts as well (server environments in general).

How about replacing all print statements with calls to a logging library handlers so that we have flexibility to print both to stdout, stderr and log files, at potentially different levels of verbosity (the latter is lower priority).

@sujaypatil96 could you take a look at how the synapse client currently handles that and see if we can have similar functionality in schematic?  https://github.com/Sage-Bionetworks/synapsePythonClient/blob/develop/synapseclient/core/logging_setup.py

**Comment by sujaypatil96** [comment]
PR #406 resolves this issue.
