### ISSUE TITLE
CLI scripts architecture discussion

### ISSUE THREAD

**Issue by sujaypatil96** [Sage-Bionetworks/schematic#328]
Issue to discuss where the CLI scripts will fit in, given our current directory/folder structure of our package.

Overall objective: Identify atomic functionalities, i.e., the functionalities should make sense as a "unit" by itself, and add as a script to the CLI module.

Example of "atomic functionality": `$ python cli/generate_manifest.py pos_args --opt_args`

The above command generates a manifest based on supplied arguments.

_Structure of the package_:
```
data/
docs/
cli/ -- new cli folder to be added here with atomic functionalities
examples/ (consider renaming to scripts) -- also CLI based, but still needs improvement
schematic/
tests/
.
.
.
```
List of "atomic functionalities" to be added to cli (list to be expanded):

| Core Module      | Module Functionality | CLI Utility |
| ----------- | ----------- | ----------- |
| Metadata Model      | getModelManifest       | get_manifest       |
| Metadata Model   | validateModelManifest        | validate_manifest       |
| Metadata Model   | populateModelManifest        | populate_manifest       |
|   |         |        |
| Manifest Generator   | get_manifest        | get_manifest       |
|   |         |        |
| Schema Explorer   | explore_class        | explore_class       |
| Schema Explorer   | explore_property        | explore_property       |
| Schema Explorer   | edit_class        | edit_class       |
| Schema Explorer   | update_class        | update_class       |
| Schema Explorer   | edit_property        | edit_property       |
| Schema Explorer   | update_property        | update_property       |
|   |         |        |
| Schema Generator   | get_json_schema_requirements        | get_validation_schema       |

Note:
- `get_manifest` (is the same in both the _Manifest Generator_ as well as _Metadata Model_) will make a call to the generic `get_manifest` method (found in _Manifest Generator_).

One of the projects I've been referring to is Sage's project `Genie`. Looking at the [cli implementation](https://github.com/Sage-Bionetworks/Genie/blob/master/genie/__main__.py) there, we could also think of implementing it within `__main__.py` in `schematic/` and indicating that as an "entry point" to the application.

What are your thoughts?

**Comment by sujaypatil96** [comment]
Results of discussion:

1. Some of the scripts will be moved from the `examples/` folder (in their current state) to the `cli/` folder. Some others will need modification(s) before moving.

2. Remove the current example scripts that showcase the usage of all the methods/APIs in the core modules. The `examples/` folder will provide usage examples only for the useful functions (i.e., those functions that are part of the bigger metadata submission process) that will be added to `cli/`'.

3. Documentation to show the usage of `cli/` scripts must be added.

**Comment by milen-sage** [comment]
@sujaypatil96 thanks for getting the discussion started on this.

Wrt get_manifest, let's expose only one method - i.e. the wrapper one with its corresponding parameters.

To the table above, let's also add methods to
- get valid values for a given attribute, based on the display name or the label of that attribute (i.e. the user can supply either display name or label)
- get required attributes for a given attribute, based on the display name or the label of that attribute
- check if an attribute is required, based on the display name or the label of that attribute
- add synapse store methods
--- get projects
--- get datasets for a given project synid
--- get files in a given dataset synid
--- get manifest from synapse based on a given dataset synid
--- submit manifest (wrapper allowing validation depending on passed parameters) 

In addition, let's see if the CLI table can include most of the schematic features related to the comment here 
https://docs.google.com/document/d/1MoTVogc5JouziQ9i7otf74qzBRIBHHNCJda6NAbRU_M/edit?disco=AAAAKhspxaY
More specifically, under the schema utilities section we have some functions that we can add to the table above.

**Comment by jaeddy** [comment]
+1 for `click`. It's really nice for _composing_ a CLI. However, that also implies a structure that's not as "flat" as what's proposed above. For example, with `click`, it's pretty easy to define a pattern like this:

```
schematic manifest get
```
or
```
schematic schema explore-class
```

Where the structure is generally:
```
<package> <subpackage> <operation>
```

While I can see pros and cons to this structure (it's totally subjective, and I've seen plenty of examples of both approaches in practice), I do like how this maps a little more closely to a RESTful API. For example, you wouldn't expect an endpoint like `/api/get_manifest/{id}`; it'd be a `GET` request to `/api/manifests/{id}`. So, basically, each subpackage might map to a `path` in the API, representing logically grouped operations around a particular type of object or task.

The downside to this convention is that the syntax could end up a little awkward in some cases — e.g., for `get_json_schema_requirements`, the command might be something like `schematic schema get-validation`... but we could probably work through these cases with reasonable solutions.

Anyway, `click` is totally a usable option even if you only want one level of commands, you just might not get the added benefit of being able to specify the CLI in a more modular way (e.g., each subpackage has its own "mini-CLI" that can be combined in `__main__.py` for the overall package CLI). I'll defer to you guys to decide which approach you like best, and then we can chat more about examples and structure. 🙂

**Comment by milen-sage** [comment]
I am also one of those people who likes more of a composed CLI vs a flat structure and agreed that it would get us closer to a REST API. +1 on click as well :)

**Comment by BrunoGrandePhD** [comment]
There isn't a timeline on this since this issue was created before the templates were instituted. 

I just thought I would mention that imCORE will eventually need the ability to validate metadata at the command-line at the end of a workflow (for generating downstream level-2 and -3 data) before uploading the metadata to Synapse. Because I don't want to contribute to an end-of-year rush, I would say that this would be great to have by the end of January (to help with triage and prioritization).

**Comment by milen-sage** [comment]
The timeline is a bit tighter from HTAN's perspective. HTAN would require programmatic workflow functionality in couple of weeks.

Technically all of the functionality is available through the package when installed even now, and as long as that's documented and we have usage examples that people can follow in their workflows, that would be sufficient for HTAN. That's a possible short-term solution that has benefits long term as well :)

However, if we can have a version of the CLI soon, even if it doesn't contain all of the functionality above but covers the most important features, that would make writing documentation and usage-example scripts much easier. We can discuss during our sync up tomorrow with @sujaypatil96 ?

**Comment by BrunoGrandePhD** [comment]
I mostly just wanted to vocalize what would be ideal from imCORE's perspective. In this case, since I have a vested interest, I could take a first stab at this issue (at least for the feature that I need) in January if @sujaypatil96 hasn't tackled it by then.

**Comment by jaeddy** [comment]
OK, as promised, here's a quick example to get started with `click`:

In a package I wrote called `wfinterop`, I have a subpackage named `config`. I can start my CLI by adding commands specific to the `config` subpackage.

```
.
├── wfinterop/
│   ├── __init__.py
│   ├── __main__.py
│   ├── config/
│   │   ├── __init__.py
│   │   ├── config.py # assume there's a method in this module named `show`
│   │   └── commands.py
│   ├── orchestrator/
│   └── <other-packages>
├── setup.py
└── README.md
```

... where `commands.py` looks like this:
```python

import click

from . import show


@click.group() # this defines my subcommand — i.e., `wfinterop config ...`
def config():
    """
    Manage app configuration.
    """
    pass


@config.command('show')
def show_config():
    """
    Show current testbed/orchestrator configuration.
    """
    show()
```

I might also wrap another method called `add-queue` that takes a `data` argument:
```python
@config.command('add-queue')
@click.option('--data')
def add_queue(data):
    """
    Add a workflow queue.
    """
    Queue.create(data) # not a real class :)
```

Imagine that I took a similar approach to specify the CLI for my `orchestrator` subpackage. Now, in `__main__.py` I can build the overall package CLI like this:

```python
#!/usr/bin/env python
import os
import sys
import logging
import pkg_resources

import click

from .config import commands as config_cli # get config commands
from .orchestrator import commands as run_cli # get orchestrator commands

logger = logging.getLogger()
logger.info("Starting `wfinterop`")


@click.group()
@click.option('--quiet', 'verbosity', flag_value='quiet',
              help=("Only display printed outputs in the console - "
                    "i.e., no log messages."))
@click.option('--debug', 'verbosity', flag_value='debug',
              help="Include all debug log messages in the console.")
def main(verbosity):
    """
    Command line interface for the `wfinterop` library.
    """
    if verbosity == 'quiet':
        logger.setLevel(logging.ERROR)
    elif verbosity == 'debug':
        logger.setLevel(logging.DEBUG)
    else:
        logger.setLevel(logging.INFO)


main.add_command(config_cli.config) # add config commands
main.add_command(run_cli.run) # add orchestrator commands


if __name__ == '__main__':
    main()
```

And now I can call the `show` method like this:
```
wfinterop config show`
```

or `add_queue`:
```
wfinterop config add-queue --data <input-data>
```

Note: you'd need to set the `entry_points` field in `setup.py` to create the CLI alias:
```python
    entry_points={
        'console_scripts': 'wfinterop = wfinterop.__main__:main'
    }
```

And there you have it! Easy, composable CLI with `click`. You can check out more of the code [**here**](https://github.com/jaeddy/workflow-interop/tree/add-cli/wfinterop)... but it's basically an in-progress feature branch that I never finished or merged (so not particularly functional).

**Comment by milen-sage** [comment]
Thanks @jaeddy !

**Comment by milen-sage** [comment]
@sujaypatil96 will take a stab at the CLI implementation using click for the methods outlined above.

**Comment by sujaypatil96** [comment]
Thanks everybody for your input on architecting/designing the CLI scripts structure. Closing this issue since we've incorporated this structure in our development workflow.
