### ISSUE TITLE
Error when creating Google Sheets manifest template when using "Bulk RNA-seq" data type (Level 1 or 2)

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks/schematic#333]
**Describe the bug**

When I try to generate a Google Sheets manifest template using "Bulk RNA-seq" data type (Level 1 or 2), I run into the following error (taken from the Shiny logs). This causes the Data Curator App to disconnect. Note that I'm using the HTAN schemas. On the other hand, I'm able to generate a template if I use one of the following types for the same dataset: "scRNA-seq Level 1", "scATAC-seq Level 1", "Clinical Tier 1: Demographics", or "Other Assay (Minimal Metadata)". 

Here's the [relevant line](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/schemas/generator.py#L511) in the `develop` branch (since I'm running off of `main`). I can't tell if there's an error in the HTAN schema for "Bulk RNA-seq", or if a condition should be added like [what's at the end](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/schemas/generator.py#L661-L666) of the following `while` loop. 

I have time to submit a PR if need be, but I wanted to check here to see if this has come up before. If this has been fixed with a more recent version of `schematic`, then perhaps a hot fix can be applied to `main` since I'm hesitant to completely switch to `develop`. 

```
Warning: Error in py_call_impl: IndexError: pop from empty list

Detailed traceback: 
  File "/home/bgrande/ShinyApps/schematic/schematic/models/metadata.py", line 133, in getModelManifest
    return mg.get_manifest()
  File "/home/bgrande/ShinyApps/schematic/schematic/manifest/generator.py", line 215, in get_manifest
    json_schema = self.sg.get_json_schema_requirements(self.root, self.title)
  File "/home/bgrande/ShinyApps/schematic/schematic/schemas/generator.py", line 489, in get_json_schema_requirements
    process_node = nodes_to_process.pop(0)
```

**To Reproduce**
1. In the Data Curator App, select any dataset available to you.
2. Select "Bulk RNA-seq Level 1" or "Bulk RNA-seq Level 2" as the data type.
3. Attempt to generate a Google Sheets manifest template in the next section.
4. You should see the Data Curator App crash. 
5. The log file for that Shiny instance should end with the error posted above.

**Expected behavior**
I should be able to generate a Google Sheets manifest template. 

**Screenshots**

**Desktop:** Google Chrome (86.0.4240.111) on macOS (10.15.7), although I don't think this factors in the error since this is running on the Sage Shiny server.

**Comment by xdoan** [comment]
good catch, thought I fixed the schema names on previous updates but with dev/prod duality the prod was using old schema names. has been updated now, lmk if you run into the same issue after refreshing.

**Comment by BrunoGrandePhD** [comment]
I can confirm that the new `config.json` fixes the issue. Thanks for the quick bug fix, @xdoan!
