### ISSUE TITLE
Write script that generates the config.yaml file

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks/schematic#336]
**Is your feature request related to a problem? Please describe.**
I'm thinking of how the config file will be distributed once `schematic` is deployed via PyPI. It would be confusing if the user installed `schematic`, but they still had to either download the `config.yml` file from the repo. 

**Describe the solution you'd like**
One possible approach is to expose a CLI script (that would get added to your path like other CLI scripts added in #334) that generates the config file based on values provided at the command-line. This also provides an opportunity to document the main user-configurable fields in the config file using the CLI usage documentation. This could complement any comments in the config file. 

Another advantage of generating the config file using a CLI script is that the script can perform some upfront validation on the user-provided values. For example, the script can confirm that the files exist, the URLs are accessible, the Synapse credentials work, the Google credentials work, etc. If something doesn't work, the script can provide a useful error message on what needs to be fixed. 

I'm thinking that the `config.yml` file currently in the root of the repo would be further de-HTAN-ified and bundled in the repo as a [mustache](https://github.com/noahmorrison/chevron) template, which can be rendered by the script on demand. 

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work. 

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months (_i.e._ whenever the package is deployed to PyPI)

**Comment by milen-sage** [comment]
Thanks for bring this up @BrunoGrandePhD! I've been thinking about some of the parameters in the config as well, and how we can be more flexible wrt what's hardcoded/included during installation vs what is generated vs what can be specified even further downstream as methods' arguments potentially overriding config values (which is likely a separate question from config generation). 

Let's think a bit more about this feature after it is triaged; also it could interact with changes related to #295 and #334, and to a lesser extent #335; we probably want to be thoughtful on the order in which it's implemented (e.g. after the code related to the issues/PR ^ is tested and integrated).

**Comment by BrunoGrandePhD** [comment]
I'm thinking of taking a stab at this once @sujaypatil96 is done working on #344. This script could become the first component for the `schematic` CLI using the `click` package, as described in #328.

**Comment by ychae** [comment]
@BrunoGrandePhD trying get a sense of where this is in term of priority -- is it something we'd like to have for the first PyPI release?

**Comment by BrunoGrandePhD** [comment]
It can wait until after the PyPI release because we can temporarily point to an existing template in the repository.
