### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/schematic#338]
Not really a "feature", but adding a ticket here for reference. 🙂

**Comment by milen-sage** [comment]
This could be an epic on its own :) but yes for now we can keep it as an issue that's not about a feature.

**Comment by ychae** [comment]
@jaeddy should we close this issue since the framework is in place? We could also rename the ticket and use it to track unit testing/code coverage for the PyPI release.

**Comment by milen-sage** [comment]
Yes, I think the framework is in place and we even [have some going on coverage](https://github.com/Sage-Bionetworks/schematic/runs/2034293543) :)

**Comment by ychae** [comment]
Will continue to increase the code coverage but can close this ticket as the central idea of it has been completed.
