### ISSUE TITLE
scRNAseq Lvl2 &3 schema issues

### ISSUE THREAD

**Issue by xdoan** [Sage-Bionetworks/schematic#340]
**Describe the bug**
1) https://docs.google.com/spreadsheets/d/1UapgIJxBRjLgpomdkteWGHLDKbawcnTwriQUiSiLC8E/edit#gid=0

https://docs.google.com/document/d/12GMuwm4cIbJSymX6VQJIGrc9d-BgWegsA0nSL57auko/edit#

For lvl 2 did you mean to change 

`Aligned read length | Read length used for alignment if hard trimming was applied`
 
to `Applied Hard Trimming`? they seem to cover slightly different use cases. (e.g. you'd want to know how it was trimmed if it was used)

2) and level 3 missing workflow version: https://docs.google.com/spreadsheets/d/1ux_pIH0JUFwKNINho64PH5BhevsR7yCGtpc5aewIfJw/edit#gid=0

https://docs.google.com/document/d/1nNz_Pds2onAoJQ0fCUCCNpvocCKixMK1oQmjiUKzp18/edit#heading=h.5zic3kd06aef

**Comment by xdoan** [comment]
see that 1) is fixed by #343 but still missing `workflow version` from Level 3 when I tested. I'll push Level 2 to prod!

**Comment by milen-sage** [comment]
Thank you for spotting that @xdoan -  #346 should address it.

**Comment by xdoan** [comment]
fixed by #346!
