### ISSUE TITLE
Show warning about invalid values (instead of rejecting input)

### ISSUE THREAD

**Issue by kthrog** [Sage-Bionetworks/schematic#341]
In metadata template CSV, warn user about invalid value(s) instead of rejecting the invalid input. This would allow the user to override the warning and enter an invalid value. 

_NF use case:_ our schema is always evolving, and we sometimes have new data types that are not yet represented in our schema. We want to allow our contributors to enter these values, even if they're invalid, if need be (after they see a warning).

[Example](https://docs.google.com/spreadsheets/d/1_owmb2_oNGie1qID_RKUc-enbA7IFdY68CMxNRfVMMw/edit?usp=sharing):
![image](https://user-images.githubusercontent.com/43977698/98181191-91450480-1eb7-11eb-9988-1d1b0238851e.png)

cc: @allaway

**Comment by milen-sage** [comment]
Thank you  for the comments and transferring - this will be fairly straightforward enhancement I think.

We might want to expose this as a google sheet style option in config: some users might prefer strict data validation enforcement in google sheets; others might prefer flexibility. (I'd be the latter.)

**Comment by kthrog** [comment]
I agree, @milen-sage -- making this a config option would probably be the best option, to allow different groups different levels of enforcement.

**Comment by allaway** [comment]
I believe this is the default behavior now, perhaps this issue can be closed.

**Comment by allaway** [comment]
Maybe I was mistaken about this: the default behavior still seems to be `strict=T`.
