### ISSUE TITLE
Bundle accessory JSON(-LD) files (and others) as package resources

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks/schematic#344]
**Is your feature request related to a problem? Please describe.**
The current setup requires that the user downloads/clones the repo in order to use accessible JSON(-LD) files included therein. However, this approach won't work once the package is published on PyPI, unless you force the user to also still download the repo, which would be a terrible UX. Another reason is that addressing this issue would permit the developers to remove a bunch of hard-coded (or needlessly configurable) file paths from the package. 

**Describe the solution you'd like**
In preparation for an eventual publication on PyPI, I propose that we use package resources as a means to bundle or "ship" accessory JSON(-LD) files with the module. Files that never change should be bundled with the package, _e.g._ using [`pkg_resources`](https://kiwidamien.github.io/making-a-python-package-vi-including-data-files.html). Files that should or might be changed should remains user-configurable in the configuration file (as achieved in #295). The lists below is compiled based on discussions [on Slack](https://sagebionetworks.slack.com/archives/C01ANC02U59/p1601076059077900). 

  - **Bundled files**
    - [ ] class_json_schema.json
    - [ ] property_json_schema.json
    - [ ] schema.json
    - [ ] biothings.jsonld
    - [ ] all_layer.jsonld
  - **User-configurable files**
    - [ ] biothings.jsonld
    - [ ] all_layer.jsonld

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work (PyPI deployment is still some time away, so this isn't urgent.)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months (I like to think that deployment to PyPI will happen in the next few months.)

**Comment by BrunoGrandePhD** [comment]
I suggest creating a `etc/` subdirectory within the `schematic/` subdirectory.

**Comment by BrunoGrandePhD** [comment]
Consider renaming the bundled files to use more intuitive names. For example, `schema.json` is fairly generic.

**Comment by milen-sage** [comment]
I agree with the proposed solution above. Let's add example.jsonld schema to the bundled jsonld files - that would enable users to play around with the package immediately after installation. We can add more examples of schemas for different use cases later as well.

**Comment by sujaypatil96** [comment]
Addressed in PR #347.
