### ISSUE TITLE
Recursive retrieval of files

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#350]
**Is your feature request related to a problem? Please describe.**
Our data contributors have been uploading a lot of severely nested directories. They don't have the computational savvy to flatten these directories. However, they'd like to have a "flat" manifest of these files for annotation purposes (e.g. like what you'd see in a fileview, where the directory structure is more or less no longer relevant). I think this is both a front and back end feature. 

**Describe the solution you'd like**
I'd like there to be an option to select a folder in the frontend, and during manifest generation, crawl into all subfolders and populate a manifest with all files within those folders.

**How important is this feature?** Select from the options below:
Important

**When will use cases depending on this become relevant?** Select from the options below:
Short-mid term. We can do hacky workarounds, but they basically involve manually adding files to the manifest once we've generated a template for the given assay/data type. 

Thanks for the consideration :)

**Comment by milen-sage** [comment]
@allaway if I understand it correctly, you are interested in this functionality: https://github.com/Sage-Bionetworks/schematic/pull/301 ? 

If you update the NF data curator app, pulling schematic from the main branch, this PR^ should do the trick? We are already using it for HTAN. E.g. here is an example of a folder with two levels of nesting (see path to file relative to dataset directory in Filename column below):
<img width="2346" alt="Screen Shot 2020-11-12 at 11 15 59 AM" src="https://user-images.githubusercontent.com/41303818/98985532-86eac200-24d8-11eb-8ad1-5b02402805f3.png">

Let me know if I am misunderstanding the feature request and what you need is different.

**Comment by allaway** [comment]
Thanks! this is, from what I can tell, basically what I was asking for! I'll assign this issue to me and close it if this is indeed what I was asking for.

**Comment by allaway** [comment]
D'oh, I now see that conversation that we had on that PR. I think i'm losing it :)

**Comment by milen-sage** [comment]
2020 has its ways to warp everything for sure :)

**Comment by allaway** [comment]
I'm trying to test this, but I get the error @xdoan mentioned in #286 

>So I'm running into issues bc you are merging into develop and @sujaypatil96 already merged the command line utils stuff that is not compatible with the frontend, so I get errors such as "ModuleNotFoundError: No module named 'schematic.utils.config_utils'"

>Can you merge to main or a new feature branch?

I just tried to run the NF Data Curator app off the `schematic` develop branch and got this same error. Can you please advise as to whether I'm doing something wrong, or if they are currently incompatible?

**Comment by allaway** [comment]
Nvm, I now see in a comment above that #301 was merged into main, not develop!

**Comment by allaway** [comment]
This appears to work for us as well! thanks!!

**Comment by milen-sage** [comment]
Yes, the functionality is already in main.

It is also in develop, but the schematic develop branch is in development (no pun intended :) - there are features on the develop branch that have not been tested with the data curator app, so I'd expect crashes due to say refactor.

Just saw that it worked for you on main - cool!
