### ISSUE TITLE
Prune and moduralize examples that are currently w/in each subpackage of schematic

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#354]
- Include all CLI functionality in the python schematic examples for each subpackage.
- Include all features functionality from the schematic [docs](https://docs.google.com/document/d/1gNUA1BpSP09LmU4GHp3Qrg3SocF5v1uR1XQdg3yiInA/edit?usp=sharing) in the python schematic examples for each subpackage.
- Remove functionality in the current examples that are outside the scope of the above
- Split up examples in modules that are topically organized.
- Update README for each subpackage to include CLI commands when available and provide links to the python example scripts for all features in the doc above.

**Comment by ychae** [comment]
@sujaypatil96 is this currently in progress?

**Comment by sujaypatil96** [comment]
@ychae: Much of the items from this issue were resolved in issue #360 (PR #392, #416), so I think we're good to close this issue for now.
