### ISSUE TITLE
Reuse column header sorting from existing manifest

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#366]
Currently schematic attempts to sort columns based on schema both when new manifests are created and when an existing manifest has already been provided and is just being updated.

If meanwhile the schema has been changed, the columns in the existing manifest and the attributes in the new schema may be mismatching - this may lead to an uncaught errors.

If there is an existing manifest we need to just reuse the column header order, for now; we can also issue a warning if the schema is mismatched. 

That way the user and downstream apps can handle the warning appropriately.

**Comment by ychae** [comment]
@milen-sage is this work for this phase (ending April 15) or next?

**Comment by milen-sage** [comment]
Nope - need to prioritize; likely not on table at least until April (would be a good first issue :).
