### ISSUE TITLE
Handle the case when a manifest already exists for a different data type

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks/schematic#374]
### Describe the bug

I was trying to generate a Google Sheets template for a "Bulk RNA-seq Level 1" dataset on Synapse, but the [result](https://docs.google.com/spreadsheets/d/1XPOGBBDqi4WZ58G2yQoE3MJaIMGzhHZuFh4xcEr61z8/edit?usp=sharing) was messed up. The columns names seem out of order (compared to [what](https://docs.google.com/spreadsheets/d/1pyPMkdEW-OD79tWyum2dlLbI6BOE2QFbwaxb8xRtlX0/edit?usp=sharing) I'm used to), and the notes on the column headers don't match the column names (it seems like they roughly match the expected order). 

### To Reproduce

1. Identify a dataset that has already been annotated by the Data Curator. 
2. Generate a Google Sheets manifest template for this dataset using a different data type. 
3. Compare the columns to a manifest template generated for an unannotated dataset. 

### Expected behavior

This is [what](https://docs.google.com/spreadsheets/d/1XPOGBBDqi4WZ58G2yQoE3MJaIMGzhHZuFh4xcEr61z8/edit?usp=sharing) I got. This is [what](https://docs.google.com/spreadsheets/d/1pyPMkdEW-OD79tWyum2dlLbI6BOE2QFbwaxb8xRtlX0/edit?usp=sharing) I expected. 

That said, I don't think this situation is going to be very common, so I think it would suffice to simply raise an error saying that a manifest already exists for a different data type. Then, the user can opt to delete or move the existing manifest.

**Comment by ychae** [comment]
Addressed in PR #496
