### ISSUE TITLE
Badly Formatted CSVs with empty column names throw an error upon validation

### ISSUE THREAD

**Issue by xdoan** [Sage-Bionetworks/schematic#376]
**Describe the bug**
Jackynn from MSK had this CSV she got from exporting from Excel (can't upload but its on slack if you want it)
<img width="493" alt="Screen Shot 2021-01-08 at 1 14 35 PM" src="https://user-images.githubusercontent.com/15043209/104064831-7a6ea700-51b3-11eb-8920-b527d6e59930.png">
 that has trailing column spaces (all the ,,,,, after the column names) that are incorrectly read as empty columns and given a column name in R, etc. Similar to the error we got in adding extra rows from excel to csv. 

**To Reproduce**
1. download the csv https://htanworkspace.slack.com/archives/G01AUKU8HJT/p1609954274101400?thread_ts=1607713396.074500&cid=G01AUKU8HJT
2. try to to validate it (demographics) on the app or backend
3. On the app for me it hangs and crashes the site until you refresh it a few times. 

**Expected behavior**
The empty columns should be stripped before validation, similar to completely empty rows.

**Comment by sujaypatil96** [comment]
Hi @xdoan. Can you attach a screenshot of the error you're seeing (on the R Shiny app, backend also if tested). I'm seeing the same set of errors on the backend when I run `validateModelManifest()` on the manifest file you've shared, with and without the trailing commas in the column names.

<img width="1112" alt="Screen Shot 2021-01-08 at 2 05 22 PM" src="https://user-images.githubusercontent.com/20239224/104069957-a4779780-51ba-11eb-85c2-ba3a998af4b6.png">

**Comment by sujaypatil96** [comment]
Hi @xdoan. Could you attach a screenshot of the error message you're seeing on the Shiny frontend? I validated (`validateModelManifest()`) the attached manifest against the `Demographics` component, and I'm seeing the same set of errors, both with the trailing commas and without them.

_Note: I did trim out the empty rows after line 58 before running this though._

<img width="1112" alt="Screen Shot 2021-01-08 at 2 05 22 PM" src="https://user-images.githubusercontent.com/20239224/104070309-6fb81000-51bb-11eb-925d-ce612071f463.png">

**Comment by xdoan** [comment]
What you have is the expected output, hopefully you can just trim any completely empty columns so this doesn't happen. 

The server timed out before I got the validation error returned. It just was processing forever (it is 9k rows etc). 

Log attached: 
The first part is basically how I read in the preview for the table, then it hung for like 2min and then upon refreshing it crashed and I had to refresh the server twice for it to be back. 
```
[WARNING] sys:1: DtypeWarning: Columns (17) have mixed types.Specify dtype option on import or set low_memory=False.

Warning: Missing column names filled in: 'X18' [18], 'X19' [19], 'X20' [20], 'X21' [21], 'X22' [22], 'X23' [23], 'X24' [24], 'X25' [25]
Parsed with column specification:
cols(
  .default = col_logical(),
  Component = col_character(),
  `HTAN Participant ID` = col_character(),
  Ethnicity = col_character(),
  Gender = col_character(),
  Race = col_character(),
  `Vital Status` = col_character(),
  `Days to Birth` = col_double(),
  `Year Of Birth` = col_double(),
  `Cause of Death` = col_character(),
  `Days to Death` = col_double(),
  `Year of Death` = col_double()
)
See spec(...) for full column specifications.
/opt/shiny-server/scripts/shiny-run: line 3: 30164 Terminated              /bin/bash --login -c "$SHINY_EXEC_COMMAND $SHINY_R_PATH $*"
```
