### ISSUE TITLE
Disconnect from the server during Synapse submission 

### ISSUE THREAD

**Issue by xindiguo** [Sage-Bionetworks/schematic#377]
**Describe the bug**
The metadata file has passed the validation but it showed an error message "Disconnect to the server" when trying to submit to Synapse

**To Reproduce**
1. Go to [HIV Data Curator App](https://www.synapse.org/#!Wiki:syn21823262/ENTITY)
2. Pick the 20201218_Pikachu folder in step 1
3. Go to Submit & Validate Metadata tab (please ask Xindi for the metadata file)
4. Upload, validate, and submit the file - see the error

**Expected behavior**
The metadata should assign annotations to the files 

**Screenshots**
![Screen Shot 2021-01-11 at 10 28 47 PM](https://user-images.githubusercontent.com/16565812/104277819-67cacb00-545c-11eb-9630-2d855b8279f4.png)

**Desktop (if applicable, please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Additional context**
Here is part of the log from the Shiny server
```
Warning: Error in py_call_impl: ParserError: Error tokenizing data. C error: Expected 25 fields in line 32, saw 26


Detailed traceback:
  File "/home/xguo/backend/schematic/schematic/synapse/store.py", line 405, in associateMetadataWithFiles
    manifest = pd.read_csv(metadataManifestPath)
  File "/home/xguo/anaconda3/envs/data_curator_env/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/xguo/anaconda3/envs/data_curator_env/lib/python3.7/site-packages/pandas/io/parsers.py", line 454, in _read
    data = parser.read(nrows)
  File "/home/xguo/anaconda3/envs/data_curator_env/lib/python3.7/site-packages/pandas/io/parsers.py", line 1133, in read
    ret = self._engine.read(nrows)
  File "/home/xguo/anaconda3/envs/data_curator_env/lib/python3.7/site-packages/pandas/io/parsers.py", line 2037, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 860, in pandas._libs.parsers.TextReader.read
 [... truncated]
  76: <Anonymous>

Execution halted
```

**Comment by xindiguo** [comment]
Updates: the submission was successful when tested with the first 9 rows of the file.

**Comment by xdoan** [comment]
it looks like we're getting a similar error and it seems like a common error in now pandas/python parses CSVs and expects them to follow the first row's pattern...adding @milen-sage bc it seems relevant to back end.

**Comment by sujaypatil96** [comment]
This issue was resolved in this [PR](https://github.com/Sage-Bionetworks/data_curator/pull/105).

**Comment by xindiguo** [comment]
The collaborator has ran into this error again using Safari Version 14.0.2. I will post the log later.

**Comment by milen-sage** [comment]
@xindiguo yes, please post the log snippet when you have a chance (could be a different issue than the above).

There is also another [PR](https://github.com/Sage-Bionetworks/schematic/pull/381) that @sujaypatil96 merged in 'main' about 2 hours ago; that might help, but would be nice to see the logs in any case.

**Comment by xindiguo** [comment]
The user was not certified.

**Comment by milen-sage** [comment]
@ychae is there a way to programmatically find if a user is certified (e.g. is there an error we can catch from the synapse client)?

**Comment by milen-sage** [comment]
ah - just saw the @xdoan has opened an issue on that https://github.com/Sage-Bionetworks/data_curator/issues/106 - we can track there.
