### ISSUE TITLE
Do not upload "nan" for blank values in manifest

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#402]
**Describe the bug**
This is related to #401 but distinct - blank values are currently uploaded as `nan`. This can cause issues with adding annotations in the future because synapse interprets nan as a `DOUBLE`. 

**To Reproduce**
1. Leave a field blank that is not required
2. Validate and upload manifest
3. Annotation on synapse is `nan` for the blank field. 

**Expected behavior**
I would expect no annotation to be uploaded for a blank field.

**Comment by allaway** [comment]
I was just wondering if there was an updated timeline for this? I tried to tackle this a couple weeks back but failed miserably. 

At the moment, I'm manually cleaning up all of the `nan`s as they come in, which is a bit of a headache.

**Comment by ychae** [comment]
Subset of #441

**Comment by milen-sage** [comment]
@GiaJordan another related issue! We'd close a lot by resolving #441 :)
