### ISSUE TITLE
Add configuration disabling use of multi-selection script while retaining list validation

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#405]
**Is your feature request related to a problem? Please describe.**
I am testing out the `list` validation rule and have encountered a few issues with the resulting manifests:
 * multi select doesn't appear to work properly in firefox
 * multi select requires authorization of script to see all sheets (likely to cause a lot of customer service overhead)
 * multi select script only works in google sheets and not excel - some med centers blocklist google drive/sheets/docs
 * dropdown disappears (this is expected but problematic in the firefox and excel scenarios listed above), so can't see any options 

**Describe the solution you'd like**

When "list" is a Validation Rule, treat it like any other key is treated, except permit listed values when validating in the Data Curator App. 

This would allow users to simply type in a comma separated list of valid values, using the dropdown as a reference (rather than multi-select), but the validation in the data curator app to will properly validate these "listed" values. Perhaps a schematic config parameter could be used to change this behavior based on community preference.
This is not a perfect solution, but the perfect solution of just having multiple-select natively would require google intervention. :) 

**How important is this feature?** Select from the options below:
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months
relevant now, but we can probably work around it for the time being. 

**Additional context**

**Comment by milen-sage** [comment]
@allaway try removing the master template config variable from the config (or leaving it as ''). The list validation should still work, though the multi-select feature would not be part of the google sheet (still the validator would expect comma-separated list of valid values, if an attribute has 'list' in 'Validation Rules' of the schema).

**Comment by allaway** [comment]
Will try this! What you describe is (I think) the same as what I am asking for!

**Comment by allaway** [comment]
Unfortunately this breaks @ manifest generation via the app:

Remove template ID variable, leave as '':

```
[WARNING] sys:1: DtypeWarning: Columns (49,51) have mixed types.Specify dtype option on import or set low_memory=False.

Warning: Error in py_call_impl: UnboundLocalError: local variable 'spreadsheet' referenced before assignment

Detailed traceback: 
  File "/home/rallaway/ShinyApps/NF_data_curator_staging/schematic/schematic/models/metadata.py", line 135, in getModelManifest
    return mg.get_manifest()
  File "/home/rallaway/ShinyApps/NF_data_curator_staging/schematic/schematic/manifest/generator.py", line 308, in get_manifest
    spreadsheet_id = self._create_empty_manifest_spreadsheet(self.title)
  File "/home/rallaway/ShinyApps/NF_data_curator_staging/schematic/schematic/manifest/generator.py", line 150, in _create_empty_manifest_spreadsheet
    spreadsheet = self.sheet_service.spreadsheets().create(body=spreadsheet, fields='spreadsheetId').execute()

  76: <Anonymous>


Execution halted


```

remove variable entirely:

```


[WARNING] sys:1: DtypeWarning: Columns (49,51) have mixed types.Specify dtype option on import or set low_memory=False.

Warning: Error in [[: attempt to select less than one element in get1index
  72: observeEventHandler [/home/rallaway/ShinyApps/NF_data_curator_staging/app.R#355]
   1: runApp


Execution halted



```

**Comment by milen-sage** [comment]
Thank you for trying this out! I see, yes - will make this configurable.

Also after trying setting the master template ID to just an empty google sheet, which works, I realized that the sheet notes on cells allowing lists, still point you to the 'Selection option' menu item. The menu items is no longer there since I am no longer using the master template that supports that... so we'd need to make a tweak to make this more configurable.
