### ISSUE TITLE
Speed up annotation retrieval from Synapse for large datasets

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks/schematic#411]
## Description

I noticed that the new annotation retrieval feature (implemented in #361) is slow, especially for large datasets. I generated a run time [profile](https://github.com/Sage-Bionetworks/schematic/files/6018362/profile.txt). It's my first time generating one of these, so bear that in mind. I'm also running into rate limits with Google's API (see #410), but I think I got the information I need. It does confirm that the annotation retrieval process is one of the slowest parts. For reference, here's the profiling command I ran:

```
poetry run python -m cProfile -s cumulative -m schematic manifest get --dataset_id syn4984604 --jsonld NF.jsonld --config tests/data/test_config.yml --sheet_url --data_type GenomicsAssay --use_annotations
```

I want to highlight lines 33-38 from the [profile](https://github.com/Sage-Bionetworks/schematic/files/6018362/profile.txt). The rows are ordered based on the time cumulatively spent in each function (see `cumtime` column). The total time spent according to the top row is 605 seconds. You can see that the one call to `getDatasetAnnotations()` takes up 527 seconds (first row below `[...]`), which represents the vast majority of the time spent during execution. 

The last row confirms that the bottleneck is indeed with the Synapse API, since `_getRawAnnotations()` is a simple wrapper around `restGET()`. You can see that `restGET()` is also included in the rows below, but we cannot conclude anything from it because that function can be called from anywhere (not necessarily for the annotation retrieval). 

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   2335/1    0.010    0.000  605.419  605.419 {built-in method builtins.exec}
   [...]
        1    0.001    0.001  527.485  527.485 synapse.py:512(getDatasetAnnotations)
     3513    0.030    0.000  489.277    0.139 sessions.py:546(get)
        1    0.033    0.033  487.881  487.881 synapse.py:527(<listcomp>)
     3505    0.131    0.000  487.849    0.139 synapse.py:478(getFileAnnotations)
     3508    0.029    0.000  487.582    0.139 client.py:3766(restGET)
     3505    0.104    0.000  487.298    0.139 client.py:1291(_getRawAnnotations)
```

While I'm looking at the profile, I also noticed that `getFilesInStorageDataset()` also takes up a non-trivial amount of time for a large dataset. On average, it takes 40 seconds to retrieve a list of 3505 files (see `percall` column). 

This function also happens to be called twice (see `ncalls` column), which seems unnecessary. I know that one of these two calls was added in this PR (in `getDatasetAnnotations()`), but I didn't realize this function could be so slow. I think he other call is made in `getDatasetManifest()`, but it seems excessive to compile a list of all of the files in the dataset just to find the manifest (unless the file list is cached). 

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   2335/1    0.010    0.000  605.419  605.419 {built-in method builtins.exec}
   [...]
        2    0.008    0.004   79.766   39.883 synapse.py:200(getFilesInStorageDataset)
```

### Getting annotations from Synapse

I'll contact John Hill for his suggestions on how to speed up annotation retrieval. A short-term solution might be the creation of a temporary file view to aggregate annotations. That said, I don't know if `schematic` can assume that users have a project where they can create file views. 

### Getting list of files from Synapse

We can probably work towards (1) speeding up the function itself (perhaps with the use of the same temporary file view mentioned above) and/or (2) making sure the function is only called once. 

## Feature Importance

Important, because the users cannot be expected to wait 20+ minutes for a manifest to generate. 

## Time Frame

Within the next month, because the NF community needs this feature soon.

**Comment by milen-sage** [comment]
This is great info @BrunoGrandePhD ! I have a refactor of the getDatasetManifest function laying around that doesn't rely on the Synapse file walker and will commit it today, you can review; it should eliminate this part of the bottleneck. The reason for the current behavior: I initially thought it was a good idea to treat fetching manifest files as a special case of fetching any kind of file - avoids implementing same logic two different ways. Though it does trade-off performance for generality - often the case :). Agreed it's overkill for just fetching manifests, and the logic is much simpler to just do that.

**Comment by BrunoGrandePhD** [comment]
I implemented file views to address this.
