### ISSUE TITLE
Auto-fit Google Sheets columns when pre-populating manifest template

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks/schematic#413]
**Is your feature request related to a problem? Please describe.**

When pre-populating manifest templates on Google Sheets, many values are truncated because the column widths are based on the column headers ([example](https://docs.google.com/spreadsheets/d/1BdOLIcTL6hbhk3H2FxQIGPsyvGN8ELl4gSrnMq2MHGQ)). It would be nice if the columns are auto-fitted to the content after it's been added. 

**Describe the solution you'd like**

It seems possible to do according to this StackOverflow [post](https://stackoverflow.com/a/49971230). 

**How important is this feature?** Select from the options below:

• Low - it's an enhancement but not crucial for work

This is a quality of life feature, so this isn't urgent. 

**When will use cases depending on this become relevant?** Select from the options below:
• Long-term (no urgency)

**Comment by allaway** [comment]
I agree that this is a nice to have. except `etag`, maybe. :o)

**Comment by BrunoGrandePhD** [comment]
We might eventually hide and/or protect the eTag and entityId columns to avoid confusing the user or giving them the opportunity to change the values.

**Comment by allaway** [comment]
+1, that sounds like a good solution. It could be helpful to have them
still around (even if hidden) for troubleshooting concurrency issues or
(maybe?) off by one errors, but hiding/protecting makes a lot of sense.

Cheers,
Robert
