### ISSUE TITLE
annotations supplant valid values when previous annotations exist

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#424]
**Describe the bug**
When a key/column has annotation values already defined for a file that is within the manifest, the list of valid values in the resulting manifest is populated using the unique list of column annotations, not the valid values from the schema.

**To Reproduce**

1. Use the current `develop` branch. 
2. Generate a manifest retreving previous annotations from the CLI eg: `schematic manifest get --title Soragni-Imaging --dataset_id syn18152772 --jsonld ~/Downloads/NF.jsonld --sheet_url True --data_type ImagingAssay --use_annotations`

**Expected behavior**
I expect to have the previous annotations pulled into the cells, but for the "valid values" dropdown to reflect the valid values in the schema. 

Here's an example of a manifest generated using the previous approach (which works, but doesn't retrieve the files' current annotations): https://docs.google.com/spreadsheets/d/1wdObZxBfKeb1S0_MPlbOP8SGnYsYbl5V4fuhRd0u-l4/edit#gid=0

Here's an example of a manifest generated using new approach (which retrieves the current files' annotation, but doesn't respect the JSON-LD valid values in all columns): https://docs.google.com/spreadsheets/d/1JPlIVRwwmwhmYbTAgx_hjZqTznG0_gHRBf1QaJjZoOE/edit#gid=0

I added @BrunoGrandePhD as the assignee because I already chatted with him about this over Slack, but please reassign if necessary!

**Comment by BrunoGrandePhD** [comment]
This is going to require some additional digging. I just generated a test manifest (see link below) using my latest code, which fixes the issue with the empty `Filename` column. Interestingly, Sheet2 is empty, so it might be using the old approach of storing valid values (_i.e._ in the data validation rule itself). 

https://docs.google.com/spreadsheets/d/1mPqShLtw5EPOm6zqL7TyJcSSm1Cplz2x9bw7KhpfPmM/edit#gid=0

@milen-sage: I was under the impression that the new approach (storing all valid values in Sheet2) was universally applied. If so, I'm afraid that I might have omitted that functionality when adding support for retrieving Synapse annotations. Could you point me to the relevant functions?

**Comment by milen-sage** [comment]
@BrunoGrandePhD you can take a look at the function [call here](https://github.com/Sage-Bionetworks/schematic/blob/07b589357ee93fcee6c62749d473f5f888d50075/schematic/manifest/generator.py#L590). Note on the develop branch the code only stores valid values in the 2nd sheet if there are [more than 10 items](https://github.com/Sage-Bionetworks/schematic/blob/07b589357ee93fcee6c62749d473f5f888d50075/schematic/manifest/generator.py#L586
) in a dropdown. If you change the 10 to 0 it would store valid values for all columns explicitly in the 2nd sheet.

**Comment by allaway** [comment]
Hi all, In case it is of interest or useful, I tested Bruno's changes in #425 and added in the one-line change described by @milen-sage above. This fixes the issues with the hidden sheet, but does not fix the behavior of the valid values being overridden by existing annotations. 

In this example, the third row has a pre-existing annotation `fileFormat = foo`: https://docs.google.com/spreadsheets/d/1qKgSj2RxxaZ9EQ7XueJvh2feY8z2vURrTKRcqX3BZXk/edit#gid=532294347

**Comment by BrunoGrandePhD** [comment]
Thanks for testing this, Robert! My week has been completely consumed by a blocker on HTAN, so I haven't been able to do any schematic development for the past week.

**Comment by allaway** [comment]
No worries! :) Let me know if there's anything else I can do on my end to help.
