### ISSUE TITLE
Automatically remove empty rows from synapse_manifest.csv files

### ISSUE THREAD

**Issue by inodb** [Sage-Bionetworks/schematic#431]
**Is your feature request related to a problem? Please describe.**
As part of HTAN we have received some metadata files where there are empty rows in the middle of the file. Currently empty rows are only removed at the beginning and end of the file

**Describe the solution you'd like**
Automatically remove any empty row (instead of just first or last)

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by ychae** [comment]
@milen-sage I assigned this to you but please re-assign as needed. Also, I added it to this phase since the timeline for it being relevant is within the next month.

**Comment by milen-sage** [comment]
yep - figured :)

**Comment by milen-sage** [comment]
@GiaJordan if you could trace the csv I/O in schematic (both @mialy-defelice and I can help with that, if you have questions around it), you can check if this trimming is done in the latest development code base. It very likely is and in that case we only need to communicate back to stakeholders. 

In light of issues #441 and #559, it's very likely we want to add/refactor logic in [df_utils](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/utils/df_utils.py). Note: [io_utils](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/utils/io_utils.py) may sound relevant but is mostly focused around json and schemas. In our larger-scope refactor we can name and restructure these utils modules appropriately.

**Comment by GiaJordan** [comment]
`trim_commas_df` added as step in the universal CSV import function so that it is applied every time a CSV that isn't a data model is read as a df.
