### ISSUE TITLE
Strategize handling of “na” / “blank” / “nan” values for filled manifest

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/schematic#441]
As @milen-sage @sujaypatil96 suggest, I post the issue in schematic here. 

`'blank'` in filled manifest are read as `'NA'` using `readr` in the front-end, but the `validateModelManifest` uses **absolute path** to read `'blank'` values in manifest as `''`. <del>In addition, `DT::formatStyle` function (used to highlight preview table) will NOT highlight the `'blank'`/`''` values.</del>

- [ ] Decide how to strategize handling of `'NA'` / `'blank'` / `'NaN'` on the data curator app end as well as schematic end.
  
  - For the front end's point of view, we can read blanks as "NA"  and change all "NA" to `""` after `readr::read_csv`.
  - Regarding of schematic, is it possible to let `validateModelManifest` read manifest from R variable instead of file path or output error blank values to `NA`? Otherwise, update front-end can still deal with this issue for now.

**Comment by allaway** [comment]
I am probably misunderstanding the suggestion, but pushing `" "` instead of NULL values as annotations cause will cause problems in synapse queries, facets, SRC tools.

e.g. the query `SELECT * FROM synXXXX where key is NULL` no longer works if blank values are `" "`. Similarly, the Synapse Portals rely on NULL values to know when something is left blank (e.g.: the `Not Assigned` values here are actually NULLs on synapse: 
<img width="323" alt="Screen Shot 2021-03-31 at 2 27 58 PM" src="https://user-images.githubusercontent.com/20408008/113213733-688a2680-922d-11eb-980c-0ef3c7e208d4.png">

**Comment by rrchai** [comment]
Hi Robert,

Thanks for explaining the potential problems in synapse if pushing `" "` values as annotations.

> For the front end's point of view, we can change 'blank' values to one space blank (' ') for both readr and validation results from schematic

Sorry about the confusion and unclear description. For an example, if user's uploaded manifest has an empty/NULL value which is supposed to be filled, the results in R from `validateModelManifest` will like the list below: 
```
> annotation_status[[10]]
[[1]]
[1] 6

[[2]]
[1] "Nucleic Acid Source"

[[3]]
[1] "'' is not one of ['Single Cell', 'Single Nucleus', 'Bulk Whole Cell', 'Bulk Nuclei']"

[[4]]
[1] ""
```
I was suggesting to change the NULL/blank to `" "` just in shiny codes in terms of `readr` and `validateModelManifest` results, so that the `DT::datatable` can recognize the matches and highlight the blank/NULL cells in validation section in the app.
- change NULL/NA to `" "` when we read the upload manifest
https://github.com/Sage-Bionetworks/data_curator/pull/129/commits/7f221f83cdf56d8b7ab09e060f383b6f72309476#diff-ee89f65a0b4e0dccabce1672d6d689b4e2b6ca51ea1e746bdda1eca94aaa6e0fL419-R420
- change  NULL values from schematic's annotation results  (`validateModelManifest`) to `" "` as well
https://github.com/Sage-Bionetworks/data_curator/pull/129/commits/7f221f83cdf56d8b7ab09e060f383b6f72309476#diff-ee89f65a0b4e0dccabce1672d6d689b4e2b6ca51ea1e746bdda1eca94aaa6e0fL459-R462

In the current shiny codes, the uploaded manifest from users will be read again when they submit the manifest to synapse (where NULL values is changed to "NA"). I am not sure if it will cause the problem in synapse.

Please feel free to let me know if it is still not clear.

**Comment by allaway** [comment]
Thanks for clarifying, Rong! That makes sense, it sounds like i was misunderstanding. 

I think your proposal makes sense. Another option for your consideration is switching to `reactable`, which has pretty comprehensive support for conditional styling, and might work without having to having recode data `NA`s or `""`s to something else: https://glin.github.io/reactable/articles/conditional-styling.html 

Benefit to reactable: more powerful styling (see [examples](https://glin.github.io/reactable/articles/cookbook/cookbook.html))
Downside to reactable: no server-side rendering like DT, but seems to be pretty performant with 100k rows, so might not be an issue for the DC app. 


Re: the actual behavior of annotations returned to Synapse, I think at present the app/schematic returns the string "NaN" if values are blank (at least, with the current NF version this is the case, the core version might not do this anymore).

**Comment by allaway** [comment]
Here is a related issue to my last sentence, but it sounds like you are talking in this issue only about the front end: https://github.com/Sage-Bionetworks/schematic/issues/402

**Comment by rrchai** [comment]
Thank you for the suggestion, Robert! `reactable` looks like a powerful tool to customize styling of data tables. I will look into it and I think it will be super useful when we need more styles on data table.
>In addition, DT::formatStyle function (used to highlight preview table) will NOT highlight the 'blank'/'' values.

I just realize it is not reproducible, so I can just simply change "NA" to `""` in the front end and have updated the issue.

**Comment by milen-sage** [comment]
@GiaJordan let's talk about this issue during sprint planning, as well. Since it touches both on front end tools and schematic it might require a bit of coordination across the team.

**Comment by milen-sage** [comment]
Acceptance criteria - the empty values in manifests should be stored as blanks; similarly in annotations the empty values should show up as NULL on Synapse. Confirm w/ @allaway.

**Comment by allaway** [comment]
Confirmed!

**Comment by milen-sage** [comment]
:) Yes, I think we are @allaway - @GiaJordan will share a sample project with some annotations for you to take a look at, just in case.

**Comment by GiaJordan** [comment]
I've just shared an example data file with you both, @milen-sage when I showed you the file the annotations displayed a string NULL, I've changed it to just have no value for the annotation as per @allaway

**Comment by allaway** [comment]
Hi @GiaJordan, could you change my permission to `Can Download`? I cannot see the file contents w/`Can View`. Thanks!

**Comment by GiaJordan** [comment]
@allaway updated!

**Comment by allaway** [comment]
Thank you! The manifest looks good to me! I also looked at the annotations, and was curious how you managed to get the blank annotations to show up?
<img width="456" alt="Screen Shot 2022-02-15 at 1 43 20 PM" src="https://user-images.githubusercontent.com/20408008/154154388-e13fc3ee-f240-46c0-ba58-9a0eb99f29bd.png">

I would have thought with a NULL value, Synapse would not set the annotation at all. But maybe I am remembering the behavior of this incorrectly :)

**Comment by GiaJordan** [comment]
@allaway the values are saved in python as empty strings: `''`.
`None` values appeared as 'None' and `NULL` values appeared as '0' in Synapse. Will this current solution work or would you rather one of the latter two options?

**Comment by allaway** [comment]
Thanks for clarifying! That's interesting. I'd like the values to be treated by Synapse as NULL values, though I would have thought that a python `NULL` value would have been interpreted as a null by `synapseclient`, not a 0. I wonder if this is being coerced to a string somewhere in `schematic` before it hits `synapseclient`? Or `synapseclient` is coercing to a string?

**Comment by GiaJordan** [comment]
@allaway You're correct synapse was changing the values to strings in `annotations.py`. Moving forward, I'll been using the value `None` as opposed to python's object `NULL`. I've updated `annotations.py` to recognize and pass on `None` types and values for empty annotations to be uploaded to Synapse. However, it appears Synapse isn't configured to allow null annotation values to be uploaded currently. When doing so I get an error message: `400 Client Error: Property: 'value' is required and cannot be null`. 
I'll to look into this more tomorrow 

cc @milen-sage @ychae

**Comment by allaway** [comment]
@GiaJordan - that all makes sense. Thanks! In that case, I think that the correct action would be to skip blank/None annotations entirely (i.e. they make it into the manifest csv, but not applied as an annotation). That way, if the file is in a View, files with null/missing annotations will be queryable like so: 

https://www.synapse.org/#!Synapse:syn16858331/tables/query/eyJzcWwiOiJTRUxFQ1QgY291bnQoKikgRlJPTSBzeW4xNjg1ODMzMSB3aGVyZSB0dW1vclR5cGUgaXMgbnVsbCIsICJhZGRpdGlvbmFsRmlsdGVycyI6W10sICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNSwgInNvcnQiOltdfQ==

@milen-sage - what do you think?

**Comment by GiaJordan** [comment]
Modified acceptance criteria: the empty values in manifests should be stored as empty strings; in annotations the empty values should not appear but will still be present as empty strings in the manifest, so as to be queryable in Synapse.

Please confirm @allaway @milen-sage 

The example project I shared and a file view for it have also been updated to reflect these so you can take a look at that as well

**Comment by allaway** [comment]
The fileview you shared looks good to me. Thanks @GiaJordan!
