### ISSUE TITLE
Age in Days Validation

### ISSUE THREAD

**Issue by inodb** [Sage-Bionetworks/schematic#442]
**Is your feature request related to a problem? Please describe.**
We have had a few centers that submitted incorrect Age data (e.g. in years instead of in days). As well as including decimals instead of just integers. There are also some other issues related to privacy, such as according to law age should be indicated as  <18 and >90.

**Describe the solution you'd like**
When any age related data is submitted the submission fails, notifying the center they should fix it

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Additional context**

**Comment by mialy-defelice** [comment]
Hi @inodb! 

A question regarding this issue. 

- How do you anticipate the age being indicated in these groups of <18 and >90, as days(ints) or these string literals? 

- Do you want the validation to check the age and issue an error for the center to re-enter the value as '<18' or '>90' -- in that case the validator needs to be able to check for these specific entries and ages in days that fall between these ranges, as well that the day entries are formatted as ints.

-  Do you anticipate a conflict with reporting as both days and years?


It's all doable, but I just want to make sure I am understanding the solution correctly.

Thanks!!

**Comment by ychae** [comment]
will be addressed by PR #509

**Comment by ychae** [comment]
Need to update to match the HTAN schema

**Comment by mialy-defelice** [comment]
@inodb I remember having a convo that it might be actually useful to keep the age submission and filter out later (before it gets to BQ or the portal). In this case could we close out this issue since it would be downstream of schematic?
