### ISSUE TITLE
Revise schematic_service_account_creds.json documentation to help users understand what this is and why they might do it

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#445]
**Describe the bug**
Documentation doesn't sufficiently describe how to do this step: "Use the schematic_service_account_creds.json file for the service account mode of authentication (for Google services/APIs)."

**To Reproduce**
Read the docs :) 

**Expected behavior**
I would expect this section to describe how to create or obtain this json. 

**Screenshots**
n/a

**Desktop (if applicable, please complete the following information):**
n/a

**Additional context**
n/a

**Comment by allaway** [comment]
I guess a related thing that I do not understand in the docs: is the OAuth2 credentials/token.pickle method of authentication sufficient, or do I also need to define `schematic_service_account_creds.json`? As far as I can tell, the answer is yes, both need to exist to run schematic.

**Comment by sujaypatil96** [comment]
Can this issue be closed @allaway? Like you mentioned in your followup comment, the relatively new `--oauth` flag allows you to choose between using `OAuth` and the `Service Account`.

**Comment by allaway** [comment]
Hi Sujay, Sorry for not being clearer: I think the issue is primarily that there is not enough context. What is the service account mode of authentication? Why would a user want to do this instead of oauth?

**Comment by sujaypatil96** [comment]
I see, okay. I think there's sufficient documentation on the Google API docs.
1. Authentication overview: https://cloud.google.com/docs/authentication
2. Service Account authentication: https://cloud.google.com/docs/authentication/production

But what you're saying does make sense. I'll add a few more lines of context here ([details.md](https://github.com/Sage-Bionetworks/schematic/blob/develop/docs/md/details.md)). Describing the `service account` and its usage in a little more detail. I'll tackle this in a future documentation update PR.

**Comment by allaway** [comment]
Thanks, I agree that google's docs are probably sufficient for the how (which was the original title of this issue - I'll change that), but the why and how it relates to schematic is something I was also struggling to understand. Thanks!!
