### ISSUE TITLE
Missing synapse_config key when running tests

### ISSUE THREAD

**Issue by hweej** [Sage-Bionetworks/schematic#446]
**Describe the bug**
Running the tests on a fresh schematic install produces the following error. It appears to be using the `tests/data/test_config.yml` which doesn't have this key.

**To Reproduce**
1. Run `pytest `
2. See error

**Expected behavior**
The tests pass

**Screenshots**
<img width="734" alt="Screen Shot 2021-04-08 at 11 57 53 AM" src="https://user-images.githubusercontent.com/1216418/114058742-bc19f700-9861-11eb-9e43-83ad44e9b67e.png">

**Desktop (if applicable, please complete the following information):**

**Additional context**
Putting this here for tracking and so I don't forget about it.

**Comment by sujaypatil96** [comment]
To ensure that these tests successfully you will need to create a Personal Access Token on Synapse.

To do so, you can login to [synapse.org](https://www.synapse.org/). Under the `Settings` section from the dropdown in the top right corner you can find `Personal Access Tokens`. You can create a new personal access token and store it in a `.env` file in the repo root like:

```
> cat .env
SYNAPSE_ACCESS_TOKEN='Personal_Access_Token'
```
The `dotenv` module will take care of loading that value for you during testing.

Can you try this @hweej.

**Comment by hweej** [comment]
@sujaypatil96 , this seems to resolve most the issue. Almost all tests run & pass for me now off a fresh pull of Schematic. I suspect the other errors I'm getting are Synapse permission errors for my access token.

<img width="950" alt="Screen Shot 2021-04-22 at 3 50 39 PM" src="https://user-images.githubusercontent.com/1216418/115776849-98d36980-a382-11eb-8ba2-600bd0722dcd.png">
<img width="957" alt="Screen Shot 2021-04-22 at 3 50 52 PM" src="https://user-images.githubusercontent.com/1216418/115776870-9d981d80-a382-11eb-93c6-33e47d22f134.png">

**Comment by sujaypatil96** [comment]
@BrunoGrandePhD: Do you know what the best way to resolve this would be? I'm seeing: `synapseclient.core.exceptions.SynapseAuthenticationError: You are not logged in and do not have access to a requested resource.` and `synapseclient.core.exceptions.SynapseHTTPError: 403 Client Error: You lack CREATE access to the requested entity.` error messages as well when running the `test_store.py` tests locally.

**Comment by BrunoGrandePhD** [comment]
It's probably because he isn't a member of our schematic development [team](https://www.synapse.org/#!Team:3419888) on Synapse, which grants write-access to the test project. I issued an invite. 

The CONTRIBUTING docs should be updated to mention this requirement.

**Comment by sujaypatil96** [comment]
Hm..the tests don't run for me either, even though I'm already a member on the `schematic-dev` [team](https://www.synapse.org/#!Team:3419888) on Synapse.

Can you confirm if the test cases are running successfully for you @hweej?

**Comment by BrunoGrandePhD** [comment]
In that case, you need to use a personal access token generated on the `schematic-tester` account, which you can login using the credentials in LastPass. Both @sujaypatil96 and @hweej should have access to these credentials. 

![image](https://user-images.githubusercontent.com/740725/115917822-94af5680-a42b-11eb-8a62-f1a6cdd8ce6d.png)

**Comment by hweej** [comment]
Yes, I can confirm I'm still getting the `synapseclient.core.exceptions.SynapseAuthenticationError: You are not logged in and do not have access to a requested resource`. and `synapseclient.core.exceptions.SynapseHTTPError: 403 Client Error: You lack CREATE access to the requested entity.` With my own personal access token.

**Comment by sujaypatil96** [comment]
Thanks @BrunoGrandePhD. All the tests passed locally with a `schematic-tester` generated Personal Access Token (PAT).

----

So long-term, we'll have to get contributors to follow this protocol? Get users to generate PATs themselves through the `schematic-tester` account? I'm honestly surprised since I would have expected the same @BrunoGrandePhD, i.e., everybody added onto the `schematic-dev` team on Synapse (with Administrator level privileges) should be able to generate PATs that allow tests to run locally.

**Comment by BrunoGrandePhD** [comment]
It's because the `TestDatasets` folder has a local sharing setting that restricts edit-access to the `schematic-tester` account. I did this to make it harder for us to accidentally mess with the test datasets. I'm open to removing this local sharing setting if we think it's safe. 

![image](https://user-images.githubusercontent.com/740725/115929106-114a3100-a43c-11eb-988a-c0a7e0aaab28.png)

**Comment by sujaypatil96** [comment]
Right, I see, I didn't realize that `schematic-dev` had only "Can download" permission on the `TestDatasets`. Perhaps we can change the permission level for the `schematic-dev` team to "Can edit"? I can check if that level of privilege is enough to run the tests locally.

**Comment by BrunoGrandePhD** [comment]
Edit-access should be sufficient. The reason it's needed is for creating folder-bound file views. 

I've updated the `TestDatasets` folder to grant the `schematic-dev` team with edit-access (but not delete-access). We can revert this if things catches on 🔥.

**Comment by BrunoGrandePhD** [comment]
@hweej: Can you try again and report back whether the problem is resolved?

**Comment by hweej** [comment]
@BrunoGrandePhD yup! All tests pass using a personal access token created on the `schematic-tester` account!

**Comment by sujaypatil96** [comment]
@hweej: Can you test the same with a Personal Access Token created under your account? @BrunoGrandePhD has enabled "Can edit" permissions for all members of the `schematic-dev` team on Synapse.

**Comment by hweej** [comment]
Looks like I'm lacking `DELETE` access from my own Synapse account.
<img width="881" alt="Screen Shot 2021-04-23 at 6 09 20 PM" src="https://user-images.githubusercontent.com/1216418/115935100-7748af80-a460-11eb-8a58-a77cbef1d91c.png">

**Comment by BrunoGrandePhD** [comment]
Right, the code deletes the folder-bound file view after it's done with it. I've updated the permissions for the `schematic-dev` team accordingly. 

@hweej: Things should work now for you using your PAT. 

![image](https://user-images.githubusercontent.com/740725/115943659-115f2680-a466-11eb-96cc-3ed2d4062089.png)
