### ISSUE TITLE
json_schema_logs directory not found

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#448]
**Describe the bug**
On a new installation of the develop branch of schematic. When issuing the command

schematic model --config <path to config> submit --manifest_path <path to manifest> --dataset_id <dataset synapse ID> --validate_component <component>

user gets error

File "/Users/debruiji/miniconda3/envs/schematic-dev/lib/python3.9/site-packages/schematic/schemas/generator.py", line 646, in get_json_schema_requirements
    with open(json_schema_log_file, "w") as js_f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/json_schema_logs/json_schema_log.json'

**To Reproduce**
Try running the above CLI command.

**Expected behavior**
User worked around by manually creating the directory data/json_schema_logs/
They shouldn't need to do that; ideally the logging directory should be created for them as needed.

**Screenshots**
NA

**Desktop (if applicable, please complete the following information):**
mac os 

**Additional context**
NA

**Comment by sujaypatil96** [comment]
If you want to invoke the default behaviour, you can try removing the `log_location` key altogether from the `config.yml` file. The CLI will create a JSON Validation Schema (e.g., `example.Patient.schema.json`) for you in the same folder where you have your data model JSON-LD file.

If the `log_location` key is specified, then it does create a folder for you if one doesn't exist already (see behaviour [here](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/schemas/generator.py#L646)).

Could you check if you are pulling the latest code from the `develop` branch?

**Comment by sujaypatil96** [comment]
Commenting on this issue to see if it can be closed @milen-sage?
