### ISSUE TITLE
Escape retrieved annotations in google sheets

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#457]
**Is your feature request related to a problem? Please describe.**
More recent versions of schematic appear escape numbers, booleans, and formula-like statements when populating the valid values in a google sheet manifest (eg TRUE in schema becomes 'TRUE in google sheet, -/- becomes '-/- in google sheet). This is super helpful. However, when values that are numbers, booleans, or formula-like values are retrieved from Synapse, these values are not escaped. An example of this can be seen in column T in this manifest: https://docs.google.com/spreadsheets/d/1olSch1oz1arP-D_kBbsvF920GgftPMuMkIbo0e2c9ns/edit#gid=0, where the Synapse annotations of +/- are not escaped.  In the case of formula-like values, the resulting CSV exported from the  google sheet becomes `#ERROR`, meaning that the users need to actually fix these values even though they were initially correct. In the case of numeric/boolean values, the exported value is still correct, but the google sheets formatting suggests they are invalid values. 

**Describe the solution you'd like**
It would be helpful if annotations retrieved from synapse were escaped in the same manner that valid values are so that users who are modifying previous annotations don't feel the need to re-assign these already-valid-values.

**How important is this feature?** Select from the options below:
• low-Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks
Relevant now, but more of a convenience/quality of life improvement than a blocker. 

**Additional context**

**Comment by milen-sage** [comment]
@BrunoGrandePhD could you take a look into this? looks like it dovetails w/ your earlier changes and might be an easy fix.

**Comment by BrunoGrandePhD** [comment]
I haven't looked at the code yet, but it seems like the solution is to leverage the same escaping logic that's being used to generate the valid values sheet (_i.e._ the hidden `Sheet 2`) when filling the template with annotations. 

I'll dedicate two hours on Thursday to take a look at this. Depending on how readily the escaping logic can be shared, this could be fixed within two hours or might require additional time. I'll post an update after I look at the code on Thursday.
