### ISSUE TITLE
Schematic adds "Filename" value as an annotation

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#476]
**Describe the bug**
Schematic pushes "Filename" value in a manifest as an annotation. This is an issue because schematic will then throw an error when you regenerate a manifest that contains files that have a `Filename` annotation and `use_annotations = T`. The error is: `Warning: Error in py_call_impl: ValueError: cannot insert Filename, already exists` This prevents a user from revisiting/reannotating data using schematic. 

**To Reproduce**
1. Generate a manifest, fill in.
2. Apply manifest to files. 
3. Try and regenerate a new manifest containing the same files with use_annotations = T.

**Expected behavior**
I expect Filename to not be set as an annotation.

**Comment by allaway** [comment]
Note: when following this approach, you also get `etag` as an annotation, which I don't think causes any issues (that I've discovered yet) but it can be confusing because a file then has two etags in a view: the true system `eTag` and the (possibly outdated) annotation `etag`.

**Comment by allaway** [comment]
I just tried the following: remove the Filename annotation manually on synapse and then re-generate manifest. It now works, suggesting that it is this annotation value that's resulting in this error.

**Comment by BrunoGrandePhD** [comment]
@allaway: In the meantime, you might want to delete the `Filename` and `eTag` annotations on all affected files/folders, which will unblock you right away. Once you deploy this eventual fix, you could run that code once more and then you should be good to go.

**Comment by allaway** [comment]
Thanks! yep, I used that approach this morning and it worked as a temporary fix!
