### ISSUE TITLE
schematic fails due to UnicodeEncodeError on Windows

### ISSUE THREAD

**Issue by lopierra** [Sage-Bionetworks/schematic#481]
**Describe the bug**
Running `schematic schema convert htan.model.csv` returns error `UnicodeEncodeError: 'charmap' codec can't encode character '\u039c' in position 5: character maps to <undefined>`

`\u039c` is the Greek character "mu" (as in "um" or "micrometres"). This happens on my Windows machine but not with @milen-sage's Mac. 

It happened with both a CSV that I converted from a Google Sheet, and with a CSV taken directly from the HTAN GitHub repo.

**To Reproduce**
1. Either download the [HTAN schema v19](https://docs.google.com/spreadsheets/d/1tBK7lBcWU3FvdB2awtHLWbRuK6od3k4h60grDzydX8k/edit?ts=60888476#gid=0) Google Sheet as a csv, or download the current `HTAN.model.csv` from https://github.com/ncihtan/data-models/tree/main-add-files
2. Run `schematic schema convert` on either of the above files. Schematic fails with the above error after running for about 5 min. A partial model (`htan.model.jsonld`) is created.

**Expected behavior**
Schematic should generate the complete jsonld model with no errors on Mac or Windows.

**Error Log**
Error log is attached for running with ncihtan version of model.
[log.txt](https://github.com/Sage-Bionetworks/schematic/files/6588307/log.txt)

**Desktop (if applicable, please complete the following information):**
 - OS: Windows 10

**Comment by milen-sage** [comment]
very likely related to #559

**Comment by ychae** [comment]
Change how it's encoded within schematic rather than in the OS
Make sure fix doesn't break data models 
Test that fix doesn't break on Macs
