### ISSUE TITLE
Add Windows-specific instructions to documentation

### ISSUE THREAD

**Issue by lopierra** [Sage-Bionetworks/schematic#482]
**Is your feature request related to a problem? Please describe.**
The instructions to activate a Python virtual environment may be slightly different for Windows than for Mac/Linux

**Describe the solution you'd like**
The Mac/Linux command, as currently written in the documentation, is  `source .venv/bin/activate`
On Windows (at least on my machine - Windows 10), I did not have a `bin` folder - instead I used `source .venv/Scripts/activate`

I also found that I need to use Cygwin or other Unix emulator, or use the Git Bash window. The commands did not work in the Windows Command Prompt app. (That might be pretty basic, but as a beginner it took me a while to figure this out.)

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Whenever we have new Windows users

**Comment by HumanG33k** [comment]
You should instead use ubuntu not so hard to install and use. https://ubuntu.com/tutorials/install-ubuntu-desktop#1-overview

**Comment by sujaypatil96** [comment]
> The commands did not work in the Windows Command Prompt app.

@lopierra: I wanted to ask, what command specifically did not work in cmd? Once the virtual environment has been activated in the way you mention, and the package has been installed, the schematic commands for Windows should be the same as the ones we write for bash.

**Comment by lopierra** [comment]
@sujaypatil96: adding the `.\.venv\Scripts\activate    # on Windows` line is helpful, thanks!

More generally, any of the Unix commands will not work in Windows `cmd.exe`. You have to have a specific bash program like git bash, [Cygwin](https://www.cygwin.com/), or [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10). I think you could just mention it in "2. Installation Requirements and Pre-requisites".

**Comment by sujaypatil96** [comment]
@lopierra: Perfect, thank you for the comment. Does this [commit](https://github.com/Sage-Bionetworks/schematic/pull/492/commits/13683eb3176094cb8e1cc493cf90ee67645e6131) appropriately address what you requested?
