### ISSUE TITLE
`schematic schema convert` option `--output_jsonld` fails when output file doesn't already exist

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#505]
**Describe the bug**
`schematic schema convert` option `--output_jsonld` only works as expected when jsonld file already exists. 

**To Reproduce**
Convert a schema csv without --output_jsonld flag set. 
Rename the jsonld to something else, eg test.jsonld
Convert a schema csv with --output_jsonld set to test.jsonld (pointing to the path where the file was created in the last step) 
Conversion should work fine ✅ 
Delete test.jsonld
Re-run previous command
Conversion will not work ❌ 

**Expected behavior**

**Screenshots**
prior to this command, NFTI.jsonld already exists. 
```
(data_curator_env) ➜  schematic-upstream git:(develop) ✗ schematic schema convert "/Users/rallaway/Downloads/NFTI Schema - Main Schema.csv" -o '/Users/rallaway/Downloads/NFTI.jsonld'
Starting schematic...
Done adding requirements and value ranges to attributes
The Data Model was created and saved to '/Users/rallaway/Downloads/NFTI.jsonld' location.
```
deleted NFTI.jsonld and rerun command
```
(data_curator_env) ➜  schematic-upstream git:(develop) ✗ schematic schema convert "/Users/rallaway/Downloads/NFTI Schema - Main Schema.csv" -o '/Users/rallaway/Downloads/NFTI.jsonld'
Starting schematic...
Usage: schematic schema convert <options> <DATA_MODEL_CSV>
Try 'schematic schema convert --help' for help.

Error: Invalid value for '--output_jsonld' / '-o': Path '/Users/rallaway/Downloads/NFTI.jsonld' does not exist.
```

**Desktop (if applicable, please complete the following information):**
 - v1.0.0

**Additional context**

**Comment by linglp** [comment]
this issue should now be solved with this [PR](https://github.com/Sage-Bionetworks/schematic/pull/601).
