### ISSUE TITLE
Set CLI `schematic manifest get` -s option to generate a google sheet url

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#506]
**Describe the bug**
When this boolean flag is not called, the behavior is supposed to be: "If not it will produce a pandas dataframe for the same."
This is the default behavior for schematic manifest get. 

When I run this command without the `-s` flag, i get no output at the command line: 

```
(data_curator_env) ➜  schematic-upstream git:(develop) ✗ schematic manifest --config config.yml get -p "/Users/rallaway/Downloads/NFTI.jsonld" -oa --data_type Component
Starting schematic...
The (manifest > title) argument with value 'NF' is being read from the config file.
The '--title' argument is being taken from configuration file (manifest > title), i.e., 'NF'.
The (model > input > validation_schema) argument with value 'data/validation_schemas/example_validation_schema.json' is being read from the config file.
The '--json_schema' argument is being taken from configuration file (model > input > validation_schema), i.e., 'data/validation_schemas/example_validation_schema.json'.
Permission Id: anyoneWithLink
(data_curator_env) ➜  schematic-upstream git:(develop) ✗
```

**To Reproduce**
Run schematic manifest get, without calling the -s flag. 

**Expected behavior**
I would have expected the default behavior to produce a google link, or, alternatively, to spit out a manifest to stdout, but I'm not sure that would actually be of value to the users. 

**Screenshots**

**Desktop (if applicable, please complete the following information):**
 v1.0.0

**Additional context**

**Comment by milen-sage** [comment]
Yes, this makes sense! We can simplify the CLI for some of the most common operations and have more sensible defaults, starting with this one.

**Comment by linglp** [comment]
@milen-sage I know this is an old issue, but here's the current behavior: 
`schematic manifest --config config.yml get` could generate a local manifest in CSV format, and it is the same for `schematic manifest --config config.yml get -p "tests/data/example.model.jsonld" -oa --data_type Biospecimen`

I am not sure if you would still like the default behavior to be generating a google sheet url

**Comment by milen-sage** [comment]
@linglp ok, this is good as a generic default behavior for getting a CSV manifest. What we could change though is the default behavior for generating a google sheet. Currently, I think, you'd need to have 

`schematic manifest --config config.yml get -p "tests/data/example.model.jsonld" -oa -s --data_type Biospecimen`

could we have 

`schematic manifest --config config.yml get -p "tests/data/example.model.jsonld" -s --data_type Biospecimen` still generate a google sheet url. Note it doesn't list the -oa flag. We may want to be a bit careful on the type of google authentication (oauth vs service account is done by default if we don't provide the oa flag).

I changed the title of the issue.

**Comment by milen-sage** [comment]
This will be addressed as a revamp of CLI utilities, preserving backward compatibility when possible. I'll add a milestone and timeline.
