### ISSUE TITLE
Synapse Google cloud interoperability

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#52]
Synapse file-handles functionality for files hosted on Google Cloud buckets. The feature is developed by the Synapse team, and is now in alpha. Let's test it!

#roadmap

**Comment by ychae** [comment]
Users can select AWS or GC storage locations: https://ncihtan.github.io/HTAN-Data-Ingress-Docs/choose-your-cloud-storage-platform.html
