### ISSUE TITLE
RDB Export Table Joins

### ISSUE THREAD

**Issue by mialy-defelice** [Sage-Bionetworks/schematic#536]
**Is your feature request related to a problem? Please describe.**
Need a way to export sql table joins so they can be imported into Synapse.

**Describe the solution you'd like**
Take in a file describing all joins that need to be performed across the RDB and filenames for these joins. Export as csv.

**How important is this feature?** Select from the options below:

• Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by mialy-defelice** [comment]
This now works on the working `develop-rdb-export-joins` branch, which will soon be merged with the `develop-rdb` branch.

**Comment by mialy-defelice** [comment]
> Not sure if this deserves it's own issue, but list-columns in the joined tables should be exported as JSON arrays so that Synapse interprets them as list-column values (though `schematic` already has support for this with synapse annotations so maybe it would already work as-is for RDB export too).

I addressed this issue at the same time :)

**Comment by allaway** [comment]
🎉
