### ISSUE TITLE
NF RDB: Convert camel case column names to Display Names

### ISSUE THREAD

**Issue by mialy-defelice** [Sage-Bionetworks/schematic#543]
**Is your feature request related to a problem? Please describe.**
In the NF RDB on Synapse the table column names are rendered in camel case, to match the data frame columns made for the RDB. However when they are converted to display names in the portal they are being rendered improperly.

**Describe the solution you'd like**
Make a dictionary mapping camel case names to display names, so column names do not have any issue rendering. 
Convert all column names to display names on synapse.

**How important is this feature?** Select from the options below:
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months
Needs to be addressed before the public release.

**Additional context*
<img width="420" alt="Screen Shot 2021-11-08 at 1 53 54 PM" src="https://user-images.githubusercontent.com/85905780/142693612-4683dd4e-ef54-4d6b-bff9-d165dfc29a56.png">
*

**Comment by mialy-defelice** [comment]
@ychae I changed the problematic camelcase's so that the NF portal looks nice for now. But it might be good to put this on our roadmap for next quarter. I don't think its urgent to make this update, but wanted to pull you into the loop.

**Comment by milen-sage** [comment]
@andrewelamb let's keep track of the changes we discussed here. A screenshot of the [whiteboard](https://us02web.zoom.us/wb/doc/iCi_ZpkPSuK4ZcjZiR4pKQ/p/172294691880960) in case useful (not sure how long Zoom keeps whiteboards active...):

<img width="1637" alt="Screen Shot 2022-06-27 at 11 31 14 AM" src="https://user-images.githubusercontent.com/41303818/176012236-28f26b73-9594-4ec2-8dc9-6fd612878dd1.png">










here

**Comment by andrewelamb** [comment]
@milen-sage @mialy-defelice A few more questions:

- Am I adding the strict argument to just `get_property_label_from_display_name`, or `get_class_label_from_display_name`?
- Is it OK to add a test [here?](https://github.com/Sage-Bionetworks/schematic/blob/develop/tests/test_schemas.py)
- I'm a still mixed up on display name vs the output from these methods. Could you quickly go over where these. For example, `get_property_label_from_display_name("how to aquire") -> "howtoAquire` when the result should be `"howToAquire"` correct?
- Does this line `display_name = display_name.translate({ord(c): None for c in string.whitespace})` strip out unicode whitespace?

**Comment by andrewelamb** [comment]
I'm still a little confused on what the display name is vs the output. The column name in the manifest is "howToAquire". Is the display name coming from the schema?

I've started writing some unit tests to capture the wrong output:
```
        se_obj = helpers.get_schema_explorer("example.model.jsonld")
        assert(se_obj.get_property_label_from_display_name("howToAcquire") == "howToAcquire")
        assert(se_obj.get_property_label_from_display_name("how_to_acquire") == "howToAcquire")
        assert(se_obj.get_property_label_from_display_name("howtoAcquire") == "howtoAcquire")
>       assert(se_obj.get_property_label_from_display_name("how to acquire") == "howToAcquire")
E       AssertionError: assert 'howtoacquire' == 'howToAcquire'
E         - howToAcquire
E         ?    ^ ^
E         + howtoacquire
E         ?   
```

**Comment by mialy-defelice** [comment]
> @milen-sage @mialy-defelice I have soem git related questions:
> 
> Should this be one PR, or should the changes to explorer.py be separate from the changes to rdb.py? What branch(or branches if the answer to the previous question is separate PR's) should I be working off of?

We haven't pulled from Develop in a while but it shouldn't really affect the RDB codebase. So you could Pull Develop and Merge with RDB then work on this issue from a branch off develop. Thoughts @milen-sage ?

**Comment by mialy-defelice** [comment]
> @milen-sage @mialy-defelice A few more questions:
> 
> * Am I adding the strict argument to just `get_property_label_from_display_name`, or `get_class_label_from_display_name`?
Both I believe.
> * Is it OK to add a test [here?](https://github.com/Sage-Bionetworks/schematic/blob/develop/tests/test_schemas.py)
That seems fine.

**Comment by milen-sage** [comment]
@andrewelamb I second @mialy-defelice's proposal on the code that goes in the explorer.py:

> So you could Pull Develop and Merge with RDB then work on this issue from a branch off develop.

Just to clarify by "Merge with RDB", @mialy-defelice you mean merge into [this branch](https://github.com/Sage-Bionetworks/schematic/tree/develop-rdb-export-joins) right?

**Comment by mialy-defelice** [comment]
> Just to clarify by "Merge with RDB", @mialy-defelice you mean merge into [this branch](https://github.com/Sage-Bionetworks/schematic/tree/develop-rdb-export-joins) right?

Yep!
