### ISSUE TITLE
schematic init doesn't download schematic_service_account_creds.json

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/schematic#544]
Section 3.4 of the walkthrough isn't clear on how to obtain schematic_service_account_creds.json

`schematic init --config ~/path/to/config.yml --auth [token|serivce_account]`

**Comment by ychae** [comment]
related to #555

**Comment by linglp** [comment]
@ychae and @afwillia : to obtain schematic_service_account_creds.json, the command should be: 
`schematic init --config ~/path/to/config.yml --auth serivce_account`
I have added this to documentation.
