### ISSUE TITLE
Enable multiple manifests per folder

### ISSUE THREAD

**Issue by adamjtaylor** [Sage-Bionetworks/schematic#551]
**Is your feature request related to a problem? Please describe.**
Some HTAN contributors have organised their data with multiple types/components per folder. eg. Mixed ImagingLevel2 and ImagingLevel1 data in the same folder.

**Describe the solution you'd like**
The ability for a manifests for different components/types to be generated/held in the same folder.

**How important is this feature?** Select from the options below:
• ~~Low - it's an enhancement but not crucial for work~~
• **Medium - can do work without it; but it's important (e.g. to save time or for convenience)**
• ~~Important - it's a blocker and can't do work without it~~

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks
• ~~Mid-term - 2-4 months~~
• ~~Long-term - 6 months - 1 year~~

**Additional context**
None. Have already discussed with @milen-sage

**Comment by ychae** [comment]
@adamjtaylor #629 and #610 address this ticket. We're wrapping up some testing and should have this ready the week after Home Week.
