### ISSUE TITLE
Update and consolidate schematic installation documentation

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/schematic#555]
Update developer installation documentation for schematic

**Comment by ychae** [comment]
Issue 1. On Macs, need to set the path to point to python 3.8 otherwise poetry and other packages don't work

**Comment by ychae** [comment]
Tracking all my notes here:

# Doc to track errors and missing steps in the schematic README.md and CONTRIBUTING.md guide

## README
In "Installation and Pre-requisites":
`Note: You need to be a registered and certified user on  [`synapse.org`](https://www.synapse.org/), and also have the right permissions to download the Google credentials files from Synapse.`
1. How do I know what files that I need permissions for?
- [ ] Ask Milen about PR around google credentials
    
## Changes
1. Change `python` to `python3`:
`python3 -m venv .venv`

2. Install numpy separately, installing with `schematicpy` results in the following error:
`ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly`
To resolve, run: (this can likely be resolved to a single pip install line)
```
pip install --upgrade pip setuptools wheel
pip install numpy
```
3. Then run:
`python3 -m pip install schematicpy`
    
4. Next, go to: [CONTRIBUTING.MD](https://github.com/Sage-Bionetworks/schematic/blob/develop/CONTRIBUTION.md)
    
## CONTRIBUTING.md
## Changes

1. Fails at `poetry build` with error `zsh: command not found: poetry`
	To resolve: 
	`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -`
	- Unsure about using  `get-poetry.py` since the [docs](https://python-poetry.org/docs/#installation) seem to recommend using `install-poetry.py` and `get-poetry.py` will be deprecated.

2. Fails at: `pip install dist/schematicpy-x.y.z-py3-none-any.whl` with error `ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/Users/ychae/Documents/sandbox/schematic/dist/schematicpy-x.y.z-py3-none-any.whl'`
To resolve: 
My `dist` folder has the file `schematicpy-1.0.0-py3-none-any.whl` so I ran `pip install schematicpy-1.0.0-py3-none-any.whl` 
	- There is this comment in the doc immediately under this command that says "_Note_: Use the appropriate version number (based on the version of the codebase you are pulling) while installing the wheel file above." **How do I know if I have the appropriate version number?**

3. The `pip install schematicpy-1.0.0-py3-none-any.whl` throws the error: `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
schematicpy 1.0.0 requires synapseclient<2.4,>=2.3, but you have synapseclient 2.5.1 which is incompatible.`

**Comment by ychae** [comment]
@milen-sage @mialy-defelice Does the `schematicpy-1.0.0-py3-none-any.whl` file try to install the latest version of the synapseclient? I uninstalled synapseclient version 2.5.1 and manually installed synapseclient version 2.3.0 but every time I run `pip install schematicpy-1.0.0-py3-none-any.whl` it errors out by complaining: `schematicpy 1.0.0 requires synapseclient<2.4,>=2.3, but you have synapseclient 2.5.1 which is incompatible.` And when I check my synapseclient version after running the `.whl` file it says I now have synapseclient version 2.5.1

Please advise on how to proceed.

**Comment by milen-sage** [comment]
@ychae you are using a virtual environment, right?  Might be worth trying starting a clean environment and install again; schematic should have a fixed  version for the synapseclient it uses and install that as a dependency autoamtically.

Meanwhile, we can take a look at poetry's lock file.

**Comment by milen-sage** [comment]
Thanks @ychae! We should check what version is in schematic's poetry lock. We fixed the synapseclient version to ensure backward compatibility with schematic, but it sounds like you are getting the latest version (e.g. 2.5.1) nevertheless. Just to confirm, are you running these commands in the same virtual environment? (Not an urgent question.)

**Comment by ychae** [comment]
@milen-sage Yep, all of this is being run in the same venv. I can re-try using a fresh venv and schematic install.

**Comment by milen-sage** [comment]
@ychae we should probably add this to backlog?

**Comment by elv-sb** [comment]
.synapseConfig file is not automatically generated. You need to download credentials separately or create it via https://python-docs.synapse.org/build/html/index.html#connecting-to-synapse

**Comment by ychae** [comment]
Acceptance criteria:
1. Have an E2E doc of how to install dev schematic in one location
