### ISSUE TITLE
Register JSONSchema on synapse after converting from data model

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/schematic#556]
JSONSchemas need to be registered on Synapse. It's a simple API call and making this part of the Data Model to JSONSchema conversion process would be helpful.

**Comment by milen-sage** [comment]
@avanlinden and @danlu1 just fyi we are working on this feature and are tracking work in this issue. 

This work is along the lines of the data model management framework outlined in the slide [here](https://docs.google.com/presentation/d/1yMAF2Sagw4-5vleFH93NFKwxcIuldrmNiH-smUC46qI/edit?disco=AAAAUgK1gDA).

@afwillia is focusing first on exploring how we can refactor a bit the backends of the dccvalidator and dccmonitor to work with JSONSchema for validation consistently. That way the apps will have a single source of truth based on the schema generated according to a data model.
