### ISSUE TITLE
Schema Viz: Allow visualization of different types of relationships.

### ISSUE THREAD

**Issue by mialy-defelice** [Sage-Bionetworks/schematic#566]
Update gather_dependencies to take in `requiresDependency` as a data type for the Observable visualization tool.

**Comment by ychae** [comment]
Acceptance criteria:
Making sure that the graph can render and show the highlights

**Comment by mialy-defelice** [comment]
@ychae 

I made the graph (its a bit wonky) with the `requiresDependency` relationship attributes. It is so large it is not helpful in this form. I chatted with @milen-sage and we decided to show the `requestDependency` relationship _per_ component, as the component is chosen from the dropdown.



[requires_dependency_plot.pdf](https://github.com/Sage-Bionetworks/schematic/files/8017775/untitled-1-1.pdf)

**Comment by mialy-defelice** [comment]
A current set of issues that should be addressed (schema:HTAN Component Requires Dependency) in the main schema viz.

- [ ] `Biospecimen`:  level assignment is a bit messed up bc `Biospecimen` is connected to both `Biospecimen Type` and `Site of Resection or Biopsy`. This connection pulls `Biospecimen` down a level and distrubs all the connections that should be one level below but are now in the same level as it. I am not sure if `Biospecimen` can be pulled up a level without breaking. Will try that first...then try to develop a general solution. 
- [ ] `BulkRNA-seqLevel1`: level colors are all the same for some reason.
- [ ] `ImagingLevel2` looks like there might be some issue with how units were added. Are both dependent on `ImagingLevel2` and related attributes (for example: . Maybe should just be dependent on the other attributes, so they will render properly in the figure? @milen-sage thoughts?
- [ ] `ScATAC-seqLevel1`: some attribute names are extremely long, for now I have just been ignoring text overlapping to links, but this is a bit extreme. Need to precompute all text widths then set width between levels based on max text width. This might be better as its own issue.
