### ISSUE TITLE
schematic manifest get -o does not return a csv

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/schematic#569]
**Describe the bug**
Passing the --output_csv option to schematic manifest get does not return a csv

**To Reproduce**
Set up schematic according to the [README ](https://github.com/Sage-Bionetworks/schematic#manifest)
schematic manifest --config config.yml get --output_csv test.csv

**Expected behavior**
A file to be written with the name of the --output_csv argument.

**Comment by ychae** [comment]
AC: return a csv when using the output csv option
