### ISSUE TITLE
Highlight conditional dependencies in google sheets

### ISSUE THREAD

**Issue by mialy-defelice** [Sage-Bionetworks/schematic#571]
**Describe the bug**
Conditional dependencies are no longer being highlighted in google sheets presumably after the `get_manifest` refactor.

**Expected behavior**
Conditional dependencies should be conditionally highlighted in google sheets.

**Comment by mialy-defelice** [comment]
Conditionally optional cells need to be yellow.
For example (hypothetically):
Vital status = dead then the conditionally required are cause of death, year of death, etc, but primary cause of death is required, but secondary cause of death is conditionally optional.

Confusingly it looks like the necessary information should be there to highlight fields properly, but it is not actually showing up in the manifest.

Check that this is not to issue with JSON in follow on issue. Check if we can see conditional formatting for Biospecimen conditional dependencies.

**Comment by milen-sage** [comment]
After updating my local develop branch, the issues I see with conditional dependencies is:
- only one of conditionally *required* dependencies is highlighted in blue; e.g. in Demographics [manifest](https://docs.google.com/spreadsheets/d/1zpP92NXOdTIev0Aix2lb5RQKETvndqMvpPj4xJGRP0I/edit#gid=0), select Vital Status = Dead and you should be able to replicate
- conditionally optional dependencies are not highlighted; e.g. same manifest as above to replicate

Confirmed that the data model jsonld  and the derived JSONSchema files contain accurate indication of which attributes are conditionally required and optional. The highlight issue is likely in the manifest generator as we had suspected.

**Comment by mialy-defelice** [comment]
[Biospecimen manifest](https://docs.google.com/spreadsheets/d/1l0AYSdm9ehYhFNbuQi3gVtUQLchoALpCneeKkOwqurY/edit#gid=0) before the fix (BiospecimenType) is Analyte Biospecimen. Only a single conditional dependency (Ischemic Temperature) is highlighted. This can be randomly chosen among the the conditional dependencies.

Going back to a previous commit before the refactor I can see what the expected manifest is [here](https://docs.google.com/spreadsheets/d/1drgqoF5YPzV_TkVbaUQLbUd-q6s33wK7_dWJOmdhq1I/edit#gid=0).

I found the issue had to do with how the conditional dependencies were being stored is now fixed (with the upcoming PR) to match the previous version. See [here](https://docs.google.com/spreadsheets/d/1YnEiEpa611i33nwk_WWFMN1eym_GxtaArUrOcptWEzQ/edit#gid=0).
