### ISSUE TITLE
Manifests and JSON do not contain some conditional dependencies.

### ISSUE THREAD

**Issue by mialy-defelice** [Sage-Bionetworks/schematic#576]
**Describe the bug**
Discovered by happenstance that the JSON schemas and Manifests did not include all the conditional decencies. 

**To Reproduce**
For the HTAN schema, create a manifest for `Diagnosis`.
Look for `VitalStatus` in the manifest and generated JSON schema.
It will not be present in either one. 

The schema visualization tool also shows that it is not present.

**Expected behavior**
All dependencies and conditional dependencies should be present in both the JSON and manifest for the connected component.

This is high priority.

**Comment by milen-sage** [comment]
I double checked and the manifests and JSONSchema are OK - false alarm. `Vital Status` is part of Demographics. `Family Member Vital Status Indicator` is part of the components we were generating manifests for. We are good!
