### ISSUE TITLE
Update schematic's poetry lock numpy version 

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#578]
Change from 1.21.1 to 1.19.0

@rrchai let us know if 1.21.1 works or if it's still a conflict; if it's in conflict with other requirements we'll update poetry lock on schematic.

**Comment by rrchai** [comment]
change all numpy version==1.21.1 in `poetry.lock` still not working

**Comment by rrchai** [comment]
```
Collecting numpy>=1.18.5; platform_machine != "aarch64" and platform_machine != "arm64" and python_version < "3.10"
  Using cached numpy-1.22.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
```
