### ISSUE TITLE
Research migrating clinical and biospecimen entities to Tables (use table joins)

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/schematic#589]
**Is your feature request related to a problem? Please describe.**
The Sage Platform team has given us as much of an increase as possible in File View limits (35,000). Once we hit this limit, everything powered by the main file view will cease to work (ie DCA and portal in HTAN). 

**Describe the solution you'd like**
Migrate the clinical and biospecimen entities to a Synapse Table to use the new [Table joins feature](https://sagebionetworks.jira.com/wiki/spaces/PLFM/pages/2514321554/Synapse+Joins) to join these with their respective file views. 

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience) **However this will become a blocker in the next month when the remaining data is released in HTAN (see Additional Context below)**

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**
HTAN has a "release 2.1" happening a month from now (approximately March 31) and the addition of these data will tip the new file view limit that the Platform team gave us. It's been made very clear that this is the tip top of the limit increase and we will need to adopt the table joins method in order to ensure that the data ingress tools and portals continue to function.

For this ticket specifically, it is to scope out and research what would be needed to accomplish the solution described in the `Describe the solution you'd like` section. This scoping can then be applied to the implementation which would be the work of the next sprint. 

TO DO:
- [ ] How do we know when scoping is done?

**Comment by ychae** [comment]
@mialy-defelice and @milen-sage will review the acceptance criteria and have further conversation

**Comment by mialy-defelice** [comment]
@milen-sage @ychae 

**Current status:**

- Wrote a new function based on other functions in `store/synapse.py` to pull all the manifests for a particular project and reupload them as tables. This is currently called by a simple script.
- [ Created a Materialized View ](https://www.synapse.org/#!Synapse:syn27729630/tables/)(using Synapse UI) Joining the Vanderbilt[ Biospecimen Manifest Table](https://www.synapse.org/#!Synapse:syn25010908/tables/) and [ScRNA-seq-Level1 Fileview](https://www.synapse.org/#!Synapse:syn27728255/tables/) with the following join 
    - `SELECT * FROM syn25010908 M JOIN syn27728255 F ON (M.HTANBiospecimenID = F.HTANParentBiospecimenID)`

**Current Issues:**

- New version of Python Synapse Client is incompatible with Schematic
- Unable to login to new Python Synapse Client for unknown reasons
    - Note I am in a new venv and following Tom's instructions [here](https://github.com/Sage-Bionetworks/synapsePythonClient/pull/903).
    - `syn_config_path = "/Users/mialydefelice/Documents/schematic_b/schematic_package_docs/.synapseConfig"
syn = synapseclient.Synapse(configPath=syn_config_path)
syn.setEndpoints(**synapseclient.client.STAGING_ENDPOINTS)
syn = synapseclient.login(silent=True)`
    - Error is `*** synapseclient.core.exceptions.SynapseNoCredentialsError: No credentials provided.`

**Comment by mialy-defelice** [comment]
@milen-sage @ychae 

Figured out the issue with the Client login.

Now having issue with sql join error. Using the same join that worked with the SynapseUI so not sure what's happening. Reached out to Tom for assistance.

Other than this issue, I would say this scoping is complete.
