### ISSUE TITLE
Test and enhance schematic REST API submission end point

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#590]
Currently the REST API service uses the credentials provided using schematic's installation. However, different service users may have different credentials. Add a parameters to the submission endpoint that allows authentication information to be passed to it.

**Comment by milen-sage** [comment]
@linglp you can chat with @afwillia on that. He may have some useful examples for how to pass authentication information.

**Comment by afwillia** [comment]
@linglp here is a simple example of passing authentication info in a synapse REST API request

`### Get user profile info
# For information on authenticating synapse REST API queries
# https://docs.synapse.org/rest/#org.sagebionetworks.auth.controller.AuthenticationController
# Authentication to Synapse services requires an access token passed in the
# HTTP Authorization header, as per the HTTP bearer authorization standard. 
# https://datatracker.ietf.org/doc/html/rfc6750#section-2.1
#
# https://docs.synapse.org/rest/#org.sagebionetworks.repo.web.controller.UserProfileController
# PAT is the synapse personal access token OR the browser cookie from a logged-in session.
uri <- "https://repo-prod.prod.sagebase.org/repo/v1/userProfile"
req <- GET(uri, add_headers(Authorization=paste0("Bearer ", pat)))
content(req)`

**Comment by afwillia** [comment]
@linglp Functions that data curator uses from [schematic store](https://github.com/Sage-Bionetworks/schematic/blob/f16a10b01c81a07afb6a1e5f3f3f230ad4b014a6/schematic/store/synapse.py#L40)

- [getStorageProjects](https://github.com/Sage-Bionetworks/data_curator/blob/ce9b754f02eb8ec38e81d5e166d2f36721774e15/server.R#L83)
- [getStorageDatasetsInProject](https://github.com/Sage-Bionetworks/data_curator/blob/ce9b754f02eb8ec38e81d5e166d2f36721774e15/server.R#L158)
- [getFilesInStorageDataset](https://github.com/Sage-Bionetworks/data_curator/blob/ce9b754f02eb8ec38e81d5e166d2f36721774e15/server.R#L194)
- [associateMetadataWithFiles](https://github.com/Sage-Bionetworks/data_curator/blob/ce9b754f02eb8ec38e81d5e166d2f36721774e15/server.R#L400)

**Comment by ychae** [comment]
Acceptance Criteria: submission of manifest work through the REST API service
Passing authentication: input field - get the token string and pass that through

**Comment by afwillia** [comment]
The data curator dashboard [dashboardFuns.R](https://github.com/Sage-Bionetworks/data_curator/blob/ee82b0cc06bc6b013ba6ef147de10f465ffb6e7c/functions/dashboardFuns.R) also uses some schematic and synapseclient functionality.

**schematic**
metadata_model$validateModelManifest(manifest_path, manifest_component)
metadata_model$get_component_requirements(datatype, as_graph = TRUE)

**synapseclient** (just as a note)
synStoreObj$storageFileviewTable
syn$get(manifest_id)
syn$getUserProfile(manifest["properties"]["modifiedBy"])["userName"]

**Comment by afwillia** [comment]
I did not add tableQuery or get because the app isn't actually using them.
