### ISSUE TITLE
Scope the new table and fileview joins feature in Synapse

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#591]
schematic has features in development to create and interact with RDB. Synapse has exposed a RDB-like service that joins tables to tables, and tables to fileviews. 

Scope whether or what it'd take for schematic to instantiate a RDB-like set of tables and fileviews and perform joins between them.  This may be useful in the context of the NF GFF RDB work in the future.

**Comment by mialy-defelice** [comment]
@milen-sage what is your current vision when you say "instantiate a RDB-like set of tables and fileviews"?

My initial reading of this made me think, we could just use our RDB backend for schematic (setting primary and foreign keys and all the relationships) then just import the tables into schematic and use the schematic joins feature? Is this what you meant? Or did you mean something perhaps more complicated like trying to set up everything using Synapse alone?

**Comment by milen-sage** [comment]
@mialy-defelice 

>  setting primary and foreign keys and all the relationships

Yes, on using schematic's RDB functionality, for example, to determine which tables need to be updated in what order, on Synapse.

>  just import the tables into schematic and use the schematic joins feature

I think this may be something we'd need to discuss in more detail. Ideally, we'd want to "compose" the joins queries based on schematic's RDB backend query configuration, but then be able to execute these join queries on tables in Synapse. We wouldn't want to execute the joins in a mysql db outside of Synapse; that way table records don't need to leave Synapse. 

In general, we'd like to support Synapse as another RDB type. Currently we have mysql, we could add synapse_rdb.

**Comment by mialy-defelice** [comment]
@milen-sage 
> but then be able to execute these join queries on tables in Synapse

Okay yes, I think this is totally doable using a very similar format to what I currently have, but we could write the joins in the Synapse query language. We already upload all the base tables to Synapse for NF. Instead of creating a MySql database first then uploading the MySql tables to Synapse, I could upload the tables directly. Using the python client I could compose the materialized views within schematic and then export those to Synapse, and then they would update each time the base tables were updated.

Scoping note: The Synapse join functions are limited compared to MySql. For our purposes we can think of them only allowing JOIN ON. Time wise I anticipate writing the joins will be the most time consuming part of this process, and might require composing intermediate materialized views for some of the more complicated joins.

**Comment by milen-sage** [comment]
If we see that constructing Synapse joins requires much more complicated queries and intermediate views, we can raise that as a use case with Kevin.

**Comment by mialy-defelice** [comment]
![IMG_8944](https://user-images.githubusercontent.com/85905780/157309602-3812b588-7665-4ba5-b886-37688fc0e8a2.jpg)

Keep using `create_load_sql_db_nf.py` it will functionally create the RDB in the backend and allow the table data to be updated using sql logic. Note this will technically retain a sql component.

The area of the code that needs to be adjusted is `sql_query_nf.py` (probably will need to be renamed).

**Steps/Issues:**

- [ ] Add a new class `synapse_query` that is analogous to `sql_query`.
- [ ] Can use `sql_query` to pull all base RDB tables and load them to synapse. This would ensure they would all be processed fully and not require code duplication. This would technically require a very simple MySql Query for example, `SELECT * FROM Resource`.
- [ ] Create function to automatically record all Synapse Table Ids for all loaded base tables and update `nf_joins_for_synapse.csv`.
- [ ] Add functions to `synapse_query` that would allow the creation of Materialized Views using [Tom's new additions to they Python client.](https://github.com/Sage-Bionetworks/synapsePythonClient/pull/903)
- [ ] Push Materialized Views to Synapse, update `nf_joins_for_synapse.csv` with all newly created TableIds (if possible do so automatically like mentioned above.
- [ ] Convert all current Sql Joins to Synapse Joins (add new column to `nf_joins_for_synapse.csv`) to house the Synapse Joins.

**Comment by milen-sage** [comment]
This is awesome! 

@mialy-defelice you mentioned renaming the files a bit; that makes sense (e.g. making the modules NF-agnostic).

**Comment by mialy-defelice** [comment]
@milen-sage actually these scripts are NF specific...but I was thinking of renaming the parts that specify sql for example `sql_query_nf` to `query_nf.py`. 

We decided not to really refactor these scripts and to wait to make it into a package. Though I don't think it would take that much, probably just adding more things to the config file, I was trying to keep things things out that might be potentially confusing and might not be needed eventually if aliasing is implemented. 

The actual class names are NF agnostic.
