### ISSUE TITLE
API Schematic, allow user to enter many dataset_ids to the manifest endpoint

### ISSUE THREAD

**Issue by mialy-defelice** [Sage-Bionetworks/schematic#598]
**Is your feature request related to a problem? Please describe.**
Allow users to add many dataset_ids to the API manifest endpoint, would follow the decision to allow users to make multiple manifests at a time.

**Describe the solution you'd like**
Users able to add many dataset Ids to the API endpoint.

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Additional context**

**Comment by ychae** [comment]
@mialy-defelice isn't this already completed?

**Comment by mialy-defelice** [comment]
> @mialy-defelice isn't this already completed?

Not that I'm aware of...unless @linglp did it in another pr?

**Comment by mialy-defelice** [comment]
Note this would add specifically to the endpoint `manifest generate`.

@milen-sage should we also make an issue to add this to the commands or just include it in this issue as well?

**Comment by milen-sage** [comment]
@mialy-defelice let's start a separate issue for the CLI.
