### ISSUE TITLE
Download a file from manifest get instead of gsheet url

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/schematic#599]
**Is your feature request related to a problem? Please describe.**
Related to #569. Posting xlsx versions of manifests as templates on Synapse is common. Having `schematic manifest get` return an xlsx file downloaded from the google sheet would eliminate needing to manually access the URL.

**Describe the solution you'd like**
A flag for xlsx, csv, possibly other output in the [google drive api](https://developers.google.com/drive/api/v3/ref-export-formats)
`schematic manifest --config config.yml get --output_csv test.csv` but with an xlsx output type.

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Comment by ychae** [comment]
AC: implement downloading a manifest in xlsx format
