### ISSUE TITLE
Update readthedocs to remove installation inconsistencies

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/schematic#602]
**Is your feature request related to a problem? Please describe.**
readthedocs has inconsistencies that conflict with the other installation instructions and need to remove

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months (@ychae update if SH need it sooner)

**Additional context**
https://sage-schematic.readthedocs.io/en/develop/index.html

**Comment by linglp** [comment]
Close this issue for now since most conflicts should be resolved with [PR 604](https://github.com/Sage-Bionetworks/schematic/pull/604).
