### ISSUE TITLE
Clean up readthedocs

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#606]
**Is your feature request related to a problem? Please describe.**

- [x] Clean up readthedocs (i.e. remove the parts related to installation and only keep the part related to CLI)
- [x] Make sure the command line functionalities in command.py are consistent
- [x] Rebuild documentation related to CLI and publish it through readthedocs
- [x] Link ReadMe CLI section to readthedocs

*Note*: for explaining the usage of CLI, in the future we would want to use Jupyter Notebook. 

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Additional context**

**Comment by milen-sage** [comment]
Acceptance criteria: all items above are checked :)

**Comment by milen-sage** [comment]
We can discuss publishing of the docs later - we may need a business license for readthedocs

**Comment by milen-sage** [comment]
This is done. I just need to transfer the readthedocs ownership to @linglp for now (we can decide if we'd like more owners later).
