### ISSUE TITLE
API: Complete schematic end points used in DCA w/o dashboard

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#607]
From #590

Functions that data curator uses from schematic/store/synapse.py that require an endpoint

- [x] getStorageProjects
- [x] getStorageDatasetsInProject
- [x] getFilesInStorageDataset

Functions that data curator uses from schematic/manifest/generate.py

- [x] populateModelManifest - double check - this may have been implemented as an endpoint already.

**Comment by milen-sage** [comment]
Acceptance criteria: endpoints above are added to the REST API.

**Comment by milen-sage** [comment]
This should also close issue #603

**Comment by milen-sage** [comment]
@linglp the only remaining item is to check whether the populated manifest google sheet contains newly added files to dataset - i.e. new dataset files that haven't been yet included in the csv uploaded to the populateModelManifest endpoint. If new files are not included, we can open a separate issue and tackle in one of the next sprints.

**Comment by linglp** [comment]
@afwillia all the endpoints mentioned here were finished and merged to develop!
