### ISSUE TITLE
Add option to schematic to create/update Synapse tables instead of row-based entities

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#610]
Currently schematic creates a folder entity on Synapse for each non-file record/row in a manifest. Let's make this optional. 

Add a flag to associateMetadataWithFiles to allow either storing manifest rows in Synapse tables, or storing manifest rows as entities (current behavior), or both.

Tables associated with a given manifest would need to be created, if the manifest has been added for a first time to a dataset; or updated, if a manifest (and a corresponding table) already exists for a given dataset.

**Comment by mialy-defelice** [comment]
Acceptance Criteria: 

- [ ] Make creating a folder entity for non-file record/row in manifest optional.
- [ ] Add flag to associateMetadataWithFiles. (is this just storing a manifest as a table)
- [ ] Store manifest as a table.

This is all just in schematic? Or HTAN does anything need to be done for HTAN?

**Comment by milen-sage** [comment]
Let's sync up with Adam on whether we want to remove all existing entities and create tables instead.
