### ISSUE TITLE
Implement additional validation rules for feature parity with dccvalidator

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#612]
Sync with Anthony on which validation rules are needed

**Comment by afwillia** [comment]
@milen-sage @GiaJordan https://github.com/Sage-Bionetworks/schematic/issues/558

**Comment by milen-sage** [comment]
Thanks @afwillia!

@GiaJordan I checked the ones that we have captured already in various schema logic. Perhaps you can start with these:

- [ ]  Empty columns produce a warning.
- [ ]  Ages over 90 are censored.
- [ ]  No filepaths in the manifest are duplicated. - can start with this one

We can discuss how to handle the censoring of ages over 90, and if that falls in validation rules or in a different piece of code. 

schematic already produces an error if columns that are required by the schema are empty columns. It'd be interesting to see how we can raise warnings and not just errors in general, so let's tackle that one too: if there are columns that are not required but are left completely empty let's return a warning. This may require refactoring our errors data structure.

**Comment by GiaJordan** [comment]
**Acceptance Criteria:**
- [ ] Recommended
- add 'Recommended' validation rule that raises warnings if column is empty
- check if required, throw warning if not, error will raise if so

- [ ] protectAges 
- Ages over 90 and under 18 get censored to >90 or <18 and a warning or error is raised

- [ ] unique
- error or warning raised if duplicates
@milen-sage
