### ISSUE TITLE
Document the process of using Read the Docs

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#617]
**Is your feature request related to a problem? Please describe.**

- [x] Document the process of using Read the Docs
- [ ] Document the process of publishing

**Describe the solution you'd like**
A clear ReadMe

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by ychae** [comment]
@milen-sage will need to give Lingling access to publish readthedocs

**Comment by linglp** [comment]
@ychae I have updated the documentation related to Readthedocs. But I have not yet gotten credentials to officially republish our documentation.

**Comment by linglp** [comment]
Close this issue for now. Milen's Github credentials are tied to publishing Readthedocs, so it is not easy to transfer. We could open another issue again for publishing.
