### ISSUE TITLE
Lock versions of frequently used schematic dependencies

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#624]
In poetry toml file lock versions of 

- [x] SynapseClient
- [x] Pandas
- [x] Numpy

**Comment by milen-sage** [comment]
@mialy-defelice what were the versions that worked for you?

**Comment by milen-sage** [comment]
While we are at it let's also have

markupsafe==2.0.1 in schematic toml

**Comment by mialy-defelice** [comment]
> @mialy-defelice what were the versions that worked for you?

Numpy is already locked at `numpy = "1.21.1"`
My Pandas is `1.3.1`
My Synapse client is `1.5.1`

**Comment by mialy-defelice** [comment]
There are a couple of versioning issues that @linglp brought up in the[ SwaggerUI readme](https://github.com/Sage-Bionetworks/schematic/tree/develop/api). The markupsafe versions, at least, is in the lock file, but maybe it also belongs in the toml?

- itsdangerous version: 1.1.0
- jinja2 version: 2.11.3
- markupsafe version: 2.0.1

We also discovered last night that Python should be at least "^3.9.6" to allow Poetry to work properly.

**Comment by GiaJordan** [comment]
**All versions to lock:**
- [ ] numpy =`1.21.1` - already locked
- [ ] pandas = `1.3.1`
- [ ] synapseClient = `1.5.1` @mialy-defelice are we doing `1.5.1` now instead of `2.5.1`?
- [ ] itsDangerous = `1.1.0`
- [ ] jinja2 = `2.11.3`
- [ ] markUpSafe = `2.0.1`
- [ ] python = `3.9.6` - to be addressed in separate issue after checks with GH actions

**Comment by GiaJordan** [comment]
@milen-sage @mialy-defelice my pandas version that I've been working with is `1.3.1`

**Comment by mialy-defelice** [comment]
> * [x]  synapseClient = `1.5.1` @mialy-defelice are we doing `1.5.1` now instead of `2.5.1`?

I must have mistyped.

**Comment by mialy-defelice** [comment]
> @milen-sage @mialy-defelice my pandas version that I've been working with is `1.3.1`

This matches my version.
