### ISSUE TITLE
Update README.md contributor’s section to add lock file and toml management

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#625]
**Is your feature request related to a problem? Please describe.**

We're going to switch to [locking the versions of some of the core dependencies](https://github.com/Sage-Bionetworks/schematic/issues/624), to avoid users getting errors because they're using newer versions of packages that we haven't tested yet.

In general, when users do `poetry install`, they could get the controlled version of packages from the lock file. In this way, we could make sure that users have all the dependencies for all of packages schematic needs. 

In the case that it doesn't work for a user, they can delete the file and install the poetry library again, and it'll generate a new .lock file that will work for them.

**Describe the solution you'd like**
Update the README section. 

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by ychae** [comment]
AC: update and publish
