### ISSUE TITLE
Integrate Schema Viz into Schematic.

### ISSUE THREAD

**Issue by mialy-defelice** [Sage-Bionetworks/schematic#626]
**Is your feature request related to a problem? Please describe.**
The schema visualization code is currently working outside of schematic as a series of scripts.

- `parse_json_manifest.py`

    - Uses individual json validation files easily determine all the attributes connected per manifest and all the required and conditionally required/optional dependencies. This file is used to put together all the data for the table and gather all the components to list in the observable dropdown. Has a single file output per model.

- `get_dependencies.py` 

    - This is the script that makes the normal and highlighted text to appear in the visualization into the proper data structure to be used by Observable. It also provides the data structure in order for observable to construct the tangled tree. Has many outputs. 2 text outputs and many tangled tree structure outputs. For the dependency view of the tangled tree it would be the number of components per model.
     
**Describe the solution you'd like**
Integrate this code into schematic and create REST API endpoints so we can create a backend to the visualization.  For `parse_json_manifest.py` want to shift from using `json` files to being able access the model instead.

**How important is this feature?** Select from the options below:

• 🌋 Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by milen-sage** [comment]
Acceptance criteria: @ychae perhaps we could use the section "Describe the solution you'd like" as AC? This could work in general too. Or we may want to change the template for enhancement/features and bugs to include AC section explicitly? 

What do you think?

**Comment by mialy-defelice** [comment]
- [ ]  Add unit tests
