### ISSUE TITLE
 setup github action to run PyPi publishing

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#628]
**Is your feature request related to a problem? Please describe.**
To automate our PyPi release process, we would need to set up a series of GitHub actions. We could refer how that was set up for the data curator app [here](https://github.com/Sage-Bionetworks/data_curator/blob/4802eba3107d500145138b4f2c0a2f1ef7ee394a/.github/workflows/shinyapps_deploy.yml#L13-L14)

**Describe the solution you'd like**

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by ychae** [comment]
@milen-sage access to PyPi

**Comment by linglp** [comment]
@ychae : we are almost there. I just got added as maintainer on PYPI and I will test it out the release workflow later today.

**Comment by ychae** [comment]
Moving to Sprint 6 - @milen-sage will identify how to add @linglp as maintainer to the test PyPI instance

**Comment by linglp** [comment]
To do:  Remove the part related to PYPI testing in github workflow and test publishing to PYPI

**Comment by linglp** [comment]
@ychae Close this issue for now. We will wait until stakeholders finish testing for the new validation rules to do an official release.
