### ISSUE TITLE
Handle Censored and Uncensored Manifests

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#629]
**Is your feature request related to a problem? Please describe.**
The censoring of manifest data has been introduced into schematic for feature parity with DCC validator. Only uploading censored manifests protects sensitive information, ex: ages over 90 or under 18, but while we wish to prevent the broader sharing of this information, we do not wish to take away information that might be necessary for data submitters or others as appropriate.

**Describe the solution you'd like**
When censoring of a manifest is necessary:
- upload a censored version of the manifest, with permissions enabling sharing to other specified entities
- upload an uncensored version of the manifest, with stricter sharing permissions, ex: only to submitters of the data.

**How important is this feature?** Select from the options below:
• 🌋 Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**
Additionally, we may want to also create censored and uncensored tables based on manifests at upload?
cc @milen-sage @mialy-defelice

**Comment by ychae** [comment]
@milen-sage will add additional details and AC
@GiaJordan needs what level of sharing permissions for uncensored manifests
