### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#63]
We have some FAQ material (@xdoan could you link the latest version here?). 

@liz-williams what do you think are some missing pieces, if any, we want to include in v0 (I guess aside from linking to detailed SOPs, if we want to have an FAQ for initial distribution soon)?

#roadmap

**Comment by ychae** [comment]
FAQ section in data ingress docs: https://ncihtan.github.io/HTAN-Data-Ingress-Docs/faq.html
