### ISSUE TITLE
add schemasheets and linkml to schematic toolchain

### ISSUE THREAD

**Issue by sujaypatil96** [Sage-Bionetworks/schematic#631]
There is a new tool on the block, written by @cmungall called [schemasheets](https://github.com/linkml/schemasheets/), which we released a few months ago.

I think this tool could be a good replacement or addition to the schematic toolchain. The schemas and data models that are currently maintained as Googlesheets can be translated to LinkML data models by simply modifying the existing, say HTAN schema to be compatible with schemasheets syntax.

Once the schema has been translated to LinkML, you can take advantage of the various generators that are baked into the LinkML library.

One use case in the context of schematic, that I can think of currently:
* Rather than generating the JSON Schema from the Google spreadsheet, you can use the schemasheets spreadsheet to generate the LinkML model, and use the `gen-json-schema` CLI command to auto generate the JSON Schema
* TODO: _add more use cases_

CC: @milen-sage @ychae @mialy-defelice @cmungall

**Comment by milen-sage** [comment]
@sujaypatil96this is awesome! We are looking into it and it'd fit nicely into the toolchain for INCLUDE.

We can catch up on it towards the end of April? We can provide some feedback and how we could start integrating it.

**Comment by sujaypatil96** [comment]
@milen-sage: Yes, absolutely. We can discuss how LinkML can be leveraged for INCLUDE's use case on our periodic Friday LinkML call.

Some resources:
* schemasheets documentation: https://linkml.io/schemasheets/
* LinkML documentation: https://linkml.io/linkml/

I'm not sure if you're following a similar strategy for INCLUDE as you did with HTAN? With getting RFC's from expert curators on a Google Spreadsheet and then translating it to a data model? If so, you can consider using schemasheets with [cogs](https://github.com/najoungkim/COGS) to maintain the source of your data model, which can further be translated into a LinkML data model. And JSON-LD, JSON Schema, and other artifacts downstream from that depending on what you want to use.

**Comment by sujaypatil96** [comment]
@milen-sage: do let us know when you're ready with a rough draft of the schemasheets spec. for the HTAN Schema.

If you need schemasheets support, feel free to message us on the schemasheets Slack channel: https://monarchinitiative.slack.com/archives/C03BY689PQ9
