### ISSUE TITLE
Create an API endpoint to download manifests as CSV 

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#632]
**Is your feature request related to a problem? Please describe.**
The DCA needs an endpoint to download an existing manifest as a csv. Currently it uses Synapse's REST API directly to download a csv manifest file. However, we'd like to decouple the DCA from Synapse.

**Describe the solution you'd like**
Create an endpoint for downloading a manifest that [uses this function](https://github.com/Sage-Bionetworks/schematic/blob/8efa7296a6f3381b12e3640e63d3f6b8f1b6a8c7/schematic/store/synapse.py#L278). Currently, the GET manifest endpoint only returns the existing manifest or create a new empty manifest. We would need a new endpoint for the data curator app. 

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Additional context**
Acceptance criteria: A new endpoint gets created and tested.

**Comment by linglp** [comment]
@milen-sage and @afwillia could you let me know what this endpoint should return? I can have the endpoint download an existing manifest (in CSV format) and return local path of the downloaded manifest. Will that be sufficient? Or do we want to return a JSON with content from the CSV?

**Comment by milen-sage** [comment]
Downloading the existing csv and returning a path should work for the DCA use cases, and we can start there? @afwillia would the content of the manifest itself be useful as JSON in any way for the app currently?

**Comment by afwillia** [comment]
@milen-sage @linglp DCA doesn't do much with the content of the manifest so returning JSON at the moment won't have an effect.

**Comment by linglp** [comment]
Thank you @milen-sage and @afwillia ! I will let this endpoint return a local file path then.

**Comment by lakikowolfe** [comment]
Just popping in with some thoughts on this

Lingling and I spoke briefly today about the existing API endpoints and what will be needed for the Data Flow Coordinator App (AKA Release Administrator). My initial thought is that the content of the manifest would be most useful for this app as JSON rather than returning a path to a downloaded csv. Just wanted to log that here for now! Happy to talk further as the Data Flow Coordinator develops.

**Comment by milen-sage** [comment]
@lakikowolfe that's great to know! We can think about adding an argument to the endpoint to indicate whether to return the JSON representation of the csv file.
