### ISSUE TITLE
Validation Rules Combination Architecture 

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#633]
**Is your feature request related to a problem? Please describe.**
Expand the functionality of validation rules to allow for multiple rules to be used in the validation of one attribute. Currently, rule combinations are limited to list and regex validation.

**Describe the solution you'd like**
Allow for the use of multiple validation rules to validate a single attribute
**ex:** `list::int::recommended` 

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks
or
• Mid-term - 2-4 months

**Additional context**

**Comment by ychae** [comment]
@GiaJordan will speak with @mialy-defelice and @milen-sage to scope this out

**Comment by GiaJordan** [comment]
Structure to use multiple validation rules for in house and GE validation suites in place. More work to be done to test rule combos, make valid rule combinations clear, and clearly define limits and rules of combos. For rule combinations, the list rule is being updated to allow for combinations with other rules
@ychae

**Comment by ychae** [comment]
@GiaJordan do you think this work can be accomplished in the half sprint we have coming up? I don't want you to lose momentum on this but also recognize that this is a complex issue -- we can move it to Sprint 7 if more time is required!

**Comment by GiaJordan** [comment]
@ychae I think it would be better to move this back to sprint 7 to allow for enough time for the remaining implementation and testing. It's in a place that shouldn't be too hard to pick up again at the start of that sprint

**Comment by ychae** [comment]
That sounds great! Thanks for the quick response -- the ticket's been updated 😁

**Comment by GiaJordan** [comment]
Validation Rules Combination will be converted to epic
Updated AC for ticket:
Develop structure to validate multiple rules for a single attribute. Rule combinations will be added in stages, prioritized based on use
