### ISSUE TITLE
Validation on attributes with `list` rule causes error

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#648]
NOTE: Transferred from the DCA repository because it is probably a schematic-level issue I am running into. 

**Describe the bug**
When trying to validate a manifest in the data curator app the app crashes and I get this error:

```
2022-04-05T23:09:41.297404+00:00 shinyapps[5727796]: Warning: Error in validationResult: object 'annotation_status' not found
2022-04-05T23:09:41.297516+00:00 shinyapps[5727796]:   13: fn
2022-04-05T23:09:41.297461+00:00 shinyapps[5727796]:   15: <Anonymous>
2022-04-05T23:09:41.297625+00:00 shinyapps[5727796]:    7: connect$retryingStartServer
2022-04-05T23:09:41.297664+00:00 shinyapps[5727796]:    6: eval
2022-04-05T23:09:41.297580+00:00 shinyapps[5727796]:    8: retry
2022-04-05T23:09:41.297712+00:00 shinyapps[5727796]:    5: eval

````

I tried to generate a new manifest in one of our demo projects and validate that and it worked fine, and I don’t see that other users have had this issue in our logs, so I am guessing it’s something to do with the contents of this manifest or the dataset I’m using…

It appears to happen when include annotations for this column in the manifest: https://github.com/nf-osi/nf-metadata-dictionary/blob/main/NF.csv#L406

**To Reproduce**
Alright, so I was able to come up with something reproducible: it happens whenever I try to annotate something that has a list validation rule. We have three attributes that have this rule: modelSystemName,tumorType and cellType. description of what the bug is.

1. Go to NF Data Curator App
2. Select a dataset, e.g. w/ genomics manifest
3. Fill in manifest, annotating modelSystemName,tumorType or cellType. 
4. Try to validate manifest 

**Expected behavior**
Validation should proceed, instead app crashes. 

**Environment**
This is using the app as built here: https://github.com/nf-osi/NF_data_curator/actions/runs/2001994081/workflow, with the develop version of schematic from 19 days ago, as well as the current version of develop through today (https://github.com/nf-osi/NF_data_curator/actions/runs/2099292364)

**Priority** (select one)
- [ ] Minor ⬇️
- [x] Major 📢
- [ ] Critical 🆘

**Additional context**
slack here: https://sagebionetworks.slack.com/archives/C01ANC02U59/p1649197443845809
Might be related to Sage-Bionetworks/data_curator#309 ?

**Comment by mialy-defelice** [comment]
Hey @allaway,

Can you upload the manifest that is causing this error?

Thank you!

**Comment by allaway** [comment]
Hey Mialy,

I just stepped away from my computer but my previous comment has an example
manifest in one of the code blocks!

**Comment by mialy-defelice** [comment]
Hey @allaway,

Is this the link you were referring to?

> It appears to happen when include annotations for this column in the manifest: https://github.com/nf-osi/nf-metadata-dictionary/blob/main/NF.csv#L406

I tried following that link earlier but it actually just took me to your data model. It's also the same as the one you sent on slack earlier.

**Comment by allaway** [comment]
Nope! Sorry for not being clearer. This is the test manifest:


```
Filename,progressReportNumber,fileFormat,resourceType,dataType,dataSubtype,assay,individualID,sex,species,modelSystemName
Whole Exome Sequencing/hc5gydsx3_agaacctaca-gatatatggc_l001_r1.fastq.gz,6,fastq,experimentalData,genomicVariants,raw,Whole Exome Sequencing,UF17,Male,Homo sapiens,foo

```

**Comment by mialy-defelice** [comment]
Ahh okay...sorry I thought that was just a snippet!
