### ISSUE TITLE
schematic pypi package ownership

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#654]
@sujaypatil96 we are working on streamlining the schematicpy release process. That requires adding more collaborators and owners of the package. It looks like I currently don't have access to the package management tools (e.g. I can't add owners). Could you double check if you can still manage the package, and if yes check if my account is an "owner"?

Thanks!

<img width="1188" alt="Screen Shot 2022-04-07 at 12 21 50 PM" src="https://user-images.githubusercontent.com/41303818/162287529-3863769a-69e3-4e87-9749-9af1f7716c85.png">

**Comment by milen-sage** [comment]
@sujaypatil96 added screenshot above. Are you seeing an active "Manage" button?

**Comment by sujaypatil96** [comment]
@milen-sage: yup, I'm seeing the _manage_ button. Since I made the first release, I got auto assigned **owner** permissions. I'll change your permissions to **owner** too, which is basically the highest level of privilege. You should be able to administrate collaborator permissions after that.

**Comment by milen-sage** [comment]
Thank for the quick reply and action @sujaypatil96 ! I see the button active now.
