### ISSUE TITLE
Compare API testing libraries 

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#657]
**Is your feature request related to a problem? Please describe.**
Compare [Behave ](https://behave.readthedocs.io/en/stable/api.html) and [schemathesis](https://github.com/schemathesis/schemathesis)

**Describe the solution you'd like**
Compare these two libraries in terms of the following: 
1) Are they compatible to Open API framework? 
2) How well is their documentation?
3) How much work for setting things up? 
4) How "mature" is the library? (i.e. number of forks, contributors, number of releases, active PRs)

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Additional context**
AC: create tests for API endpoints using these two libraries; make a conclusion about what library we should use going forward.

**Comment by Stranger6667** [comment]
Hey @linglp 
Schemathesis author here. Feel free to ping me directly (here or in the Schemathesis repo/Discord) if you'll need any support from my side or if there are any features you're missing :) I'd be happy to collaborate

**Comment by linglp** [comment]
> Hey @linglp Schemathesis author here. Feel free to ping me directly (here or in the Schemathesis repo/[Discord](https://discord.gg/R9ASRAmHnA)) if you'll need any support from my side or if there are any features you're missing :) I'd be happy to collaborate

Hello @Stranger6667 ! Can I ask you a question related to passing a token to schemathesis before an API call: 
We are using `flask` and `swagger` for our application. Some of our API end points require a token from the users (In other words, users have to manually pass down a token on Swagger UI before executing the API call). Do you know if there's a way to pass my input token from my local config file to a test? For example, please take a look at the code below: 
```
@pytest.fixture
def auth_token():
    """Fixture for loading authentication"""
    # reading configuation data from .SynapseConfig
    config = configparser.ConfigParser()
    synapse_config = config.read(".synapseConfig")
    token = config['authentication']['authtoken']

    return token

@schema.parametrize(endpoint="/manifest/download")
@settings(deadline=None)
def test_manifest_download(case, auth_token):
    case.call_and_validate(input_token = auth_token) # this currently doesn't not work. But I want to be able to pass my token to the endpoint
```

Thanks!

**Comment by Stranger6667** [comment]
Hi @linglp 

I think something like this should work:

```python
@schema.parametrize(endpoint="/manifest/download")
@settings(deadline=None)
def test_manifest_download(case, auth_token):
    case.headers = case.headers or {}
    case.headers["Authorization"] = f"Bearer {auth_token}"
    case.call_and_validate()
```

The main idea is that you need to modify `case` in place - I assumed that your token is likely to be sent via the `Authorization` header. But if not, then you can freely set any other header (e.g. `X-API-Key` or any other appropriate).

**Comment by linglp** [comment]
Notes: Schemathesis is helpful for ensuring our codes are rigorous, and making sure that the users do not always just see error 500. In addition, instead of writing all kinds of tests ourselves to test all edge cases, we could simply just run something like: 
```
schema = schemathesis.from_uri("https://example.schemathesis.io/openapi.json")

@schema.parametrize()
def test_api(case):
    case.call_and_validate()
```
Then Schemathesis would read about definitions of API endpoints from `swagger.json` and pass down a bunch of tests. For example, before using Schemathesis, we didn't have code to handle cases like "0", " ", or something that is not a valid URL for schema_url parameter. It also helps us write `swagger.json` more rigorously and document all error codes.

**Comment by linglp** [comment]
> Hi @linglp
> 
> I think something like this should work:
> 
> ```python
> @schema.parametrize(endpoint="/manifest/download")
> @settings(deadline=None)
> def test_manifest_download(case, auth_token):
>     case.headers = case.headers or {}
>     case.headers["Authorization"] = f"Bearer {auth_token}"
>     case.call_and_validate()
> ```
> 
> The main idea is that you need to modify `case` in place - I assumed that your token is likely to be sent via the `Authorization` header. But if not, then you can freely set any other header (e.g. `X-API-Key` or any other appropriate).
> 
> There are a few more attributes you might want to modify - `case.query`, `case.cookies`, `case.path_parameters`, `case.body`
> 
> Let me know if that helps :)

Hello @Stranger6667 !Thanks for the quick reply! I tried that and it didn't work because our input_token is a parameter instead of a header. For example, please see our input_token defined below in `swagger.json`
```
    "/manifest/download": {
      "get": {
        "summary": "Endpoint to download an existing manifest",
        "description": "Endpoint to download an existing manifest",
        "parameters": [
          {
            "in": "query",
            "name": "input_token",
            "schema": {
              "type": "string",
              "nullable": false
            },
            "description": "Token",
            "example": "Token",
            "required": true
          },
```

**Comment by Stranger6667** [comment]
You're very welcome! :) 

Thanks for sharing the schema! The following should work with a query parameter

```python
@schema.parametrize(endpoint="/manifest/download")
@settings(deadline=None)
def test_manifest_download(case, auth_token):
    case.query = case.query or {}
    case.query["input_token"] = auth_token
    case.call_and_validate()
```

**Comment by linglp** [comment]
> ```python
> case.query["input_token"] = auth_token
> ```

It is working now! Thank you so much!

**Comment by Stranger6667** [comment]
Sure thing! :) let me know if you have any further questions!

**Comment by linglp** [comment]
@ychae Let me move this to the next sprint. I was able to play around with Schemathesis and talk to Milen about its functionality. But I have not yet tried Behave.
