### ISSUE TITLE
Update schematic release documentation 

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#658]
**Is your feature request related to a problem? Please describe.**
Update release documentation since we now could use GitHub workflow for release. 

**Describe the solution you'd like**

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**
AC: documentation gets published.

**Comment by milen-sage** [comment]
We' need to figure out where docs like that live for schematic - confluence or gh? Currently a google [doc](https://docs.google.com/document/d/1z0DIN9rSoSoIaUttN1NMt7qImYMWhHC0QwO1WVPTvEQ/edit?disco=AAAAZoJvkcg)

**Comment by mialy-defelice** [comment]
@milen-sage should I go ahead and start moving the documentation over to SH?

**Comment by milen-sage** [comment]
Yes, thanks @mialy-defelice!

**Comment by mialy-defelice** [comment]
@milen-sage  Thoughts on [current progress](https://sagebionetworks.jira.com/wiki/spaces/SCHEM/pages/2651553822/FAIR+Data+Development+Workflow+and+Versioning)?

**Comment by mialy-defelice** [comment]
@milen-sage Rebumping my previous question :)

**Comment by milen-sage** [comment]
@mialy-defelice this is great - thanks! We can maintain there, and if we have develop the same docs on GH readmes (e.g. schematic release process @linglp documented) we can remove text and link to GH.
