### ISSUE TITLE
Schema visualization tools

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#66]
Customize and use existing tools to 
- [ ] visualize schema dictionary on the web
- [ ] visualize data models

@milen-sage to provide examples; @jcorn427 and @xdoan (and potentially other people as we are resourcing) to help with customization. 

@liz-williams, do you think we can hand-off a barebones data model visualization site along the lines of what we showed at the DCC west meeting and have someone on your side to work on HTAN web branding/style?

#roadmap

**Comment by milen-sage** [comment]
@mialy-defelice a throwback to pre-covid times :)

**Comment by milen-sage** [comment]
My estimate of 8 points (which translated to 16-20 hours of work in our planning at the time) was probably a bit off.

**Comment by ychae** [comment]
closing as this work is being tracked in various milestones like this one: https://github.com/Sage-Bionetworks/schematic/milestone/27
