### ISSUE TITLE
Integers are uploaded to synapse as doubles

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#664]
**Describe the bug**
Uploading a integer-like string, (e.g. `1`) as an annotation to Synapse gets coerced to a double (`1.0`). This causes two issues:
 - it takes a valid value (string `1`) and converts it to an invalid value (double `1.0`) so the resulting data are no longer compliant, these have to be fixed manually after the fact
 - if _not_ fixed after the fact, when a user goes to re-annotate files, the data that they had originally input that were valid have been altered and no longer pass validation. 

**To Reproduce**
1. Go to DC app. 
2. Create a manifest. 
3. Fill in a column with all integer-like values. 
4. Submit to synapse. 
5. See annotations, which should have doubles (See screenshot for example) 

**Expected behavior**
I would expect schematic to not alter the user's input. 

**Priority** (select one)
- [ ] Minor ⬇️
- [ X ] Major 📢
- [ ] Critical 🆘

**Screenshots**
<img width="298" alt="Screen Shot 2022-04-13 at 10 38 30 AM" src="https://user-images.githubusercontent.com/20408008/163238538-eaf44cf4-a0ad-47b9-a945-03e6a8c7585b.png">

**Additional context**
Assume this related to #600 ?
I believe this will affect the HTAN data model too. For example, readPair and readLength in the NF Data Model (ReadIndicator and ReadLength in HTAN) are both converted to doubles.

**Comment by allaway** [comment]
Doing some more digging I'm guessing this is why this happens: https://github.com/Sage-Bionetworks/schematic/blob/4b077c73272fd653c3479d7d1d7e49697b827e39/schematic/utils/df_utils.py#L33

IMO this causes two issues: for strings that are integer-like (e.g. read pair = 1) this makes it a double (1.0), and for strings that could theoretically be doubles (e.g. age = 50) this adds false precision (50.0) when we don't necessarily have that accurate of an age.

**Comment by allaway** [comment]
@GiaJordan commented in #664:

>It should address https://github.com/Sage-Bionetworks/schematic/issues/664 but from what I've gathered it think there's also something happening before schematic when the manifest is created that influences the number value read. The manifests that I've created and uploaded during my testing process for this did not have the issue you described, but this fix was intended for something slightly different so there may be more at play for that specifically.

I think your comment that there might be more at play is correct; I just tested uploading a manifest on our staging instance of the DCA using the latest version of `develop` (35fa1eb) and this issue appears to persist! So there must be something else going on here.

**Comment by GiaJordan** [comment]
Did some more digging, seems like a Pandas issue: [#31821](https://github.com/pandas-dev/pandas/issues/31821)
I'll try out the solutions mentioned in the linked thread and see if they'll work for our use cases here
@allaway

**Comment by GiaJordan** [comment]
**AC**: `int` values uploaded as synapse annotations without conversion to `float`
@ychae
