### ISSUE TITLE
DisplayName error when generating a manifest

### ISSUE THREAD

**Issue by brynnz22** [Sage-Bionetworks/schematic#671]
For the CSBC data model, I am not able to generate a manifest for the `Tool` component. The jsonld generates just fine. Attached is the CSBC data model and a screen shot of the error. The jsonld and the config.yml are not supported on here, so I can't attach it.

**To Reproduce**
1. In the config file, type 'Tool' for the `data_type`
2. Save
3. The command I am using to generate the manifest is: `schematic manifest --config /Users/bzalmanek/Documents/csbc_schematic/schematic/config.yml get -s -oauth`

**Expected behavior**
A link to a Tool manifest will be given.

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [ X] Critical 🆘

**Screenshots**
<img width="1288" alt="Screen Shot 2022-04-15 at 3 33 57 PM" src="https://user-images.githubusercontent.com/46435419/163649737-7a42f08b-7bcb-4c01-b233-7a5600760e82.png">

**Desktop
 - OS: [macOS]
 - Browser [Chrome]

CSBC data model: https://docs.google.com/spreadsheets/d/1hbG1vdi8a0gc-6psn5VgsBgyMl6IOhDSbHWDuC_8EXo/edit#gid=59750547

[csbc.model.csv](https://github.com/Sage-Bionetworks/schematic/files/8498803/csbc.model.csv)

**Comment by brynnz22** [comment]
I do not need this issue fixed; I realized I need to delete these valid values anyway.

**Comment by brynnz22** [comment]
I accidentally closed the wrong issue. I did need this fixed. Sorry about this!

**Comment by milen-sage** [comment]
@brynnz22 thanks for the sleuthing! Sounds like your immediate problem is resolved and we can close this issue? 

We can document the biothings namespace to avoid collisions in the future (longer term we will have a mechanism for resolving namespace collisions).

**Comment by brynnz22** [comment]
Yep. Sounds good. Thank you!
