### ISSUE TITLE
schematic: download a manifest with a specified name instead of default name

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#684]
Currently schematic downloads a dataset manifest with the name that was used to upload a dataset manifest (e.g. synapse_storage_manifest.csv). We can enable clients to provide a filename to be used for manifest download to the schematic service. There are different use case, some in the DCA raised by @rrchai.

**Comment by mialy-defelice** [comment]
- [ ] API
- [ ] CLI

**Comment by mialy-defelice** [comment]
@milen in our notes, I wrote down that you wanted to update both CLI and API with this option. I actually only saw an existing manifest download function within the API. Do you want a new CLI option to download the manifest?

**Comment by mialy-defelice** [comment]
@mialy-defelice Create a new ticket for creating a new command for this in the CLI
