### ISSUE TITLE
schematic: handle cases where Component is not present in manifest

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#694]
Currently, in store/synapse.py this [line](https://github.com/Sage-Bionetworks/schematic/blob/18909db70d3d2de4c15549b913c8ced019869564/schematic/store/synapse.py#L609) assumes `Component` is present in every manifest; similarly lines below require the presence of 'Component'. In the future, it's possible we can assume that. However, at the moment for backward compatibility,  submissions of manifests can proceed even if the `Component` columns is not in a manifest. 

This will partly address the issue [here](https://github.com/Sage-Bionetworks/schematic/issues/685).

**Comment by mialy-defelice** [comment]
@milen-sage I think you accidentally left out a link here: 
>Currently, in store/synapse.py this line assumes

**Comment by milen-sage** [comment]
@mialy-defelice thanks for spotting. I added the link :)
