### ISSUE TITLE
schemaHub docs: add note that cross-validation is not available for data models w/o components

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#695]
Cross-validation expects `Component` to be specified in the data model. E.g.  [here](https://github.com/Sage-Bionetworks/schematic/blob/725f2bd4df5cd1117e8abd1de926162912cdf4c7/schematic/models/validate_attribute.py#L359).

This is fine - it's the expected behavior. However, should we add a note to the respective validation rules or @GiaJordan do you think it's already pretty obvious you can't use these validation rules if you don't have components? If the latter, feel free to close this issue :)

Closing this issue, in conjunction with  #694, should address #685.

**Comment by GiaJordan** [comment]
I think it would be better to explicitly say it's not supported to limit confusion! I'm actually going through and updating the [documentation ](https://sagebionetworks.jira.com/wiki/spaces/SCHEM/pages/2473623559/The+Data+Model+Schema#A.-Schema-properties-and-relationships)on the validation rules, so I can add a note to the cross manifest rules right now.
@milen-sage

**Comment by GiaJordan** [comment]
Added to the [confluence page](https://sagebionetworks.jira.com/wiki/spaces/SCHEM/pages/2473623559/The+Data+Model+Schema#A.-Schema-properties-and-relationships)
