### ISSUE TITLE
jsonschema.exceptions.ValidationError error when using example json schema url 

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#696]
**Describe the bug**

**To Reproduce**
For context, my error could be reproduced by following the steps below: 
1. cd `api`
2. `poetry run python3 run_api.py`
3. Go to `manifest/generate` endpoint and hit execute
4. Error: 
```
File "/Users/lpeng/Documents/schematic-git2/schematic/schematic/utils/validate_rules_utils.py", line 171, in validate_schema_rules
    raise ValidationError(
jsonschema.exceptions.ValidationError: The json_schema has an error in the validation_rules set for attribute CheckMatchatLeast. Validation failed with the following errors: [['NA', 'CheckMatchatLeast', 'The json_schema, has an error in the validation rule for the attribute: CheckMatchatLeast, the provided validation rules (matchAtLeastOne MockComponent.checkMatchatLeast Patient.PatientID) is not a valid rule. Please check spelling.', 'Not a Rule'], ['NA', 'CheckMatchatLeast', 'The json_schema, has an error in the validation rule for the attribute: CheckMatchatLeast, the provided validation rules (matchAtLeastOne MockComponent.checkMatchatLeast Patient.PatientID) is not a valid rule. Please check spelling.', 'Not a Rule']]
```

Note: `manifest/generate` endpoint has been working without errors. The new validation rules might affect the example json model, and in return affect the API endpoint. 

**Expected behavior**
A google sheet url could be return from the endpoint without any errors. 

**Priority** (select one)
- [ ] Minor ⬇️
- [X] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**

**Additional context**

**Comment by ychae** [comment]
This has been resolved
