### ISSUE TITLE
not of type \'array\'' affects /model/submission endpoint

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#703]
**Describe the bug**
When I tried to use `model/submit` endpoint for submitting manifest, I came across an error: 
```
jsonschema.exceptions.ValidationError: Manifest could not be validated under provided data model. Validation failed with the following errors: [[2, 'Family History', '"[\'Breast\', \'Colorectal\']" is not of type \'array\'', "['Breast', 'Colorectal']"]]
```

For context, this is how my manifest looks like: 

Patient ID | Sex | Year of Birth | Diagnosis | Component | Cancer Type | Family History
-- | -- | -- | -- | -- | -- | --
123 | Female |   | Healthy | Patient | Breast | Breast,Colorectal

And the submission would fail too if I update the `family history` column to contain only one string. Something like below: 

Patient ID | Sex | Year of Birth | Diagnosis | Component | Cancer Type | Family History
-- | -- | -- | -- | -- | -- | --
123 | Female |   | Healthy | Patient | Breast | Breast

Error message: 
```
jsonschema.exceptions.ValidationError: Manifest could not be validated under provided data model. Validation failed with the following errors: [['2', 'Family History', "For attribute Family History in row 2 it does not appear as if you provided a comma delimited string. Please check your entry ('Breast'') and try again.", 'Breast'], [2, 'Family History', '"[\'Breast\']" is not of type \'array\'', "['Breast']"]]
```

**To Reproduce**
1. Checkout branch: `develop-fix-submit-manifest-endpoint`
2. Run API endpoint `model/submit` by using the manifest that I mentioned above.

**Expected behavior**

**Priority** (select one)
- [ ] Minor ⬇️
- [X] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**

**Additional context**
Might be related to this issue: https://github.com/Sage-Bionetworks/schematic/issues/699

**Comment by GiaJordan** [comment]
@milen-sage related to #699

**Comment by anngvu** [comment]
Since NF is experiencing this, I also combed through the issues -- this is also related to https://github.com/Sage-Bionetworks/schematic/issues/653.

**Comment by linglp** [comment]
@GiaJordan  Thanks! I tested it out with "family history" column has the following values and it all worked: 
*empty 
*with only one string
*with two strings

Thank you!
