### ISSUE TITLE
check if the Google OOB restriction impacts our API Google services usage

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#705]
**Is your feature request related to a problem? Please describe.**
check if the Google OOB restriction impacts our API Google services usage

**Describe the solution you'd like**
 OAuth out-of-band (OOB) flow will be deprecated on October 3, 2022, to protect users from phishing and app impersonation attacks. I will refer to Milen's email and check if that would impact us. 

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by allaway** [comment]
Replying to watch this as I also got an email about this...

**Comment by linglp** [comment]
This issue is related to getting permission/authorization from users. I think this will unfortunately impact us for the following reasons: 

- Based on the documentation [here](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#instructions-oob) provided by Google, to determine if your App is using OOB flow, we would need to check the value of `redirect_url` parameter. 

- I then deleted my `credentials.json` and `token.pickle` and ran the `schematic init --config config.yml` command in the terminal, and here's the URL that I saw: 
`Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=269908437164-h85tuv8smkav558msa7tqhe125t2mrt3.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fspreadsheets+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=HzRNGHDedLvahuw3TNJgOE8vQtoHaU&prompt=consent&access_type=offline`
From the url above, we could see that `redirect_url` has the following value: `urn:ietf:wg:oauth:2.0:oob`. I also opened our `credentials.json` and see that we have: 
```
    "redirect_uris": [
      "urn:ietf:wg:oauth:2.0:oob",
      "oob"
    ]
```

*Note*: `urn:ietf:wg:oauth:2.0:oob` here indicates manual copy and paste for authorization code. See the official explanation [here](https://developers.google.com/identity/protocols/oauth2/native-app#:~:text=app%20listens%20on.-,Manual%20copy/paste,urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob,-Programmatic%20extraction). 

I think the confusing part is that in our code, we didn't explicitly set `redirect_url` parameter. Even when I looked at the[official documentation](https://google-auth-oauthlib.readthedocs.io/en/latest/reference/google_auth_oauthlib.flow.html#google_auth_oauthlib.flow.InstalledAppFlow.redirect_uri) of `InstalledAppFlow.from_client_secrets_file`, it doesn't explicitly say what value that it sets. But for some reasons, we still end up with `oob` in our redirect_url parameter.

**Comment by ychae** [comment]
@linglp another one from Sprint 8 I missed following up on -- can this be closed since it's marked as "Done" on the project board?

**Comment by linglp** [comment]
@ychae Yes. Let me close it
