### ISSUE TITLE
list validation values not being uploaded to synapse as stringList values

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#710]
**Describe the bug**
Values for attributes with list validation requirements that are uploaded to synapse are uploaded as strings, instead of split and uploaded as stringlists. 

**To Reproduce**
1. Install schematic (5eca846740696ec5b882edeb70cf5d29bd20be49). 
2. Create a manifest (e.g. https://docs.google.com/spreadsheets/d/1uMT1kRafUS7WS3-X_vqyxJH9qDXgknWEqw35DLUMLKU/edit#gid=0) that has comma separated values for a `list` validation attribute, such as cellType, here. 
3. Upload to DCA. 
4. Validate (should pass)
5. Submit to synapse. 

**Expected behavior**
The cellType column should be uploaded as stringlisted values/arrays and not as plain strings (see screenshot).

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [X] Critical 🆘 This is pretty critical for us as it is blocking our use of the DCA and we are getting manifests emailed to us... :) 

**Screenshots**
<img width="1722" alt="Screen Shot 2022-05-06 at 2 56 13 PM" src="https://user-images.githubusercontent.com/20408008/167221939-f88f2f4f-09c2-4420-8dcc-9843a8273681.png">

**Comment by ychae** [comment]
@allaway Would you be able to let me know if starting this ticket at our next sprint (Tuesday May 10) would be quick enough or does it need to be addressed sooner?

**Comment by allaway** [comment]
I don't imagine we'll get a ton of use this weekend. If it would be possible and it's simple enough of an issue to fix it on Monday that would be great (recognizing that I'm reporting this at 3pm on a friday PT... 😆 ), but if it's a complicated issue starting work on tuesday makes sense to me!
