### ISSUE TITLE
UML of existing system

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/schematic#711]
**Describe the solution you'd like**
As part of the schematic refactor, create a UML diagram to show the structure and behavior of the system as it currently exists to guide the refactoring work

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by mialy-defelice** [comment]
Link to current system UML: https://lucid.app/lucidchart/c9a6cacc-c017-46a9-8252-fdb9aade2a02/edit?invitationId=inv_924e380f-fc4c-483b-b546-bbb608664a0c&page=0_0#
