### ISSUE TITLE
Review relational database work (NF)

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/schematic#714]
**Describe the solution you'd like**
Knowledge transfer of relational databases 

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by milen-sage** [comment]
@ychae have we captured the NF-related issues on gh?

**Comment by ychae** [comment]
@milen-sage Could you be more specific? Are you referring to the Jira tickets that Ashley created?
