### ISSUE TITLE
Replace local files with API calls for schema visualization 

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#716]
**Is your feature request related to a problem? Please describe.**
Currently, our schema visualization is using local files. We would want to try to replace that part with API calls: 
- Try `d3.request`
- Try ajax

**Describe the solution you'd like**

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**
AC: Quickly figure out if either option works. Just a "Yes" or "No"

**Comment by linglp** [comment]
Helpful resources: 
- https://stackoverflow.com/questions/22784164/what-is-the-best-way-to-update-d3-charts-using-ajax
- https://towardsdatascience.com/full-stack-basics-for-data-scientists-and-other-non-web-developers-part-2-jquery-d3-ajax-and-90f629c6b952

**Comment by linglp** [comment]
Try the following options: 
1) use ajax
```
function FetchCSVContent(url) {
    var result = ""

    const merged_data_2 = $.ajax({
        type: "GET",
        contentType: "application/json; charset=utf-8",
        url: url,
        dataType: 'jsonp',
        async: false,
        data: "{}",
        headers: {
            "Accept": "text/csv",
            "Access-Control-Allow-Origin": "*"
        },
        success: function (data) {
            result = data

        },
        error: function (result) { }
    })

    return result
}
```

Result: if I add `datatype = jsonp`, I would get a warning: ```jquery.min.js:2 Cross-Origin Read Blocking (CORB) blocked cross-origin response http://localhost:3001/v1/visualize/attributes?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2Fmialy-defelice%2Fdata_models%2Fmain%2FHTAN%2FHTAN_schema_v21_10.model.jsonld&callback=jQuery36008180275114882163_1652130022058&{}&_=1652130022059 with MIME type text/csv. See https://www.chromestatus.com/feature/5629709824032768 for more details``` If I do not include `datatype=jsonp`, I would also get an error related to CORS

**Comment by linglp** [comment]
A potential solution: 

If we could turn the project to a nodeJS application, and use express as back-end, we could potentially use their libraries to handle the CORS issue. I have tested it out that the following would work (for route that returns a file path): 

on the client side, we could use the `fetch` function: 
```
        const url = "http://localhost:8000/testing"

        const getRequestWithFetch = () => {
            fetch(url).then(async (response) => {
                const data = await (response.text())
                console.log(data)

                return data
            })
        }

        getRequestWithFetch();
```
on the server-side (deal with the CORS issue): 
```
app.use(cors());

app.get('/testing', function (req, res) {
    var selectedSchema = req.query.schema;

    var requested_url = "http://localhost:3001/v1/manifest/download?input_token=eyJ0eXAiOiJKV1QiLCJraWQiOiJXN05OOldMSlQ6SjVSSzpMN1RMOlQ3TDc6M1ZYNjpKRU9VOjY0NFI6VTNJWDo1S1oyOjdaQ0s6RlBUSCIsImFsZyI6IlJTMjU2In0.eyJhY2Nlc3MiOnsic2NvcGUiOlsidmlldyIsImRvd25sb2FkIiwibW9kaWZ5Il0sIm9pZGNfY2xhaW1zIjp7fX0sInRva2VuX3R5cGUiOiJQRVJTT05BTF9BQ0NFU1NfVE9LRU4iLCJpc3MiOiJodHRwczovL3JlcG8tcHJvZC0zOTQtMC5wcm9kLnNhZ2ViYXNlLm9yZy9hdXRoL3YxIiwiYXVkIjoiMCIsIm5iZiI6MTY0NTQ3NzA4MywiaWF0IjoxNjQ1NDc3MDgzLCJqdGkiOiIxNDcxIiwic3ViIjoiMzQ0MzcwNyJ9.YnIeGuVB97eJQQ2p9HiQHz1RRKnycyizZYdu1s9Xsphn16IcsUlG-qrK6qmZjBS4gE-uzh7s-2UnpTDMc6rHjyrBHuXlXTjtk9S6zmPK6lUhSYDJ4C0PuhqQiKYg5S9yAWYWAP8tkgLHuV27wVlq87PsQRmetfoR3EuV-HPSusfwmylGMjE00YmUUXD878Sfjo7eFVhLVYj98d_nUvd0y_NZcf27-vUPVgexcq9H2CTYgyO1fMdKTKYw-Cm04z24Lho1BSWfmAmX_K0i9vr_IH-jlw0IIb_E8H9al1cGtlecgbXCBsHPBX3vZO_WEzQ5o7QVTTkNfSfxlP8BpzvwNA&asset_view=syn28559058&dataset_id=syn28268700&as_json=false"

    request(requested_url, function (error, response, body) {
        console.log('body', body)
        res.send(body);
    })



})
```

**Comment by ychae** [comment]
@linglp I missed this back in Sprint 8 but I wanted to ask if this ticket can be closed? I see that it's marked as "Done" on the project board.
