### ISSUE TITLE
Validation error when attempting to upload HTAN manifest for testing

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#721]
**Describe the bug**
While @lakikowolfe is testing /manifes/submit endpoint, we tried the following parameter: 
- schema_url = https://raw.githubusercontent.com/ncihtan/data-models/main/HTAN.model.jsonld
- data_type = Demographics
- dataset_id = syn27221721 --basically my testing folder 
- manifest_record_type = None (or "--") 
restrict_rules = FALSE
input_token
manifest.csv that looks just like what exists currently in [here](https://www.synapse.org/#!Synapse:syn30028972). 

Error message: 

jsonschema.exceptions.ValidationError: Manifest could not be validated under provided data model. Validation failed with the following errors: [[2, 'Age Is Obfuscated', "'No' is not one of ['False', 'True', '']", 'No'], [2, 'Race', "'not reported' is not one of ['white', 'Other', 'american indian or alaska native', 'not allowed to collect', 'black or african american', 'asian', 'Not Reported', 'native hawaiian or other pacific islander', 'Unknown']", 'not reported'], [2, 'Wrong schema', "'HTAN Participant ID' is a required property", 'Wrong schema'], [3, 'Age Is Obfuscated', "'No' is not one of ['False', 'True', '']", 'No'], [3, 'Wrong schema', "'HTAN Participant ID' is a required property", 'Wrong schema']]

**To Reproduce**
1. Run the following on terminal: 'python3 run_api.py'
2. Click on 'manifest/submit' endpoint
3. Enter the parameters like above

**Expected behavior**

**Priority** (select one)
- [x] Minor ⬇️
- [ ] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**

**Additional context**

**Comment by linglp** [comment]
Lauren was able to upload with no errors once I updated 'HTAN Participant ID' to be 'HTAN Patient ID' and changed 'Age is Obfuscated' from NO/YES to TRUE/FALSE. Maybe this is caused by the change of HTAN dataset?

**Comment by mialy-defelice** [comment]
@linglp @lakikowolfe it looks like they did change the model. 

```{
            "@id": "bts:AgeIsObfuscated",
            "@type": "rdfs:Class",
            "rdfs:comment": "The age of the patient has been modified for compliance reasons. The actual age differs from what is reported. Other date intervals for this patient may also be modified.",
            "rdfs:label": "AgeIsObfuscated",
            "rdfs:subClassOf": [
                {
                    "@id": "bts:Demographics"
                }
            ],
            "schema:isPartOf": {
                "@id": "http://schema.biothings.io"
            },
            "schema:rangeIncludes": [
                {
                    "@id": "bts:True"
                },
                {
                    "@id": "bts:False"
                }
            ],
            "sms:displayName": "Age Is Obfuscated",
            "sms:required": "sms:false",
            "sms:validationRules": []
        }, ...

{
            "@id": "bts:Component",
            "@type": "rdfs:Class",
            "rdfs:comment": "Category of metadata (e.g. Diagnosis, Biospecimen, scRNA-seq Level 1, etc.); provide the same one for all items/rows.",
            "rdfs:label": "Component",
            "rdfs:subClassOf": [
                {
                    "@id": "schema:Thing"
                }
            ],
            "schema:isPartOf": {
                "@id": "http://schema.biothings.io"
            },
            "sms:displayName": "Component",
            "sms:required": "sms:true",
            "sms:validationRules": []
        },


```

**Comment by linglp** [comment]
Thank you @mialy-defelice !
