### ISSUE TITLE
getAttributeType API endpoint

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic#723]
**Is your feature request related to a problem? Please describe.**
I've noticed that some of the values in the manifests get read in an inconsistent manner. For example some of the same attributes get read by R as in one Character in one dataset vs Double in others. This causes an error when binding them together. 

**Describe the solution you'd like**
I would like an API endpoint that would allow me what the datatype of an attribute is so I can force the columns of the manifest into that type before merging datasets together. Something like:

getAttributeType(atrributeName) -> str
(Where string is one of [string, double, integer, logical]

I'm not sure if project ID or dataset ID should be included, since the schema for a component should be consistent across them.

**How important is this feature?** Select from the options below:
• 🌋 Important

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term 

**Additional context**
I will probably ask for a similar endpoint in the future that will ask for more specifics something like:

getAttributeValues(atrributeName) -> [str]
(Where the array is is a list of allowed values for the given atrribute.)

**Comment by milen-sage** [comment]
@linglp we can chat about this one. I think we may need more business logic on the backend than usual; if so, it may be an item for the next sprint.

**Comment by linglp** [comment]
@ychae Based on my discussion with Milen, Gianna will create the function before I add another API endpoint.

**Comment by milen-sage** [comment]
@ychae I'm trying to find the issue that captures @GiaJordan's work on the validation function @linglp mentioned. It essentially retrieves the validation rule associated with a given attribute; the rule contains the attribute type. 

@GiaJordan if you have the issue handy could you link it here?

**Comment by GiaJordan** [comment]
It was PR #781 to address issue #710. the method is in the [schema explorer](https://github.com/Sage-Bionetworks/schematic/pull/781/files#diff-9e5c6267d30efc40f243c9a0e65aa32334a61d94c69b1aa7552fdacef8657df5)

**Comment by linglp** [comment]
Close this issue for now. After discussion, we figured out that we could not always use validation rules to to infer column types.

**Comment by GiaJordan** [comment]
Adding myself, to assist. Will add

- datetime inference to [`load_df`](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/utils/df_utils.py#L10) function
- will work with @linglp to add endpoint that returns dataframe as JSON object along with column types so that they can be cast in schematic_db

**cc:** @milen-sage @andrewelamb

**Comment by andrewelamb** [comment]
Related [issue.](https://github.com/Sage-Bionetworks/schematic/issues/800)

**Comment by milen-sage** [comment]
We can tackle the validation rule in a follow up sprint.

**Comment by milen-sage** [comment]
@linglp I don't think there was work related to this issue this sprint. I'm moving it to a later sprint - let me know if I missed anything though.

**Comment by linglp** [comment]
@milen-sage @GiaJordan  I forgot to address this issue! Currently we have endpoint `get/datatype/manifest` for getting data types from a manifest on synapse. That endpoint is currently using the function`getDataTypeFromManifest` (check it out [here](https://sage-bionetworks.github.io/schematic/schematic/store/synapse.html#SynapseStorage.getDataTypeFromManifest) ), and `getDataTypeFromManifest` is calling the `load_df` function) Please let me know if we want to expose a different function as an API endpoint.

**Comment by milen-sage** [comment]
@linglp let's check with @andrewelamb if the types returned from this function work as expeced.

The work on #800 should ensure that values for date/time attributes in the manifest are formatted appropriately so that pandas can infer the appropriate datetime object type. So in combination we are likely good, but deferring to @andrewelamb to confirm.

**Comment by andrewelamb** [comment]
Is there a branch to try?

**Comment by GiaJordan** [comment]
@andrewelamb @milen-sage @linglp 
Not yet, I'm in the process of developing the new validation rule for `datetime`s. I had just reached out to @linglp to inquire about the current state of the endpoint, as we may have to change the function the endpoint calls. But that is still TBD and I'll keep you updated

**Comment by GiaJordan** [comment]
endpoint added in #815
