### ISSUE TITLE
getProjectManifests endpoint

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic#731]
**Describe the solution you'd like**
An API endpoint for the schematic getProjectManifests function

**How important is this feature?** Select from the options below:
• 🌋 Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by ychae** [comment]
Thanks for the endpoint @linglp! Closing ticket
