### ISSUE TITLE
Blank values are uploaded as annotations

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#733]
**Describe the bug**
This may be related to #402 / #579 . Blank values in manifests are being uploaded to synapse annotations (see screenshot) even when hideBlanks = T. 

**To Reproduce**
1. Uploade a file to https://www.synapse.org/#!Synapse:syn22410515
2. Go to DCA (https://sagebio.shinyapps.io/NF_data_curator-staging/)
3. Select "Neurofibromatosis Demo" project
4. Select "RNAseq" folder
5. Generate a manifest of any type
6. Minimally annotate with Component, dataType, resourceType
7. Validate, submit
8. View annotations (see screenshot)

**Expected behavior**
when hideBlanks=T (https://github.com/nf-osi/NF_data_curator/blob/104c5cf1d392e897a2cda7ffa5f10bf0d63e1f66/server.R#L447), these annotations should not be uploaded. 

**Priority** (select one)
- [ ] Minor ⬇️
- [X] Major 📢
- [ ] Critical 🆘

**Screenshots**

<img width="326" alt="Screen Shot 2022-05-17 at 12 40 21 PM" src="https://user-images.githubusercontent.com/20408008/168896466-091260ad-1828-47dc-be14-cd3acb292d51.png">

**Additional context**

**Comment by milen-sage** [comment]
It looks like we can have a parameter flag that determines whether blanks are uploaded as annotations or not. In some cases the expectation is that blanks will be uploaded as annotations (e.g empty strings); and some where blank annotations should not be submitted. We can expose that as an option with a backward compatible default (i.e. blank annotations are uploaded).
