### ISSUE TITLE
schematic refactor design: data records input UI classes

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#742]
Create UML diagram capturing design for data records input classes covering

- [ ] existing manifest generation 
- [ ] generic support for other batch- and single-record entry UIs

AC: designs capture all existing manifest generation functionality and contain sufficient information to unblock implementation of dependency classes (i.e. code in other classes knows how to instantiate manifest and form data record input objects and call requisite methods from these classes).

**Comment by linglp** [comment]
I documented the existing functionalities of Manifest Generator here: https://docs.google.com/document/d/1dXG8aQHK8qhEcIjIRvyU5VdvyTDlGUu6JAhWtKyOYqk/edit#
