### ISSUE TITLE
schematic refactor design: data-model schema CRUD classes

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#743]
Create UML diagram capturing design for data-model schema create, read, update and delete (CRUD) functionality. This includes existing

- [x] logic in schema explorer and schema generation classes
- [x] transliteration of tabular schema representation to schematic graph data structure, as well as json-ld serialization
- [x] validation of data-model schema consistency 

AC: designs capture all existing functionality (or explicitly call removed functionality) and contain sufficient information to unblock implementation of dependency classes (i.e. code in other classes knows how to instantiate schema objects and call schema-related CRUD and other schema data-structure exploration methods).

**Comment by ychae** [comment]
Schema explorer

**Comment by mialy-defelice** [comment]
Details of the refactor are [here](https://docs.google.com/document/d/11Mk7ULzmlMgggXs-2bbBTVPigrYJxfRV2Z8nffkAPes/edit#).
