### ISSUE TITLE
schematic refactor design: data-model schema transliteration to JSONSchema

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#744]
Create UML diagram capturing design for transliterating data-model schema to JSONSchema for data-records validation. This includes

- [x] all existing JSONSchema generation-related code

AC: designs capture existing schema generation functionality and contain sufficient information to unblock implementation of dependency classes (i.e. code in other classes knows how to get JSONSchema data structure).

**Comment by ychae** [comment]
Schema generator
