### ISSUE TITLE
Research spike: schematic refactor design for asset store

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#745]
Create UML diagram capturing design for asset store interfaces

- [x] capture existing Synapse asset store functionality
- [ ] provide generic support for future asset stores addition - revisit with @BrunoGrandePhD  given the pythonfs implementation

AC: designs capture existing asset store interface functionality and contain sufficient information to unblock implementation of dependency classes (i.e. code in other classes knows how to instantiate asset store objects and call the various data asset management methods support by asset store interfaces).

**Comment by milen-sage** [comment]
@linglp would be interested in participating in meetings with @BrunoGrandePhD on pythonfs.

**Comment by BrunoGrandePhD** [comment]
I'm excited for this conversation! One discussion topic that I want to raise is the comparison of [`pyfilesystem2`](https://docs.pyfilesystem.org/en/latest/introduction.html) (what `fs-synapse` currently uses) and [`fsspec`](https://filesystem-spec.readthedocs.io/en/latest/), which I wasn't aware of when I initially implemented `fs-synapse`. If you're interested, you can read some of my initial thoughts [here](https://github.com/Sage-Bionetworks/fs-synapse/pull/1#issuecomment-1407757995). Shout-out to Tom for discovering fsspec! 

In any case, if you could share the output/document from the first task here ("capture existing Synapse asset store functionality") ahead of our meeting, that would help me prepare! Thanks!

**Comment by GiaJordan** [comment]
Hi @BrunoGrandePhD, also looking forward to discussing this with you, @linglp and @mialy-defelice! I'll look through your comparisons before we meet. You should have received invites to two lucidchart diagrams: `Schematic UML class diagram` which contains the existing asset store  (and other parts of the codebase) functionality, and `Asset Store Refactor`, where I've been planning the refactor for the asset store itself. We've started incorporating some aspects of the refactor already, namely the TableOperations class and SynapseTable/DB methods.

**Comment by BrunoGrandePhD** [comment]
Thanks for sharing, @GiaJordan!

**Comment by milen-sage** [comment]
I'll catch up on the notes (just requested access). Just a couple of placeholders for discussion as we continue to work on this:
- backward compatibility of the refactored logic
- handling "file" operations that may have large latencies (e.g.   5-10s  <  latency < 120s)
