### ISSUE TITLE
schematic refactor design: RDB classes

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#747]
Create UML diagram capturing design for RDB layer in schematic.

- [x]  determine which of the existing functionality will continue be part of the schematic package and which will live separately
- [x]  provide UML diagram for the functionality that remains in schematic

AC: designs capture RDB functionality that will remain in schematic and contain sufficient information to unblock implementation of REST API dependencies.

**Comment by andrewelamb** [comment]
I've proposed some possible [improvements.](https://docs.google.com/document/d/1ZeNa9Ord6q3KGHxXz3k_eqv7AQFfmsuzGoTvjuZ6DhY/edit)

**Comment by andrewelamb** [comment]
[Example](https://docs.google.com/document/d/11Mk7ULzmlMgggXs-2bbBTVPigrYJxfRV2Z8nffkAPes/edit#)

**Comment by ychae** [comment]
next steps: start a new repo to create and track issues.

**Comment by milen-sage** [comment]
I think we have everything needed to start captured [here](https://docs.google.com/document/d/159EwbR1jJ2uRyVPJVBvZ1JPER4RKU8-Z3JeiKktUGFM/edit?usp=sharing).
