### ISSUE TITLE
Data Model Workshop - Figure out GH issues for data models

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/schematic#754]
Curate a list of 3-5 GitHub issues that would work well for the session and real world use cases.

**Comment by mialy-defelice** [comment]
@ychae could you elaborate on what you are envisioning these GitHub issues being?

**Comment by ychae** [comment]
@mialy-defelice of course! The types of issues for this ticket was to see if we could get a sense of a pattern of where people were getting errors and/or getting stuck and using that to guide the "Common Pitfalls" section of the workshop. Additionally, if there happens to be an open ticket that we could (maybe) work through troubleshooting together at the workshop that would be good to know.

**Comment by mialy-defelice** [comment]
@ychae Ahh okay. Does it perhaps overlap with this issue #755 at all?

I do know there were other issues...but they were schematic issues...

**Comment by ychae** [comment]
This ticket does feel pretty redundant after reading through the comments in that ticket.

**Comment by ychae** [comment]
Closing as duplicate
