### ISSUE TITLE
Data Model Workshop -  Pool github issues that resulted in changes in data models

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/schematic#755]
- [ ] https://github.com/Sage-Bionetworks/schematic/issues/671
- [ ] https://github.com/Sage-Bionetworks/schematic/issues/672

**Comment by mialy-defelice** [comment]
Additionally:

![Image](https://user-images.githubusercontent.com/85905780/171515428-7c42d25f-933b-4c57-926c-5b50ef4f7bdf.png)

![Image](https://user-images.githubusercontent.com/85905780/171515440-b6da2812-aad7-4d65-b602-1b72d7e96f4f.png)

The HTAN model references a prospective 'attribute' in the depends on column that doesn't exist yet.

**Comment by mialy-defelice** [comment]
We should additionally discuss circular dependencies.

**Comment by mialy-defelice** [comment]
https://sagebionetworks.slack.com/archives/C01ANC02U59/p1648231504693789
^ about formatting properly, not using `;`

**Comment by mialy-defelice** [comment]
https://sagebionetworks.slack.com/archives/C01ANC02U59/p1647383880322269

solution that worked:
>Okay just looking without testing my initial guess is you need to take everything out of the IndividualHumanMetadataTemplate1kD dependsOn column that is in the childIndividual and caregiver DependsOncolumns. Like ageAssessment etc… Then to the Person DependsOncolumn you will need to add childIndividual and caregiver. I think that should be enough to set up the conditional dependency correctly, but if it doesnt work, let me know and I’ll figure it out on my end.
