### ISSUE TITLE
Data Model Workshop - Ops

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/schematic#756]
- [x] Workshop date selected (tentative July 21, 2022)
- [ ] [Draft Slide Deck](https://docs.google.com/presentation/d/129pSx58qDm7Y1OQmSSHKDq6tsoD3pW_gDRNXiX2rd0w/edit#slide=id.g4d21a8c2ba_0_11) (Agenda, placeholder slide for each topic, presenters assigned)
- [x] Select audience

**Comment by ychae** [comment]
Audience members: data curators, DCC data liaisons, internal to Sage

**Comment by ychae** [comment]
Continue to work through slide deck in sprint 10

**Comment by milen-sage** [comment]
If the only remaining item for AC here finishing a 1st draft of the slide deck?

**Comment by ychae** [comment]
Yep! That's correct

**Comment by ychae** [comment]
To elaborate further, I think we could consider the first draft to be the items discussed in the [Workshop Planning Doc](https://docs.google.com/document/d/1LSM0b-xxPYL-Lxsly-FYFAjVwvktMW8EUyb44ew4fZA/edit#heading=h.ujbkqs4nasi4) translated into a slide outline would suffice

**Comment by mialy-defelice** [comment]
@ychae Added a whole bunch of slides about building the model. Can try to add a simpler model instead, but that will be done if I get more time.

**Comment by milen-sage** [comment]
I left some minor comments in the deck draft. Thanks @mialy-defelice!

**Comment by GiaJordan** [comment]
Finished the slides we discussed in the 6/22 workshop meeting, first draft is complete and can be reviewed
