### ISSUE TITLE
schematic NLM grant planning

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#758]
We can keep working on this [doc](https://docs.google.com/document/d/1_c2RR7gVgDH41rC-CoZVV6DmAz2bVfKNgFwnDhwGZHw/edit#) async for this sprint. Thanks for starting it @mialy-defelice!

AC: outline steps required to submit grant; focus on steps around kickstarting content. Have a list of collaborators w/in Sage that we would like to approach.

**Comment by ychae** [comment]
Plan to go over a bit of what the grant is in a Show & Tell

**Comment by milen-sage** [comment]
After discussion with LT, we don't need to apply for this grant; the work is supported differently.
