### ISSUE TITLE
HTAN staging data curator app crashes during Google sheet link generation

### ISSUE THREAD

**Issue by adamjtaylor** [Sage-Bionetworks/schematic#763]
**Describe the bug**

The staging instance of the [HTAN Data Curator App](https://sagebio.shinyapps.io/HTAN-data-curator-staging/) crashes with the error "Disconnected from the server" during the "Generating link" phase.

This bug is not present in the [production instance](https://sagebio.shinyapps.io/HTAN-data-curator/)

**To Reproduce**
1. Go to staging instance of the [HTAN Data Curator App](https://sagebio.shinyapps.io/HTAN-data-curator-staging/)
2. Step through to 'Generating link' stage
4. After waiting ~1 min error "Disconnected from the server" appears faintly at bottom left faintly visibly under slightly transparent "Generating link" screen.

**Expected behavior**

App does not crash during link generation. Link to google spreadsheet offered and functional.

**Priority** (select one)
- [x] Critical 🆘

**Screenshots**

Loom screen recording. Note video has been trimmed at various loading pages to get under 5 min limit. Covers reproduction of error in staging and the absence of the error in prod.

[![Loom video](https://cdn.loom.com/sessions/thumbnails/cab72e08f7a5469c9471ab49da6928dc-with-play.gif)](https://www.loom.com/share/cab72e08f7a5469c9471ab49da6928dc)

**Desktop (if applicable, please complete the following information):**
 - OS: macOS Monterey 12.3.1 on M1 Macbook Pro
  - Browser: Edge Version 101.0.1210.39 (Official build) (arm64)

**Additional context**

Possibly seems to be intermittent. I have successfully had the link generate.

**Comment by milen-sage** [comment]
AC: bug is resolved.

**Comment by GiaJordan** [comment]
@ychae 
`Bulk RNAseq level1` successfully generated from command line without errors, will now be tested by @afwillia with the DCA

**Comment by afwillia** [comment]
@ychae @GiaJordan it works successfully on https://sagebio.shinyapps.io/data_curator-staging/ for `HTAN BU` `archive` `scRNA-seq Level 1`

**Comment by GiaJordan** [comment]
@afwillia Good to hear! Can you also try it with `Biospecimen` please?

**Comment by afwillia** [comment]
@GiaJordan yes, it works for that as well!

**Comment by GiaJordan** [comment]
@afwillia perfect thanks!

**Comment by GiaJordan** [comment]
Resolved as per @afwillia 
cc @ychae
