### ISSUE TITLE
RDB Jupyter Notebook Crashes with too many messages.

### ISSUE THREAD

**Issue by mialy-defelice** [Sage-Bionetworks/schematic#769]
**Describe the bug**
The RDB Jupyter notebook sends a lot of messages when uploading to the server. Can cause the notebook to shutdown. See if changing the sqlalchemy logging level will help solve this problem. If not document to reset the max messages that can be sent.

`jupyter notebook --NotebookApp.iopub_msg_rate_limit=1.0e10`

**Priority** (select one)
- [x ] Minor ⬇️
- [ ] Major 📢
- [ ] Critical 🆘

**Desktop (if applicable, please complete the following information):**
 -was an issue on Andrews Ubuntu installation, not my MacOSX install.

**Additional context**

**Comment by milen-sage** [comment]
AC: resolve bug on Ubuntu.

**Comment by ychae** [comment]
Closing after conversations with @milen-sage. Will continue to maintain and revisit the jupyter notebooks after the refactor.
