### ISSUE TITLE
Great Expectations OMOP hackathon planning

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#770]
Review [Data Quality Dashboard functionality](https://ohdsi.github.io/DataQualityDashboard/articles/CheckTypeDescriptions) to compare with existing [Great Expectations expectations](https://greatexpectations.io/expectations/) to plan and set goals for a hackathon with Superconductive to create a suite of expectations to validate according to the OMOP CDM.
AC:
Tasks/plan for a hackathon (current draft of plans lives in `FAIR Data Workstream Drive/Stakeholders/Superconductive`)
**If possible, send plan to Ben by Friday, 6/10**

**Comment by GiaJordan** [comment]
cc @ychae @milen-sage

**Comment by ychae** [comment]
Forward plan to @trberg for review after final read-through
