### ISSUE TITLE
Look into react flow 

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#772]
**Is your feature request related to a problem? Please describe.**
Check out React flow and Cytoscape

**Describe the solution you'd like**

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by milen-sage** [comment]
@linglp no need to look into cytoscape; react-flow would be sufficient.

AC: has researched license of react-flow (i.e. can code be modified and shared; is it a reasonable open source license); has determined whether collapse/expand functionality is applicable to DAGs and not just trees.

**Comment by linglp** [comment]
I cloned their GitHub repos and can run all their examples locally. 

License: MIT 


Advantages of using React flow: 

Interesting features: 
Edit node: 
      - Change shape (but if we change the default shape, we will have to redesign placement of text and nodes)
      - Allow user to change color of node: https://reactflow.dev/docs/examples/nodes/update-node/
      - Edit text of the node
      https://reactflow.dev/docs/guides/custom-nodes/
      - Add an additional node 

You seem to be able to connect a child with multiple parents. The code seems to only care about the “source” and the “target”. As long as these two values are specified, you could connect any nodes. 
Validation: Allow users to connect a certain node https://reactflow.dev/docs/examples/interaction/validation/
Save nodes: https://reactflow.dev/docs/examples/interaction/save-and-restore/


Disadvantages:
- Links in original Observable designs are structured by using the SVG path element in D3 (something like [this](http://using-d3js.com/05_01_paths.html)) If we want to replicate the links in observable, we can’t just use the default links (see types of links provided by React flow [here](https://reactflow.dev/docs/api/edges/edge-types/)) provided by React flow. They do offer ways to [custom edges](https://reactflow.dev/docs/api/edges/custom-edges/), and the one that could possibly take in custom path is “LabelBgStyle” attribute. This would require more digging to figure out if that could work
- Also it seems hard to separate nodes and text. For example, if we want to decrease the size of nodes and put text in a separate position (just like in Observable), this seems difficult. 
- Still not sure if collapse and expansion for tangled trees is possible on React flow. There’s no trial license for React Flow Pro. I have sent a message to the dev team and hopefully they could get back to us

**Comment by milen-sage** [comment]
@linglp this is an awesome summary! Let's see if they reply on the collapse/expand question. Meanwhile let's keep pushing on the in-house schema viz #715.

**Comment by linglp** [comment]
@milen-sage I have sent them a working example [here](schematic manifest --config ../schematic_package_docs/config.yml get -s -oauth) and let them know our expectation in terms of collapsing and expansion. They said that they will take some time to take a look. I will let you know once they give any updates.
