### ISSUE TITLE
Rule Combination: Initial

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#775]
**Is your feature request related to a problem? Please describe.**
Basic sets of rules that can be used in combination with each other

**Describe the solution you'd like**
MVP of simple pairs of rules (TBD) that can be used for validation of a single attribute

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by GiaJordan** [comment]
@ychae for rule combo epic

**Comment by GiaJordan** [comment]
First Round of new rule pairs: 

- `int::inRange`
- `float::inRange`
- `num::inRange`
- `protectAges::inRange`

Rule pairs will be added or removed as reprioritized based on user feedback and feasibility

**Comment by ychae** [comment]
hi @GiaJordan I see that this is marked Done on the project board, can this ticket be closed?
