### ISSUE TITLE
Refactor list validation in Great Expectations

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#779]
**Is your feature request related to a problem? Please describe.**
Refactor list validation in great expectations, and allow for list validation to be used in combination with other rules ie, `int`/`float`/`num` with regex

**Describe the solution you'd like**
see above

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months
• Long-term - 6 months - 1 year

**Additional context**

**Comment by GiaJordan** [comment]
@ychae for rule combo epic

**Comment by GiaJordan** [comment]
@milen-sage will likely be easier to implement now due to relevant additions or changes to the codebase

**Comment by milen-sage** [comment]
@GiaJordan I tentatively have added it to next sprint 15.
