### ISSUE TITLE
In JIRA: Combinations of rules disjunction 

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#780]
**Is your feature request related to a problem? Please describe.**
Currently combination of rules operate on a conjunction of rules (rule1 and rule2 and ... ruleN need to be satisfied by data). We would like to support rule disjunction (rule1 or rule2 or ... ruleN need to be satisfied by data).

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Comment by MiekoHash** [comment]
Moved to JIRA https://sagebionetworks.jira.com/browse/FDS-79
