### ISSUE TITLE
Retro to review #757 - stream line comms

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/schematic#784]
AC: schedule a retrospective to review the conversation in #757 and determine best way to disseminate information to other stakeholders.

**Comment by milen-sage** [comment]
@ychae prepping the retro is sprint 11 or 12, probably not 10 based on our discussion?

**Comment by ychae** [comment]
@milen-sage scheduled for Wednesday July 13 (Sprint 12)
