### ISSUE TITLE
Add support to import date entries as type `datetime`

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic#800]
**Describe the solution you'd like**
It would be nice to have either date or datetimes as a possible validation rule. This would allow ProjectLive2 to plot these types of attributes as date instead of strings as they are currently. They should have a consistent format like 01012021 (1/1/21).

Also, provide a list of possible options on what constitutes a date (e.g. there are values that are not dates but by default some parsing libraries handle them as dates and we want to avoid that). 

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by GiaJordan** [comment]
Purpose is for type endpoint therefor a full validation rule is not necessary at this time, just functionality to import date strings into date specific types so that they can be detected by the api endpoint
