### ISSUE TITLE
Specify order of valid values in manifest (e.g. most common/recently used)

### ISSUE THREAD

**Issue by aclayton555** [Sage-Bionetworks/schematic#801]
Filing this issue on behalf of Milen following discussion on a CSBC/PS-ON stakeholder call on June 27, 2022. Meeting notes: https://docs.google.com/document/d/1To9uR_2krLPAHonXnd3EWZaK3_V8m0hdCs6s1tuAL1Q/edit?usp=sharing

**Describe the solution you'd like**
Similar to being able to specify the order of valid values alphabetically, it could be helpful to have a data curator be able to specify the order of valid values to be listed in the schema, then have the google sheet respect that order. As an example, this could allow valid values that appear to be most commonly used by a community to be ordered first in the drop down list, among a long list of valid values.

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Long-term - 6 months - 1 year

**Comment by AmyHeiser** [comment]
@mialy-defelice does this fit in with your refactor?  If so I will like to this MC2 ticket, if not I can create a new one.   https://sagebionetworks.jira.com/browse/CPO-210

**Comment by mialy-defelice** [comment]
@AmyHeiser I think this would be part of the manifest generator refactor, not the schemas refactor. @linglp has been planning the manifest generator refactor, idk if she already captured this user story there. If its needed sooner we could just issue a new ticket.
