### ISSUE TITLE
Manifests give validation errors for list attributes

### ISSUE THREAD

**Issue by brynnz22** [Sage-Bionetworks/schematic#806]
**Describe the bug**
When attempting to fill out manifests generated by Schematic, the Google Sheet will give an error that says something like, "The data you entered in cell G101 violates the data validation rules set on this cell." The only way to list values is to copy and paste the desired list of values over from another spreadsheet into the manifest. See [this example manifest](https://docs.google.com/spreadsheets/d/1taZyB8lJlZjAzddDaB3yWb_3TNx5BtM7XZqeCLjyGC0/edit#gid=0) (look at columns such as `Grant Theme Name`, `Grant Institution Name`, `Grant Institution Alias`, `Grant Investigator`, etc.

**To Reproduce**
1. Go to the [example manifest](https://docs.google.com/spreadsheets/d/1taZyB8lJlZjAzddDaB3yWb_3TNx5BtM7XZqeCLjyGC0/edit#gid=0)
2. Try to write a list of values in one of the columns that take lists and see error.

**Expected behavior**
A user will easily be able to include comma separated lists in columns that accept lists. 

**Priority** (select one)
- [ ] Minor ⬇️
- [x ] Major 📢
- [ ] Critical 🆘

**Screenshots**
<img width="1296" alt="Screen Shot 2022-07-01 at 3 57 46 PM" src="https://user-images.githubusercontent.com/46435419/176975956-b5707339-2442-4a3d-8570-7cc19fbf69ff.png">

**Desktop (if applicable, please complete the following information):**
 - iOS
 - Chrome
 - Version ?

**Additional context**
The [CSBC data model](https://docs.google.com/spreadsheets/d/1hbG1vdi8a0gc-6psn5VgsBgyMl6IOhDSbHWDuC_8EXo/edit#gid=59750547) that informs the attached example manifest can be viewed.

**Comment by ychae** [comment]
Can use the first sheet of the CSBC data model google sheet

**Comment by linglp** [comment]
@brynnz22  Could you test it out again?  After our recent bug fixes (#847  and #840), this issue should have been resolved. From my end, I also tested it out by generating an empty manifest for GrantView (see here: https://docs.google.com/spreadsheets/d/1KTrMo08XmqkiNAStEJpK2VXDu-N6qevHVrxaAECdjZo/edit#gid=0), and I could enter multiple values for columns that accept list, such as Grant Institution Name. 

Please note that the little red warning "Invalid: Input must fall within specified range" is a problem with google sheet that we can't fix on our end.

**Comment by brynnz22** [comment]
@linglp yes it works! Thank you!

**Comment by linglp** [comment]
@brynnz22 thanks for testing!
