### ISSUE TITLE
RDB NaN issues

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic#808]
**Describe the bug**
The way the database is being built at the moment, ‘NaN’ strings are getting introduced to various tables. Apparently these get converted to NULL when ingressed into synapse, so it’s not always apparent if the query to make those tables are simple. The problem right now is that this is happening to tables that are foreign keys. When two tables are joined, and the key column in one of these have these ‘NaN’ values, and the join is an INNER join, these rows will be propagated to the new table. When both tables have the ‘NaN’ values in the key column, there will be a cartesian product number of new rows that shouldn’t be included. 

**Priority** (select one)
- [ ] Minor ⬇️

**Comment by mialy-defelice** [comment]
@andrewelamb is this still relevant?
