### ISSUE TITLE
Release to PYPI

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#809]
**Is your feature request related to a problem? Please describe.**
Release develop branch to PYPI

**Describe the solution you'd like**

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by linglp** [comment]
Release was done. Documentation could be found here: https://github.com/Sage-Bionetworks/schematic/pull/817

**Comment by ychae** [comment]
@linglp congrats on the release! If there's no more remaining work for this ticket, please feel free to close 😄

**Comment by linglp** [comment]
@ychae thanks Yoree! Let me close this one for now
