### ISSUE TITLE
Manifest validates yet can't submit due to bad lookup in schema explorer / networkx call

### ISSUE THREAD

**Issue by anngvu** [Sage-Bionetworks/schematic#810]
**Describe the bug**
Interestingly, our test manifest validates just fine, but at submit time there is some additional rules lookup that fails (?). 

**To Reproduce**
:point_right: _Steps and stack trace here:_ https://github.com/nf-osi/nf-metadata-dictionary/pull/172

**Expected behavior**
Should be able to submit...

**Priority** (select one)
- [ ] Minor ⬇️
- [X] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**

**Additional context**

**Comment by ychae** [comment]
@anngvu can you test with [removing BioThings](https://github.com/Sage-Bionetworks/schematic/issues/708#issuecomment-1191541035) and let us know if that resolves the issue?

**Comment by GiaJordan** [comment]
Per @brynnz22 it doesn't seem like [removing BioThings](https://github.com/Sage-Bionetworks/schematic/issues/708#issuecomment-1212553773) resolved the `KeyError`. 
It seems there have been multiple changes submitted to the data model and manifest over the course of debugging. If either @brynnz22, @anngvu, or @allaway have the latest version of the data model and manifest that have been iterated on throughout this process, could you please send a copy my way? Thank you!
**cc:** @milen-sage

**Comment by milen-sage** [comment]
@GiaJordan sorry for the delay here. If you haven't gotten the latest json-ld schema @brynnz22 sent me, I just forwarded it to you.

**Comment by milen-sage** [comment]
Not to hijack the issue, but @brynnz22 do you have a repo for the MC2/CSBC data models? If not, could you start one in a MC2 or a CSBC github org? That way you can just post url's to the data model on github and avoid the upload problem.

**Comment by brynnz22** [comment]
Yes we do have a github for the data models: https://github.com/mc2-center/data-models

**Comment by milen-sage** [comment]
@brynnz22 great! Yes, for this issue we're good and we got the schema on our end. Going forward posting a url to a schema in your data models gh repo would work best. Could be a separate branch if the schema of interest is a different version than the one that's in the main branch.

**Comment by brynnz22** [comment]
@milen-sage Sounds good! I'll do this going forward :)

**Comment by GiaJordan** [comment]
Partially addressed in #903, work will continue to determine cause of error and relation to base schema used
@brynnz22 @anngvu
