### ISSUE TITLE
List like validation not working as expected

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#819]
**Describe the bug**
There are two list validation issues we are encountering with the latest version of develop. With a 'list like' validation for modelSystemName and cellType, we get the following errors when we supply valid values from this test manifest:

`
 [[2, 'cellType', "['schwann'] is not one of ['GABAergic neurons', 'NeuN+', 'CNON', 'astrocytes', 'NeuN-', 'iPSC-derived telencephalic organoids', 'iPSC-derived astrocytes', 'cultured Muller glia', 'iPSC', 'epithelial-like', 'iPSC-derived neuronal progenitor cell', 'macrophages', 'round', 'Meningioma', 'CD8+ T-Cells', 'iPSC-derived neuron', 'Teratoma', 'Schwann cell precursor', 'oligodendrocyte', 'schwann', 'lymphoblast', 'arachnoid', 'Embryonic stem cells', 'SH-SY5Y', 'epithelial', 'CD138+', 'fibroblast', 'microg", ['schwann']], [2, 'modelSystemName', "[''] is not one of ['hTERT NF1 ipn02.3 2λ', 'JHU 2-002-PDX', 'STS-26T', 'cNF98.4d', 'KCL024', '90-8', 'cNF97.2a', 'hTERT NF1 ipn06.2 A', 'B6.129S2-Nf1tm1Tyj/J', 'sNF94.3', 'hTERT NF1 ipNF04.4', 'cNF98.4c', 'human foreskin fibroblasts', 'NCC-MPNST2-C1', 'Ben-Men-1', 'hTERT NF1 ipNF05.5', 'icNF04.9a', 'sc93.1', 'B6;129S2-Trp53tm1Tyj Nf1tm1Tyj/J', 'hTERT NF1 ipNF95.6', 'S462', 'GM11602', 'SC4 [Mouse schwannoma]', 'Fb93.1', 'NCC-MPNST3-X2-C1', 'icNF97.2a', 'hiPSC', 'cNF97.2b', 'S520', 'SZ-NF1', 'icN", ['']], [3, 'cellType', "['schwann'] is not one of ['GABAergic neurons', 'NeuN+', 'CNON', 'astrocytes', 'NeuN-', 'iPSC-derived telencephalic organoids', 'iPSC-derived astrocytes', 'cultured Muller glia', 'iPSC', 'epithelial-like', 'iPSC-derived neuronal progenitor cell', 'macrophages', 'round', 'Meningioma', 'CD8+ T-Cells', 'iPSC-derived neuron', 'Teratoma', 'Schwann cell precursor', 'oligodendrocyte', 'schwann', 'lymphoblast', 'arachnoid', 'Embryonic stem cells', 'SH-SY5Y', 'epithelial', 'CD138+', 'fibroblast', 'microg", ['schwann']], [3, 'modelSystemName', "[''] is not one of ['hTERT NF1 ipn02.3 2λ', 'JHU 2-002-PDX', 'STS-26T', 'cNF98.4d', 'KCL024', '90-8', 'cNF97.2a', 'hTERT NF1 ipn06.2 A', 'B6.129S2-Nf1tm1Tyj/J', 'sNF94.3', 'hTERT NF1 ipNF04.4', 'cNF98.4c', 'human foreskin fibroblasts', 'NCC-MPNST2-C1', 'Ben-Men-1', 'hTERT NF1 ipNF05.5', 'icNF04.9a', 'sc93.1', 'B6;129S2-Trp53tm1Tyj Nf1tm1Tyj/J', 'hTERT NF1 ipNF95.6', 'S462', 'GM11602', 'SC4 [Mouse schwannoma]', 'Fb93.1', 'NCC-MPNST3-X2-C1', 'icNF97.2a', 'hiPSC', 'cNF97.2b', 'S520', 'SZ-NF1', 'icN", ['']], [4, 'cellType', "['schwann'] is not one of ['GABAergic neurons', 'NeuN+', 'CNON', 'astrocytes', 'NeuN-', 'iPSC-derived telencephalic organoids', 'iPSC-derived astrocytes', 'cultured Muller glia', 'iPSC', 'epithelial-like', 'iPSC-derived neuronal progenitor cell', 'macrophages', 'round', 'Meningioma', 'CD8+ T-Cells', 'iPSC-derived neuron', 'Teratoma', 'Schwann cell precursor', 'oligodendrocyte', 'schwann', 'lymphoblast', 'arachnoid', 'Embryonic stem cells', 'SH-SY5Y', 'epithelial', 'CD138+', 'fibroblast', 'microg", ['schwann']], [4, 'modelSystemName', "[''] is not one of ['hTERT NF1 ipn02.3 2λ', 'JHU 2-002-PDX', 'STS-26T', 'cNF98.4d', 'KCL024', '90-8', 'cNF97.2a', 'hTERT NF1 ipn06.2 A', 'B6.129S2-Nf1tm1Tyj/J', 'sNF94.3', 'hTERT NF1 ipNF04.4', 'cNF98.4c', 'human foreskin fibroblasts', 'NCC-MPNST2-C1', 'Ben-Men-1', 'hTERT NF1 ipNF05.5', 'icNF04.9a', 'sc93.1', 'B6;129S2-Trp53tm1Tyj Nf1tm1Tyj/J', 'hTERT NF1 ipNF95.6', 'S462', 'GM11602', 'SC4 [Mouse schwannoma]', 'Fb93.1', 'NCC-MPNST3-X2-C1', 'icNF97.2a', 'hiPSC', 'cNF97.2b', 'S520', 'SZ-NF1', 'icN", ['']], [5, 'cellType', "['schwann'] is not one of ['GABAergic neurons', 'NeuN+', 'CNON', 'astrocytes', 'NeuN-', 'iPSC-derived telencephalic organoids', 'iPSC-derived astrocytes', 'cultured Muller glia', 'iPSC', 'epithelial-like', 'iPSC-derived neuronal progenitor cell', 'macrophages', 'round', 'Meningioma', 'CD8+ T-Cells', 'iPSC-derived neuron', 'Teratoma', 'Schwann cell precursor', 'oligodendrocyte', 'schwann', 'lymphoblast', 'arachnoid', 'Embryonic stem cells', 'SH-SY5Y', 'epithelial', 'CD138+', 'fibroblast', 'microg", ['schwann']], [5, 'modelSystemName', "[''] is not one of ['hTERT NF1 ipn02.3 2λ', 'JHU 2-002-PDX', 'STS-26T', 'cNF98.4d', 'KCL024', '90-8', 'cNF97.2a', 'hTERT NF1 ipn06.2 A', 'B6.129S2-Nf1tm1Tyj/J', 'sNF94.3', 'hTERT NF1 ipNF04.4', 'cNF98.4c', 'human foreskin fibroblasts', 'NCC-MPNST2-C1', 'Ben-Men-1', 'hTERT NF1 ipNF05.5', 'icNF04.9a', 'sc93.1', 'B6;129S2-Trp53tm1Tyj Nf1tm1Tyj/J', 'hTERT NF1 ipNF95.6', 'S462', 'GM11602', 'SC4 [Mouse schwannoma]', 'Fb93.1', 'NCC-MPNST3-X2-C1', 'icNF97.2a', 'hiPSC', 'cNF97.2b', 'S520', 'SZ-NF1', 'icN", ['']], [6, 'cellType', "['schwann'] is not one of ['GABAergic neurons', 'NeuN+', 'CNON', 'astrocytes', 'NeuN-', 'iPSC-derived telencephalic organoids', 'iPSC-derived astrocytes', 'cultured Muller glia', 'iPSC', 'epithelial-like', 'iPSC-derived neuronal progenitor cell', 'macrophages', 'round', 'Meningioma', 'CD8+ T-Cells', 'iPSC-derived neuron', 'Teratoma', 'Schwann cell precursor', 'oligodendrocyte', 'schwann', 'lymphoblast', 'arachnoid', 'Embryonic stem cells', 'SH-SY5Y', 'epithelial', 'CD138+', 'fibroblast', 'microg", ['schwann']], [6, 'modelSystemName', "[''] is not one of ['hTERT NF1 ipn02.3 2λ', 'JHU 2-002-PDX', 'STS-26T', 'cNF98.4d', 'KCL024', '90-8', 'cNF97.2a', 'hTERT NF1 ipn06.2 A', 'B6.129S2-Nf1tm1Tyj/J', 'sNF94.3', 'hTERT NF1 ipNF04.4', 'cNF98.4c', 'human foreskin fibroblasts', 'NCC-MPNST2-C1', 'Ben-Men-1', 'hTERT NF1 ipNF05.5', 'icNF04.9a', 'sc93.1', 'B6;129S2-Trp53tm1Tyj Nf1tm1Tyj/J', 'hTERT NF1 ipNF95.6', 'S462', 'GM11602', 'SC4 [Mouse schwannoma]', 'Fb93.1', 'NCC-MPNST3-X2-C1', 'icNF97.2a', 'hiPSC', 'cNF97.2b', 'S520', 'SZ-NF1', 'icN", ['']]]
`

**To Reproduce**
Install schematic (c8484d1)
Get nf.jsonld with list like validation(https://github.com/nf-osi/nf-metadata-dictionary/blob/d6e480e3e8b7700fec016cd4b28c08ada75241b1/NF.jsonld) 
Validate this test manifest (https://github.com/nf-osi/nf-metadata-dictionary/blob/d6e480e3e8b7700fec016cd4b28c08ada75241b1/tests/GenomicsAssayTemplate_1.csv) with -dt GenomicsAssayTemplate 

**Expected behavior**
The blank values in a list-like column should pass validation. 
The value "schwann"  in a list-like column should pass validation. 

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [x] Critical 🆘

**Additional context**
Find the full test job here: https://github.com/nf-osi/nf-metadata-dictionary/runs/7286909637?check_suite_focus=true and click on "test validate" 

cc @anngvu

**Comment by GiaJordan** [comment]
@ychae Cause of problem diagnosed, working on general solution to prevent similar issue with future changes

**Comment by GiaJordan** [comment]
@ychae the solution is in place in the parts of code that were causing this error to surface, and the `list like` validation rule now works as expected.
Will now go through and update the other parts of the code that would use the general solution implemented above
