### ISSUE TITLE
Character string "NA" being converted to blank

### ISSUE THREAD

**Issue by lopierra** [Sage-Bionetworks/schematic#821]
**Describe the bug**
When I upload a filled metadata template to the Data Curator App, the character string "NA" is converted to blank. I would like to preserve the "NA" string so that empty columns will be uploaded to Synapse as String instead of Double (to match with String columns from other datasets).

This is currently preventing me from building a proper File View in Synapse. Eg. in the attached screenshot, `DiagnosisMONDO`, `DiagnosisSource`, and `DiagnosisType` are of type String in datasets that have data in those columns, but of type Double in datasets where those columns are empty (even when I fill them with "NA" strings), so I get a "Duplicate Fields" error.

I have worked around this by substituting "NA" with "---" and deleting the "duplicate" columns from the File View schema, but it is not a sustainable long-term solution.

@BrunoGrandePhD found that pandas (which is used in schematic) converts "NA" to NaN by default and is the likely cause of this bug.

**To Reproduce**
not sure how to provide a reprex for this (using the INCLUDE Data Curator App) but I can give a demo

**Expected behavior**
The string "NA" should be preserved as a string "NA" when the template is uploaded to DCA. 

**Priority** (select one)
- [ ] Minor ⬇️
- [x] Major 📢
- [ ] Critical 🆘

**Screenshots**
![image](https://user-images.githubusercontent.com/34149564/179317422-ed9d63f4-be06-41a9-a1ee-19e9a9551eab.png)

**Desktop (if applicable, please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
I can see the blanks that were previously "NA" in the DCA preview, so it seems to be a schematic/DCA issue and not Synapse.

**Comment by lopierra** [comment]
Possibly related to #808 ?

**Comment by GiaJordan** [comment]
@lopierra There are a number of strings that pandas interprets as `NULL` whenever CSVs are imported as dataframes. To prevent this conversion, could you please specify your values as `Not Applicable` as opposed to `NA`?

Thanks!

**Comment by lopierra** [comment]
Thanks @GiaJordan!

**Comment by GiaJordan** [comment]
> @/GiaJordan @/milen-sage On further reflection, I think I will replace NA with "Blank" instead of "Not Applicable". Most of the NAs in our data are generated when R replaces blank spaces with NA. "Not Applicable" sometimes has other specific meanings/uses that I don't want to inject incorrectly. Just FYI. Thanks!

@lopierra You're welcome! and that's fine. For schematic, you'd just need to avoid the strings Pandas interprets as NA to avoid this issue in the future
From the [read_csv doc](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html):
> By default the following values are interpreted as NaN: ‘’, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘<NA>’, ‘N/A’, ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’.
