### ISSUE TITLE
Capture schematic schema refactor work in issues

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#824]
AC: capture work related to this [milestone](https://github.com/Sage-Bionetworks/schematic/milestone/30) in a set of issues.

A subset of these are already started as stubs: #825, #826, #827, #828, but there are a few more. Let's flesh out some of the specs laid out in the refactor [notes ](https://docs.google.com/document/d/11Mk7ULzmlMgggXs-2bbBTVPigrYJxfRV2Z8nffkAPes/edit?pli=1#heading=h.7k0ywqekq78g) in the respective issues.

#825 - #828 would be a good start for sprint 13.

**Comment by mialy-defelice** [comment]
- [ ] 825
- [ ] 826
- [ ] 827
- [ ] 828
