### ISSUE TITLE
Implement new data mode graph node and edge classes

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#825]

**Comment by mialy-defelice** [comment]
Create a skeleton for the following:

- [ ] schema/data_model_nodes.py
The point of these classes is to take in relationships and attribute data to create the nodes and edges for the network graph.
- [ ] Class DataModelNodes:
    - [ ] init
    - [ ] generate_node():
    - [ ] edit_node()

- [ ] schema/data_model_edges.py
- [ ] Class DataModelEdges:
    - [ ] init
    - [ ] generate_edge()
    - [ ] edit_edge()

**Comment by mialy-defelice** [comment]
Created skeleton classes.
