### ISSUE TITLE
Implement new JSON-LD object, property and class classes

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#826]

**Comment by mialy-defelice** [comment]
Create a skeleton for the following:

- [ ] Create `create_json_ld.py`
- [ ] Add `Class JSONLD_object`
    - [ ] [Decorator class design](https://refactoring.guru/design-patterns/decorator)
    - [ ]   __init_()
    - [ ] self.to_template() -> returns a dictionary or a string thats a JSON-LD object
    - [ ] Returns jsonld_class_template or jsonld_property_template
    - [ ] Call on JSONLD_project and JSONLD_class
- [ ] Add `Class JSONLD_property`
    - [ ] [Decorator class design](https://refactoring.guru/design-patterns/decorator)
    - [ ] __init_()
    - [ ] self.to_template() 
    - [ ] explore_property: 
    - [ ] edit_property(self, property_info)
- [ ] Add `Class JSONLD_class` 
    - [ ] [Decorator class design](https://refactoring.guru/design-patterns/decorator)
    - [ ] __init_()
    - [ ] self.to_template() 
    - [ ] explore_class: 
    - [ ] edit_class(self, property_info)

**Comment by mialy-defelice** [comment]
Created skeleton for classes
