### ISSUE TITLE
Implement data model parser class

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#827]

**Comment by mialy-defelice** [comment]
Create skeleton for the following:

- [ ] schema/data_model_parser.py

- [ ] Class DataModelParser:
Get the relationships and attributes from the user submitted CSV or JSONLD.
    - [ ] init():
    - [ ] get_model_type():
    - [ ] parse_model():

- [ ] Class DataModelCSVParser:
Take and input csv and gather all relationships and their attributes
Return in a form that can then be used to load into networkx graph: https://networkx.org/documentation/latest/tutorial.html
A lot of the general logic exists in the current df_parser/create_nx_schema_object/, but its loaded in a way that is specific to JSONLD… decouple this logic.
Will mean that many of the current helper functions will be swapped out.
Return attributes and relationships

- [ ] Class DataModelJSONLDParser:
Get JSONLD and gather all relationships and attributes.
A lot of this already exists in utils/schema_utils.py but decouple from networks for now.

**Comment by mialy-defelice** [comment]
Created skeleton files and classes.
