### ISSUE TITLE
Implement data model graph class

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#828]

**Comment by mialy-defelice** [comment]
Create a skeleton for the following:
- [ ] schema/data_model_graph.py
- [ ] Class DataModelGraph:
    - [ ] Following a [singleton class design](https://refactoring.guru/design-patterns/singleton)
    - [ ] init():
    - [ ] generate_data_model_graph()
    - [ ] convert data_model_parser output into a networkx schema.
    - [ ] Analogous to function that converts JSONLD to networkx schema (load_schema_into_networkx)
    - [ ] Iteratively load nodes and edges into networkx by calling on node and edge classes.
    - [ ] Add attributes to nodes analogous to previous function.
    - [ ] Returns data_model_graph

- [ ] Class DataModelGraphExplorer:
Add all explorer functions

**Comment by mialy-defelice** [comment]
Created skeleton classes.
