### ISSUE TITLE
Create new endpoints for data viz

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#833]
**Is your feature request related to a problem? Please describe.**
Currently, I have to hard-coded some data and assume each node knows its children in the code. In addition, I also have to loop through the nodes and figure out the direct children. It would be better if the back-end could handle this part. 

This issue is about creating the following endpoints: 

- [x] get_viz_nodes_children 

- [x] get_viz_nodes_direct_children

For this two endpoints, if possible, I would like the return to be a json that looks something like: 

```
[[{"id": "Demographics", "directChildren":[], "Children":[]}, {"id": "FamilyHistory", "directChildren":[], "Children":[]}, {"id": "Exposure", "directChildren":[], "Children":[]}]]
```

Other notes: 

**I am not sure if it would be easier to add those information directly on endpoint `/visualize/tangled_tree/layers`**

My latest branch related to the visualization API is: `develop-schema-viz-tool-cors` which is a branch that I created based on your `develop-schema-viz-tool` one. I added some code there to avoid CORS errors that I got from the front end. If it is not too much trouble, could you work by branch out of my branch? That way, I could easily merge your code to my branch later

Just to clarify the meaning of "DirectChildren" and "Children":
"DirectChildren" means the nodes that are directly linked to a particular node. 
For example, in NF, the "direct children" of "CellLine" is "Resource" and "Mutation". in HTAN, the "direct children" of "Biospecimen" are: "ScRNA-seqLevel1", "BulkRNA-seqLevel1", 'BulkWESLevel1", "OtherAssay", "ScATAC-seqLevel1", and "ImagingLevel2". In comparison, "children" means all the nodes that are linked to a particular (including nodes that link to a particular node through other nodes). For example, in NF, the children of "Donor" are: CellLine, AnimalModel, Resource, and all the nodes that are under Resource, including Usage, BioBank, VendorItem, Observation, ResourceApplication, Development. 

**Describe the solution you'd like**

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by linglp** [comment]
Eventually I decided not to create two new endpoints, but instead just modifying the existing endpoint `/visualize/tangled_tree/layers`. After making some changes to branch `develop-schema-viz-tool-cors`, when you call the endpoint by using a schema URL, it will return a list of nodes following the format like below: 
```
    {
      "id": "Biospecimen",
      "parents": [
        "Patient"
      ],
      "direct_children": [
        "OtherAssay",
        "ScRNA-seqLevel1",
        "BulkRNA-seqLevel1",
        "BulkWESLevel1",
        "ScATAC-seqLevel1",
        "ImagingLevel2"
      ],
      "children": [
        "BulkWESLevel3",
        "ScRNA-seqLevel3",
        "BulkWESLevel1",
        "ScRNA-seqLevel1",
        "BulkWESLevel2",
        "ImagingLevel2",
        "BulkRNA-seqLevel1",
        "ScATAC-seqLevel1",
        "ScRNA-seqLevel2",
        "OtherAssay",
        "BulkRNA-seqLevel3",
        "ScRNA-seqLevel4",
        "BulkRNA-seqLevel2"
      ]
    }
```

**Comment by linglp** [comment]
Also @milen-sage when would be a good time to merge endpoints and functions related to schema viz to develop? Mialy has been keeping them separate in her branch `develop-schema-viz-tool`, and I created a branch called `develop-schema-viz-tool-cors` to resolve cors errors (and also changed some functionalities related to this issue).

**Comment by milen-sage** [comment]
@linglp when you are back from vacation :) It's getting close to ready.

**Comment by milen-sage** [comment]
Yes, I think it's probably a good time to merge, especially after our conversation about deploying on the HTAN data portal soon. From your perspective @linglp is there anything that's currently missing from these endpoints; or as a 1st version they are fine for the current visualization JS logic?

**Comment by linglp** [comment]
@milen-sage Yes. Sounds good. I will make an issue for myself to merge. All the endpoints required by the visualization are there. Only thing is we added the `flask-cors` package for handling cors errors. For the develop branch, this package needs to be added
