### ISSUE TITLE
Feature to allow table updates

### ISSUE THREAD

**Issue by brynnz22** [Sage-Bionetworks/schematic#835]
**Is your feature request related to a problem? Please describe.**
Related to #834 issue where updating tables in Synapse does not work properly. CSBC needs a table feature that allows for multiple manifests to be submitted using the table feature. The new manifest will append the rows onto the table, not replace them, and many manifests can be saved (instead of one manifest).

**Describe the solution you'd like**
Every time a new manifest is uploaded to the same Synapse folder (the same component) using the table feature, we would like the table to update properly by appending the rows and saving the new manifest in addition to the old manifests.

**How important is this feature?** Select from the options below:
• 🌋 Important - it's a blocker and can't do work without it!

**When will use cases depending on this become relevant?** Select from the options below:
• We have use cases for this now. Since we use a publication crawler script every month to get new publications, we consistently use new manifests.

**Comment by brynnz22** [comment]
@GiaJordan Looks like a requested this feature in July. I updated it a bit to be clearer since we are now clear what all the bugs/features are.

**Comment by GiaJordan** [comment]
@brynnz22 thanks for finding this!

**Comment by GiaJordan** [comment]
AC:
parameter that changes the default behavior of manifest table uploads(replacing existing data) and instead appends new data to the table while preserving old data
Possibly in config since will likely be similar for a given project

**Comment by aclayton555** [comment]
@milen-sage we understand from our stakeholder meeting today that this request was previously deprioritized. We were not aware of this, so thank you for this update. However, Brynn, Verena and I discussed further that we would ideally like to have this available by mid December 2022 at the latest to allow sufficient time for testing (in parallel with our Synapse project back-population and DCA roll-out). Can this please be prioritized for an upcoming sprint? 
FYI @AmyHeiser

**Comment by milen-sage** [comment]
@aclayton555 we are working on the feature this and next sprint. Will follow up when it's ready, but meanwhile, we'll use this issue to capture some of the technical discussion around the implementation.

**Comment by GiaJordan** [comment]
> * [x]  setting up working unit/integration testing for existing table replacement functionality, even if it's not optimal at this time
Addressed in #1046

**Comment by AmyHeiser** [comment]
Hi Gianna, I see the status change to PR Pending, does that mean we are ready for SCCE team testing of the Upsert feature?  
Thanks!

**Comment by GiaJordan** [comment]
Hi @AmyHeiser, Almost. This PR requires #1101 and #1092 to be merged first. We'll be reviewing all of these at code review this afternoon. I'll update after!

**Comment by GiaJordan** [comment]
@AmyHeiser #1092 created issues with the api that we'll need to work out first

**Comment by GiaJordan** [comment]
@AmyHeiser we're in the process of merging the final prerequisite PRs for this feature. Once #1101 is merged, I'll create a docker image for this dev branch. It'll have the dependencies settled and users will be able to begin testing on this feature. I'll update with the link when it's available. Thank you!

**Comment by GiaJordan** [comment]
@AmyHeiser @brynnz22 I've created a docker image of the branch with this feature on it [here](https://hub.docker.com/layers/sagebionetworks/schematic/commit-280de2b/images/sha256-531269d7c3649ef5f7c831f77d45def5f8525a20644f806b8d50efd93fc8364b?context=explore) so that this feature can be tested with the CLI. I'm currently trying to test it out myself and will update when I'm successful. (I'm having some trouble with paths but it could be limited to my machine.) The API will be useable for this feature after I complete #1116.

**Comment by GiaJordan** [comment]
We've noticed issues across devs with our docker containers. This feature branch has now been merged so it can be tested using the cli with the `develop` branch. 

Use tips/requirements:

> - If intending to upsert to a table at a later upload, the -tm/--table_manipulation upsert parameter should still be used for the initial upload as it adds additional annotations that allow the upsert to proceed successfully.
> - The --dl/--use_display_label flag should also be used for every upload for tables intending to use the upsert feature.
> - Currently, users must also have username and authtoken specified in their .synapseConfig file to use upsert functionality.
> 
> An example command would look like
>  `schematic model -c path/to/config.yml submit -mp path/to/manifest.csv -d <datasetID> -mrt table -tm upsert -dl`

**Comment by MiekoHash** [comment]
Thanks, @GiaJordan, for the update. cc: @abbywall for D&T Project Board update.
