### ISSUE TITLE
Ints cast as floats when empty cells also present in column

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#838]
**Describe the bug**
Encountered when working on an issue related to NF. If `int` values are present in a column with empty cells, when the empty cells get cast as `np.nan`s, the `int`s get converted to `float`s to support the `nan` datatype.

**To Reproduce**

1. Import manifest with column containing `int`s and missing values
2. `Int`s get converted to type `float`

**Expected behavior**
`Int`s should remain type `int`

**Comment by GiaJordan** [comment]
@allaway I noticed this issue when I was working with the manifest you provided for #819, so if it's something you've encountered since then, it's being addressed!

**cc:** @ychae and @milen-sage

**Comment by allaway** [comment]
Oh interesting! I wonder if this is related to #664?

**Comment by GiaJordan** [comment]
@allaway Most likely not, I think it was different cause than in #664, but still on the topic of how dataframes are imported
