### ISSUE TITLE
Fix example data model list validation rule

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#846]
**Describe the bug**
When generating a manifest by using the example data model, "familyHistory" which is defined as a "list" in the data model should allow people to enter multiple values. But it is currently showing as "dropdown" and only allows one entry. This might because in the data model, we specify "familyHistory" as a "list", and we should change "list" to either "list strict" or "list like" (since validation rules have now changed)

Similarly for "Check List" attribute in the data model.

In addition, we need to add valid value in the example data model for "Check List" and see if they get pop out when creating an empty manifest

**To Reproduce**

**Expected behavior**

**Priority** (select one)
- [x] Minor ⬇️
- [ ] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**

**Additional context**

**Comment by linglp** [comment]
@GiaJordan for your awareness too

**Comment by GiaJordan** [comment]
related to [#76](https://github.com/ncihtan/data-models/issues/76)

**Comment by linglp** [comment]
This is also related to the issue that @afwillia mentioned today for endpoint /validate/manifest. We noticed that the endpoint on `develop` branch is not working properly (an example of error message: "['Breast', 'Lung'] is not one of ['Lung', 'Prostate', 'Colorectal', 'Breast', 'Skin', '']")
