### ISSUE TITLE
Endpoint for SchemaExplorer.get_nx_schema()

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic#849]
**Describe the solution you'd like**
Endpoint for SchemaExplorer.get_nx_schema()

**How important is this feature?** Select from the options below:
• 🌋 Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by milen-sage** [comment]
AC: REST API returns a networkx schema graph as [a pickle file](https://networkx.org/documentation/stable/reference/readwrite/gpickle.html).
