### ISSUE TITLE
Endpoint for SchemaGenerator.get_subgraph_by_edgetype()

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic#852]
**Describe the solution you'd like**
Endpoint for SchemaGenerator.get_subgraph_by_edgetype()

**How important is this feature?** Select from the options below:
• 🌋 Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by linglp** [comment]
@andrewelamb what should I return for function `get_subgraph_by_edge_type` (see function [here](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/schemas/generator.py#:~:text=def%20get_subgraph_by_edge_type()))? If you print out `relationship_subgraph`, it would say `DiGraph with XXX nodes and XXX edges` This is not json serializable. I am thinking maybe I could just return `relationship_subgraph.edges`? So for example, if you use the example data model, and want to know about relationship `requiresDependency`, you could see the following: 

```
[
  [
    "Patient",
    "PatientID"
  ],
  [
    "Patient",
    "Sex"
  ],
  [
    "Patient",
    "YearofBirth"
  ],
  [
    "Patient",
    "Diagnosis"
  ],
  [
    "Patient",
    "Component"
  ],
  [
    "Cancer",
    "CancerType"
  ],
  [
    "Cancer",
    "FamilyHistory"
  ],
  [
    "Biospecimen",
    "SampleID"
  ],
  [
    "Biospecimen",
    "PatientID"
  ],
  [
    "Biospecimen",
    "TissueStatus"
  ],
  [
    "Biospecimen",
    "Component"
  ],
  [
    "BulkRNA-seqAssay",
    "Filename"
  ],
  [
    "BulkRNA-seqAssay",
    "SampleID"
  ],
  [
    "BulkRNA-seqAssay",
    "FileFormat"
  ],
  [
    "BulkRNA-seqAssay",
    "Component"
  ],
  [
    "BAM",
    "GenomeBuild"
  ],
  [
    "CRAM",
    "GenomeBuild"
  ],
  [
    "CRAM",
    "GenomeFASTA"
  ],
  [
    "CSV/TSV",
    "GenomeBuild"
  ],
  [
    "MockComponent",
    "Component"
  ],
  [
    "MockComponent",
    "CheckList"
  ],
  [
    "MockComponent",
    "CheckRegexList"
  ],
  [
    "MockComponent",
    "CheckRegexSingle"
  ],
  [
    "MockComponent",
    "CheckRegexFormat"
  ],
  [
    "MockComponent",
    "CheckNum"
  ],
  [
    "MockComponent",
    "CheckFloat"
  ],
  [
    "MockComponent",
    "CheckInt"
  ],
  [
    "MockComponent",
    "CheckString"
  ],
  [
    "MockComponent",
    "CheckURL"
  ],
  [
    "MockComponent",
    "CheckMatchatLeast"
  ],
  [
    "MockComponent",
    "CheckMatchatLeastvalues"
  ],
  [
    "MockComponent",
    "CheckMatchExactly"
  ],
  [
    "MockComponent",
    "CheckMatchExactlyvalues"
  ],
  [
    "MockComponent",
    "CheckRecommended"
  ],
  [
    "MockComponent",
    "CheckAges"
  ],
  [
    "MockComponent",
    "CheckUnique"
  ],
  [
    "MockComponent",
    "CheckRange"
  ]
]
```

Let me know if that works.

**Comment by andrewelamb** [comment]
@linglp Mialy's code that I'm refactoring is [here.](https://github.com/Sage-Bionetworks/schematic/blob/develop-rdb/schematic/db/rdb.py)

In her code the subgraph gets created [here.](https://github.com/Sage-Bionetworks/schematic/blob/develop-rdb/schematic/db/rdb.py#L63)

The subgraph gets used [here](https://github.com/Sage-Bionetworks/schematic/blob/develop-rdb/schematic/db/rdb.py#L64), [here](https://github.com/Sage-Bionetworks/schematic/blob/develop-rdb/schematic/db/rdb.py#L174) and [here.](https://github.com/Sage-Bionetworks/schematic/blob/develop-rdb/schematic/db/rdb.py#L210)

To be honest I haven't looked at this code that much so I don't have the best answer to your question. @milen-sage Maybe you could weigh in?

**Comment by linglp** [comment]
Okay. Thanks for the context @andrewelamb . I took a look at your code, and I think if I return what I currently have, and if you could call `nx.DiGraph()` function again, and then use `add_edges_from` function just like schematic, so something like: 
```
db_schema_graph = nx.DiGraph()
db_schema_graph.add_edges_from(Arr) --> here Arr is what I returned from API
```

This should then work, and you could do something like `db_schema_graph.nodes()` later in your code. @milen-sage let me know what you think!

**Comment by milen-sage** [comment]
@andrewelamb I'd expect adding some logic to process schematic's REST API responses when refactoring schematic's existing DB code into schematic-db. 

What @linglp suggested above should work conceptually. But you could see if there's a better way to handle the REST API response. Also, if you need a specific response format, you can call that out in advance here as well.
