### ISSUE TITLE
Endpoint for SchemaGenerator.get_subgraph_by_edge_type()

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic#853]
**Describe the solution you'd like**
Endpoint for SchemaGenerator.get_subgraph_by_edge_type()

**How important is this feature?** Select from the options below:
• 🌋 Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by milen-sage** [comment]
@andrewelamb looks like this is a duplicate of #852?

**Comment by andrewelamb** [comment]
@milen-sage  yep!

**Comment by andrewelamb** [comment]
@milen-sage Yep!
