### ISSUE TITLE
In JIRA: schematic: expose default schema load in config

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#856]
Provide a config option for the default schema to load; we can still use biothings as a default for now, but can also move to schema.org or a different schema in the future.

AC: 
- allow empty schema 
- allow a specific schema

**Comment by milen-sage** [comment]
This is a follow up on #708

**Comment by mialy-defelice** [comment]
@milen-sage @MiekoHash what is the priority for this issue for Sprint 3?

**Comment by milen-sage** [comment]
This would be lowest priority for this sprint unless you think it would inform refactor implementation.
