### ISSUE TITLE
Refactor data_model_parser

### ISSUE THREAD

**Issue by mialy-defelice** [Sage-Bionetworks/schematic#857]
Actually start writing all the code for the new data model parser, which takes in either a JSONLD or CSV data model and returns a dictionary that can be used to create nodes and edges in a network graph.

For @MiekoHash and others, there are two main user scenarios we want to enable with this work (each comprising multiple user stories): 

"As a RSE, I want to be able to add new features of schema classes and properties (such as attribute context relevant for all DCC projects) and have corresponding functions in the data model parser that I'd need to change in one place for each new class or property feature. That way I would avoid having to look up and make changes in redundant data-model parser code snippets, and that would allow me to support new types of schema object features at least 3x faster. (Currently code snippets repeat the same business logic applied to properties and classes more than three times in the data model parser code and are not encapsulated as modules.)"

"As a RSE, I want to  be able to add new schema formats that schematic can parse natively, so that I can add support for reading LinkML data schema files (e.g. the latter capturing data models in INCLUDE and Bridge2AI)."

**Comment by milen-sage** [comment]
@mialy-defelice do you think breaking down this in smaller issues would be helpful? E.g. we can capture the parser methods you have laid out in the refactor design as their own issues?

**Comment by mialy-defelice** [comment]
For Sprint2.2023 the AC is to break down this portion of the refactor into additional issues. Can link them here.

Sending documentation to Mieko.

**Comment by MiekoHash** [comment]
Requested LucidChart account via IT ticket.

**Comment by MiekoHash** [comment]
Rec'd LucidChart account and now I can see the class diagram. Plan to review the docs in the next couple of weeks.

**Comment by mialy-defelice** [comment]
Create issues for the following:

- [ ] CSV Parser
- [ ] JSONLD Parser
- [ ] Data Model Graph
- [ ] Data Model Validator
- [ ] Data Model JSONLD
- [ ] Data Model JSON Validation Schema

**Comment by mialy-defelice** [comment]
I have just been coming up with User Stories. Need catalog of actual user stories to link them properly.
