### ISSUE TITLE
Create test cases for functions in store/synapse.py

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#866]
**Is your feature request related to a problem? Please describe.**
Write tests for functions in store/synapse.py. Token could be included in the GitHub action. 

**Describe the solution you'd like**

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Additional context**

**Comment by milen-sage** [comment]
This may be done as part of the REST API testing? Feel free to close if ready @linglp

**Comment by linglp** [comment]
We could still add more unit tests for functions in `store/synapse.py`. But those that are related to APIs have already been covered by `test_api.py`

**Comment by milen-sage** [comment]
Perfect - this is less urgent technical debt then. We can open a separate issue for it later.
