### ISSUE TITLE
File rename based on HTAN IDs and unique string (e.g. base62)

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#87]
Following the SOP here 

https://docs.google.com/document/d/1K6jjWQdvtGRKUMmjC7jvt69hd3CbnSyryVWpNJVndDA/edit?usp=sharing

we want to change the original filename to a guaranteed unique one upon upload to Synapse.

#roadmap

**Comment by ecerami** [comment]
Follow-up discussion with @milen-sage.  When we say "we want to change the original filename", we are really just changing the "display name" within Synapse.  The original file in the cloud bucket will remain the same.

**Comment by milen-sage** [comment]
@jguinney @vthorsson @schultzn - just FYI the discussion on filenames is resolved^ and we can review as part of the data ingress workflow during the next DCC call.
