### ISSUE TITLE
Component not present error when trying to submit manifest 

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#874]
**Describe the bug**

**To Reproduce**
1. Run the following command to validate manifest: `schematic model -c config.yml validate -mp /Users/lpeng/Documents/test-schematic/CA184897_1.csv -dt DatasetView `
I could see that the message here: Your manifest has been validated successfully. There are no errors in your manifest, and it can be submitted without any modifications.

2. Try to submit the manifest by using the following command: `schematic model -c config.yml submit -mp /Users/lpeng/Documents/test-schematic/CA184897_1.csv -d syn33691763 -vc DatasetView -mrt table` Here, I could see error message: error: Component 'DatasetView' is not present in 'tests/data/CSBCDataModel_new.jsonld', or is invalid.

A few notes: 
1) The error message here is confusing. It should raise a different error message to indicate a different error. Please note that this error was not triggered by `self.sg.se.is_class_in_schema(validate_component)` in [here](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/models/metadata.py#:~:text=self.sg.se.is_class_in_schema(validate_component))
2) I think the error was raised because `getDatasetProject` function from `upload_format_manifest_table` [here](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/store/synapse.py#:~:text=schema%20%3D%20Schema(name%3Dtable_name%2C%20columns%3Dcol_schema%2C%20parent%3Dself.getDatasetProject(datasetId))) is trying to see if the dataset ID that we are feeding is a Project. Since `syn33691763` is only a folder, `self.getDatasetProject(datasetId)` is returning nothing. (see [here](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/store/synapse.py#:~:text=already%20project%20itself-,try%3A,return%20datasetId,-except%20SynapseHTTPError%3A)) We might need to add an additional parameter to let users feed project ID if they want to submit a table. 

**Expected behavior**

**Priority** (select one)
- [ ] Minor ⬇️
- [X] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**

**Additional context**

**Comment by linglp** [comment]
After hard-coded my own project ID [here:](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/store/synapse.py#:~:text=schema%20%3D%20Schema(name%3Dtable_name%2C%20columns%3Dcol_schema%2C%20parent%3Dself.getDatasetProject(datasetId))) 
`schema = Schema(name=table_name, columns=col_schema, parent=self.getDatasetProject("syn27221721"))`, I used a different dataset folder by running command: `schematic model -c config.yml submit -mp /Users/lpeng/Documents/test-schematic/CA184897_1.csv -d syn27223881 -vc DatasetView -mrt table`. It seems like the manifest could be uploaded successfully.

**Comment by GiaJordan** [comment]
It appears the dataset being referenced is not included in the fileview being used.
An an error is being raised after [here](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/store/synapse.py#L1069), that is caught in `commands.py` that displays an erroneous message explaining what went wrong.

Using a fileview that includes the dataset at hand should resolve the issue

**Comment by linglp** [comment]
@GiaJordan Thank you! I just tested it out by using `schematic model -c config.yml submit -mp /Users/lpeng/Documents/test-schematic/CA184897_1.csv -d syn30988361 -vc DatasetView -mrt table` with master fileview as `syn23643253`, and it worked!!! I think we would just need to update the error message then

**Comment by linglp** [comment]
To do: 
- [ ] Update the error message here: https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/store/synapse.py#L1069:~:text=in%20file%20view-,raise%20ValueError(,-f%22The%20given so that ValueError won't get overwritten by the Component not found error 

- [ ] Update the `submit` API endpoint so that users could update their master file view on swagger
