### ISSUE TITLE
model/submit is not using manifest_basename to name manifest in synapse

### ISSUE THREAD

**Issue by lakikowolfe** [Sage-Bionetworks/schematic#889]
**Describe the bug**
Even though I have specified `"manifest_basename": "data_flow_status_manifest"` the `model/submit` endpoint names the manifest using `synapse_storage_manifest_<component>`.

**To Reproduce**
1. Modify schematic config `manifest_basename` to anything other than "synapse_storage_manifest"
2. Submit manifest
3. View manifest in Synapse

**Expected behavior**
I would expect that the model/submit endpoint defaults to using the `manifest_basename` parameter to name the submitted manifest.

**Priority** (select one)
- [X] Minor ⬇️
- [ ] Major 📢
- [ ] Critical 🆘

**Screenshots**

Below you can see that before I updated my schematic repo the data flow status manifest was uploaded using the `manifest_basename` specified in the config ("data_flow_status_manifest.csv"). After update the uploaded manifest was named following the `synapse_storage_manifest_<component>.csv` structure regardless of what is in my config.

<img width="1229" alt="Screen Shot 2022-08-31 at 4 23 05 PM" src="https://user-images.githubusercontent.com/30699094/187801868-6227f82e-0416-4a70-a14c-e6a7e4dff273.png">

**Desktop (if applicable, please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Dev branch

**Additional context**

**Comment by linglp** [comment]
@lakikowolfe This is actually not a bug. We talked about this in the back-end code review meeting, and the decision is that we want to standardized manifest names by using the base name parameter in config. Users shouldn't change the base name parameter (and even if they do), we would change the name to `synapse_storage_manifest_<component name>`.

**Comment by linglp** [comment]
@lakikowolfe Let me double check then. Thanks for bringing this up.
