### ISSUE TITLE
Ghost Table Upload Behavior

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#914]
**Describe the bug**
When one manifest is uploaded to a given dataset, and then is no longer needed, and another manifest is uploaded to the same dataset with the intention of replacing it, rows from the first dataset persist in the table with annotations missing after the second upload, and this is not desired.

**To Reproduce**
Detailed in #834 

**Expected behavior**
Preferred behavior is to remove all rows from the existing table, and replace with only the rows from the new manifest.
In this scenario, only one manifest per datatype will be present in each project, and new information will be added onto the single manifest as appropriate. If multiple manifests exist for a given datatype, they will be separated into different projects so that only one exists within each project.

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [ x] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**

**Additional context**

**Comment by GiaJordan** [comment]
AC:
Uploading a manifest to an existing table removes all current rows and columns and replaces with new desired rows and columns, preserving synID
@milen-sage

**Comment by GiaJordan** [comment]
PR #917 for this issue is now pending review and is available for testing @lopierra @brynnz22.
Please note, this **only addresses the missing data annotations** that is lost when another manifest is uploaded; adding the feature to append multiple manifests to the same table in the case of having multiple different manifests of the same data type in the same folder will be addressed in a later PR.

**Comment by milen-sage** [comment]
> this only addresses the missing data annotations

it also addresses duplicating rows when uploading manifests.

@brynnz22 and @lopierra, as @GiaJordan mentioned, we will triage the feature allowing appending & updating specific set of rows #835 next Mon to see when it'd be tackled.

**Comment by milen-sage** [comment]
I'll tentatively add #835 to the next sprint since it seems like an important feature.

**Comment by GiaJordan** [comment]
> it also addresses duplicating rows when uploading manifests
Yes, that's correct; thank you for adding! @milen-sage
