### ISSUE TITLE
Unintentional Manifest Override

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#922]
**Describe the bug**
When two manifests are uploaded to the same dataset, ie in the case of uploading a censored and uncensored version of the same manifest. The manifests are uploaded with the same name and the 2nd manifest overrides the values of the first.

**To Reproduce**
1. Validate manifest containing sensitive ages (under 18yo or over 90yo) as a value for an attribute with the `protectAges` rule
2. submit manifest to synapse dataset
3. Only one manifest is present after completion of command instead of two

**Expected behavior**
Two manifests should be present, with `_censored` appended to the name as appropriate

**Priority** (select one)
- [ ] Minor ⬇️
- [ x] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**
 - Schematic on develop as of 9/21/2022
 - Windows 10

**Additional context**

**Comment by GiaJordan** [comment]
cc @milen-sage

**Comment by milen-sage** [comment]
@GiaJordan this only applies for censored and uncensored manifests, but doesn't apply to manifests from different components stored in the same folder correct? If that's the case @linglp may be best positioned to resolve - I think this could be related to the change around using the base config manifest name and how components names are appended.

**Comment by GiaJordan** [comment]
@milen-sage I believe so, it's because they're the same component so the names for the two manifests at upload are identical now. And I agree
