### ISSUE TITLE
Docker Installation Instructions

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#924]
**Is your feature request related to a problem? Please describe.**
Add instructions on how to download and use a schematic docker container

**Describe the solution you'd like**
Instructions added to README on docker container installation, can reference information in #882 by @BrunoGrandePhD 

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by GiaJordan** [comment]
cc: @milen-sage

**Comment by milen-sage** [comment]
Let's use FAIR Data's working session.

**Comment by milen-sage** [comment]
Docker [installation instructions PR](https://github.com/Sage-Bionetworks/schematic/pull/953).
