### ISSUE TITLE
Merge 'develop-schema-viz-tool-cors' branch to develop

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#926]
**Is your feature request related to a problem? Please describe.**
I will merge `develop-schema-viz-tool-cors` to develop. Also add `flask-cors` package. Related to the PR [here](https://github.com/Sage-Bionetworks/schematic/pull/942)

**Describe the solution you'd like**

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Additional context**

**Comment by milen-sage** [comment]
This will require a follow up with HTAN's data portal team.
