### ISSUE TITLE
Send schema-viz files to HTAN data portal team

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#933]
**Is your feature request related to a problem? Please describe.**
send files that HTAN needed for generating the attribute table and the tangled tree. Clean up code base a bit more and prepare to answer questions related to deploying schema viz tangled tree to HTAN portal (and help them update attribute table). This should be done after merging the API endpoints needed for schema viz to `develop`, so that if they have questions, they could submit an issue for the develop branch. But this does not need to go into the latest release. 

Add documentation to the schema visualization repo of the HTAN-specific branch to allow HTAN data portal team to visualize the schema.

AC:
- HTAN data portal team has all resources: data documentation and code to reproduce the visualization.

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by milen-sage** [comment]
Note this is currently blocked by HTAN schema updates: https://github.com/ncihtan/data-models/pull/99 and https://github.com/ncihtan/data-models/pull/94. Will confirm with @elv-sb on when the updates will be merged and if they are blockers on their end.

**Comment by linglp** [comment]
No. It currently doesn't do anything. Let me see if I could remove it before our meeting with HTAN today.

**Comment by linglp** [comment]
`develop-HTANDataPortal` should be ready to use. I also added documentation and toggle of "show/hide attribute table". The next step is captured in #1013
