### ISSUE TITLE
Make project_scope arg optional for submission command

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic#951]
**Describe the bug**
Title

**To Reproduce**

**Expected behavior**

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**

**Additional context**

**Comment by milen-sage** [comment]
@linglp yes this is related to #954.
