### ISSUE TITLE
Add project scope as a parameter for submitting manifest

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#955]
**Is your feature request related to a problem? Please describe.**
Project scope needs to be added as a parameter for manifest submission on swagger UI. It will need to be a required parameter in the short-term and in the long term, an optional parameter

Related to the issue [here](https://github.com/Sage-Bionetworks/schematic/issues/954)

**Describe the solution you'd like**

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by linglp** [comment]
@milen-sage I just checked: `AssociateMetadataWithFiles` function does not have `project_scope` parameter

**Comment by milen-sage** [comment]
That's good news - we don't need to worry about providing project_scope to it.

**Comment by linglp** [comment]
This is no longer needed thanks to PR #989
