### ISSUE TITLE
schematic: allow passing config and google credentials information as env variables to docker container

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#960]
Currently schematic relies on config and credential parameters stored as local files at runtime. 

schematic assumes these files will be locally available when a REST API is run.

To enable deploying schematic in a Fargate-based architecture, based on IT specifications, we'd like to avoid storing these files locally. Instead they can be passed as environmental variables when a docker image is created.

The schematic docker container (usage here #924 ) currently doesn't support env variables passing. We need to enable that.

AC:

- [ ]  change docker container to support passing environmental variables, similarly to https://github.com/Sage-Bionetworks/data_curator/issues/400

- [ ]  add logic to schematic's REST API to allow reading config and credential options as env variables passed when the docker image is created. E.g. running the REST API can check if these parameters are present as env variables and read them in, avoiding in this case to look for config and credential files.

**Comment by linglp** [comment]
related to #975
