### ISSUE TITLE
schematic: Add endpoint to check if attribute is required or not

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic#966]
**Is your feature request related to a problem? Please describe.**
For schematic_db it would be very useful to know if a manifest attribute was required or not, so that the database table could be set to nullable(or not).

**Describe the solution you'd like**
An endpoint that takes in a schema, and attribute name, and returns true or false.

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by milen-sage** [comment]
This is the function relevant here: 

https://sage-bionetworks.github.io/schematic/schematic/schemas/generator.html#SchemaGenerator.is_node_required

**Comment by andrewelamb** [comment]
@linglp In the swagger ui example both family_history and FamilyHistory return true, does this mean both the node label and display name work?
