### ISSUE TITLE
Error in manifest/generate endpoint w/ excel output

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/schematic#976]
Using the manifest/generate REST API endpoint to return an excel file errors out, returning status 500

```
  File "schematic/schematic/manifest/generator.py", line 1506, in _handle_output_format_logic
    self.populate_existing_excel_spreadsheet(output_file_path, dataframe)
  File "schematic/schematic/manifest/generator.py", line 1612, in populate_existing_excel_spreadsheet
    writer.book = workbook
AttributeError: can't set attribute 'book'
```

To reproduce, use the manifest/generate endpoint with the swagger ui with the following arguments
```
schema_url = https://raw.githubusercontent.com/Sage-Bionetworks/schematic/develop/tests/data/example.model.jsonld
title = Example
data_type = Biospecimen
oauth = true
use_annotations = false
dataset_id = syn35294937
asset_view = syn33715412
output_format = excel
```

Changing `output_format = google_sheet` successfully returns a link to the filled manifest.

**Comment by linglp** [comment]
This turned out to be an issue related to package installation. After installing the latest package by using `poetry install`, this issue gets resolved.
