### ISSUE TITLE
In JIRA: schematic: add support for new rule combination int:recommended

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#980]
Currently if a validation rule is specified as `int` for a given attribute the user has to provide an integer value. In some cases, an integer value is not applicable to some records for this attribute. 

We can allow a new validation rule combination, e.g. int:recommended that would allow a user to enter either an integer or the string "Not Applicable".

This would address https://github.com/ncihtan/data-models/issues/85 

AC: If int:recommended is specified for an attribute in the schema, a user can enter either an integer or the string "Not Applicable" for a given record and the record would pass validation.

**Comment by milen-sage** [comment]
@GiaJordan the desired functionality above is enabled via https://github.com/Sage-Bionetworks/schematic/pull/1000, albeit in a slightly different way? If so,  feel free to close this issue and move it to sprint 21. Thank you!

**Comment by milen-sage** [comment]
Sounds good! Let's keep it open for now and we'll check with @elv-sb.

**Comment by GiaJordan** [comment]
After sussing out implementation options and given the function and use case for `recommended`, this seems less like a rule combination with the `recommended` rule and more like an implementation of #780 
@MiekoHash

**Comment by GiaJordan** [comment]
Per @mialy-defelice 

- storing validation rules as `List[List[str]]` shouldn't be an issue as they aren't integral to the structure of the data model network
- confirm possibility or make changes during conversion and in [schema_utils](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/utils/schema_utils.py#L121)

**Comment by MiekoHash** [comment]
Placeholder ticket moved to JIRA https://sagebionetworks.jira.com/browse/FDS-81. @GiaJordan I think this ticket is a good example of capturing what was done in sprint 5 and tracking remaining tasks in a new ticket. When ready, please fill out the new JIRA ticket so that description and AC reflect more up-to-date status. Thanks. cc @mialy-defelice
