### ISSUE TITLE
schematic: allow reading credentials.json and token.pickle as environmental variables or just read service account credentials

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#986]
The title says it all.

**Comment by linglp** [comment]
I think this would also be useful for testing. If we could pass those credentials as environment variables, we could add some tests that currently require google credentials and have to be run locally to be run by GitHub actions.

**Comment by linglp** [comment]
@milen-sage if in #1010 , we decided that we could use service_account credentials instead of token.pickle and credentials.json, does that mean we should turn `service_account` credentials as an environment variable here (and set the default authentication mode as "service_account")?

**Comment by milen-sage** [comment]
@linglp yes, we'd need to do that, but I can imaging it wouldn't be a big change if we already have a solution for the other type of credentials (service account config should be simpler).
